export const FORMS_DE={
 'form.saveHint':'Änderungen werden erst mit Speichern übernommen.','form.firstName':'Vorname','form.lastName':'Nachname','form.abbreviation':'Kürzel','form.abbreviationHint':'Vorschlag wird bei Namensänderungen automatisch aktualisiert; manuelle Eingaben bleiben erhalten.','form.defaultNumber':'Standard-Nr.','form.defaultPosition':'Standard-Position','form.abbreviationTaken':'Kürzel ist bereits vergeben.',
 'form.selectTeamSeason':'Team und Saison auswählen.','form.numberShort':'Nr.','form.position':'Position','form.saveRoster':'Kader speichern','form.playerEdit':'Spielerin bearbeiten','form.playerCreate':'Spielerin anlegen','form.teamEdit':'Team bearbeiten','form.teamCreate':'Team anlegen','form.seasonEdit':'Saison bearbeiten','form.seasonCreate':'Saison anlegen','form.label':'Bezeichnung','form.start':'Start','form.end':'Ende','form.kind':'Art','form.defaultScouting':'Standard-Protokollierung',
 'form.quickDiscardConfirm':'Das spontane Scouting enthält bereits Einträge. Beim Wechsel in ein reguläres Scouting werden diese Einträge verworfen. Fortfahren?','form.regularActive':'Reguläres Scouting aktiv · Spielangaben prüfen und Spiel übernehmen.',
 'library.onDevice':'Auf diesem Gerät','library.ownFallback':'Eigenes Team','library.opponentFallback':'Gegner','library.cloudUnavailable':'Cloud-Spielbibliothek nicht verfügbar: {error}',
 'status.wait':'⌛ Bitte warten …','status.undoOne':'Letzten Eintrag inklusive Spielzustand zurückgenommen · Redo verfügbar.','status.undoMany':'Letzte Aktion inklusive Spielzustand zurückgenommen · Redo verfügbar.','status.redoOne':'Letzten Eintrag wiederhergestellt.','status.redoMany':'Letzte Aktion wiederhergestellt.',
 'import.csvLoaded':'{count} CSV-Einträge geladen; Spielzustand rekonstruiert.','import.masterMissing':'Keine VolleyTakt-Stammdaten.','import.masterDone':'Stammdaten importiert.','status.ratingUnavailable':'Bewertung {value} ist im aktuellen Profil nicht verfügbar.','status.sessionResumed':'Session wiederaufgenommen · Sätze {setsUs}:{setsThem} · {scoreUs}:{scoreThem} · {rotation}.','status.migrationPaused':'Datenmigration ausgesetzt. Lokale Nutzdaten wurden nicht verändert.'
};
export const FORMS_EN={
 'form.saveHint':'Changes are applied only after you select Save.','form.firstName':'First name','form.lastName':'Last name','form.abbreviation':'Abbreviation','form.abbreviationHint':'The suggestion updates automatically when the name changes; manual entries are preserved.','form.defaultNumber':'Default no.','form.defaultPosition':'Default position','form.abbreviationTaken':'This abbreviation is already in use.',
 'form.selectTeamSeason':'Select team and season.','form.numberShort':'No.','form.position':'Position','form.saveRoster':'Save roster','form.playerEdit':'Edit player','form.playerCreate':'Create player','form.teamEdit':'Edit team','form.teamCreate':'Create team','form.seasonEdit':'Edit season','form.seasonCreate':'Create season','form.label':'Label','form.start':'Start','form.end':'End','form.kind':'Type','form.defaultScouting':'Default scouting profile',
 'form.quickDiscardConfirm':'Quick scouting already contains entries. Switching to regular scouting will discard these entries. Continue?','form.regularActive':'Regular scouting active · review the match details and apply the match.',
 'library.onDevice':'On this device','library.ownFallback':'Own team','library.opponentFallback':'Opponent','library.cloudUnavailable':'Cloud match library unavailable: {error}',
 'status.wait':'⌛ Please wait …','status.undoOne':'Last entry including match state undone · Redo available.','status.undoMany':'Last action including match state undone · Redo available.','status.redoOne':'Last entry restored.','status.redoMany':'Last action restored.',
 'import.csvLoaded':'{count} CSV entries loaded; match state reconstructed.','import.masterMissing':'No VolleyTakt master data found.','import.masterDone':'Master data imported.','status.ratingUnavailable':'Rating {value} is not available in the current profile.','status.sessionResumed':'Session resumed · Sets {setsUs}:{setsThem} · {scoreUs}:{scoreThem} · {rotation}.','status.migrationPaused':'Data migration paused. Local user data was not changed.'
};
