export const MATCH_DE={
 'match.lineupDuplicate':'Eine Spielerin darf in der Startaufstellung nicht mehrfach vorkommen.','match.liberoDuplicate':'Libero 1 und Libero 2 müssen unterschiedliche Spielerinnen sein.','match.liberoLineupConflict':'Ein ausgewählter Libero darf nicht gleichzeitig Teil der Startaufstellung I–VI sein.','match.applyLineup':'Übernehmen','match.quickScouting':'Spontanes Scouting','match.videoAssignments':'Videospeicher / Zuordnung','match.prepareSet':'Satz {set} vorbereiten','match.prepareSetAgain':'Satz {set} neu vorbereiten','match.changeOwnLineup':'Aufstellung Wir ändern','match.changeOpponentLineup':'Aufstellung Gegner ändern','match.resetScouting':'Scouting zurücksetzen','match.cancel':'Abbrechen','match.date':'Spieldatum','match.ownTeam':'Eigenes Team','match.opponent':'Gegner','match.mode':'Spielmodus','match.modeRegular':'Regulär · 3 Gewinnsätze (max. 5)','match.modeFixed':'Feste Anzahl Sätze','match.final25':'normal bis 25','match.final15':'verkürzt bis 15','match.scoutOpponent':'Gegner mitscouten / Startaufstellung erfassen','match.apply':'Spiel übernehmen','match.applyHelp':'Die Spielangaben werden erst mit „Spiel übernehmen“ angelegt. „Abbrechen“ verwirft die Eingabe vollständig.','match.library':'Spielbibliothek','match.libraryDesc':'Automatisch gespeicherte Spiele auf diesem Gerät und – bei aktiver Synchronisation – aus der Cloud.','match.newButton':'Neues Spiel','match.refreshCloud':'Cloud aktualisieren','match.resetTitle':'Scouting dieses Spiels vollständig zurücksetzen?','match.resetBody':'Protokoll, Punkte, Sätze, Aufstellungen, Wechsel und Rallys dieses Spiels werden gelöscht.','match.resetKeep':'Erhalten bleiben: Spieldatum, Saison, Teams, Spiel-/Kaderart, Spielkader sowie die Einstellungen für Gegner-Scouting und Bewertung.','match.createCancelled':'Spielanlage abgebrochen · kein neues Spiel angelegt.','match.typeRequired':'Bitte eine vorhandene Spiel-/Kaderart auswählen. Neue Spielarten werden ausschließlich in den Stammdaten manuell angelegt.','match.baseApplied':'Spielbasis übernommen · Satz 1 wird vorbereitet.','match.cloudBusy':'⌛ Cloud …',
 'library.editMeta':'Spieldaten bearbeiten','library.actualDate':'Tatsächliches Spieldatum','library.cloudNewer':'Cloud · neuer als lokal','library.cloud':'Cloud',
 'library.continue':'Fortsetzen','library.video':'Video','library.times':'Zeiten','library.review':'Review','library.analyze':'Analyse','library.active':'Aktiv','library.interrupted':'Unterbrochen','library.ended':'Beendet','library.set':'Satz {set}','library.sets':'Sätze {us}:{them}'
};
export const MATCH_EN={
 'match.lineupDuplicate':'A player cannot appear more than once in the starting lineup.','match.liberoDuplicate':'Libero 1 and Libero 2 must be different players.','match.liberoLineupConflict':'A selected libero cannot also be part of the starting lineup I–VI.','match.applyLineup':'Apply','match.quickScouting':'Quick scouting','match.videoAssignments':'Video storage / assignment','match.prepareSet':'Prepare set {set}','match.prepareSetAgain':'Prepare set {set} again','match.changeOwnLineup':'Change our lineup','match.changeOpponentLineup':'Change opponent lineup','match.resetScouting':'Reset scouting','match.cancel':'Cancel','match.date':'Match date','match.ownTeam':'Own team','match.opponent':'Opponent','match.mode':'Match format','match.modeRegular':'Regular · best of 5 sets','match.modeFixed':'Fixed number of sets','match.final25':'standard to 25','match.final15':'short set to 15','match.scoutOpponent':'Scout opponent / enter starting lineup','match.apply':'Apply match','match.applyHelp':'The match is created only when you select “Apply match”. “Cancel” discards the complete input.','match.library':'Match library','match.libraryDesc':'Matches saved automatically on this device and, when synchronization is enabled, from the cloud.','match.newButton':'New match','match.refreshCloud':'Refresh cloud','match.resetTitle':'Reset all scouting data for this match?','match.resetBody':'Protocol, points, sets, lineups, substitutions and rallies for this match will be deleted.','match.resetKeep':'Retained: match date, season, teams, match/roster type, match roster and opponent-scouting/rating settings.','match.createCancelled':'Match setup cancelled · no new match created.','match.typeRequired':'Select an existing match / roster type. New match types are created manually only in master data.','match.baseApplied':'Match setup applied · set 1 will be prepared.','match.cloudBusy':'⌛ Cloud …',
 'library.editMeta':'Edit match data','library.actualDate':'Actual match date','library.cloudNewer':'Cloud · newer than local','library.cloud':'Cloud',
 'library.continue':'Continue','library.video':'Video','library.times':'Times','library.review':'Review','library.analyze':'Analyze','library.active':'Active','library.interrupted':'Interrupted','library.ended':'Ended','library.set':'Set {set}','library.sets':'Sets {us}:{them}'
};
