export const REPORTS_DE={
 'report.language':'Reportsprache','report.languageHelp':'Die Reportsprache ist unabhängig von der Sprache der Benutzeroberfläche.','report.german':'Deutsch','report.english':'English',
 'report.createTitle':'Report erzeugen','report.chooseAudience':'Wähle die Zielgruppe. Alle Ausgaben verwenden dieselbe gefilterte Datenbasis; Trainerreports gibt es als Kurz- oder Detailfassung.','report.team':'Für Spielerinnen · Team','report.teamDesc':'Kurz, verständlich und handlungsorientiert. Mit Stärken, Verbesserungsfeldern, Trainingsfokus und Begriffshilfe.','report.personal':'Persönlicher Spielerinnenreport','report.personalDescLong':'Individuelle Auswertung einer Spielerin für den gewählten Zeitraum; als persönlicher Report verteilbar.','report.openPersonal':'Persönlichen Report öffnen','report.forCoach':'Für Trainer','report.forCoachDesc':'Priorisierte Erkenntnisse, Interpretationen, Spielphasen, Rotationen, Kontext und Trainingsableitung.','report.short':'Kurzreport','report.detail':'Detailreport','report.teamCopied':'Team-Report als Text kopiert.','report.copyFailed':'Kopieren fehlgeschlagen: {error}','report.pngSaved':'PNG gespeichert: {name}','report.pngSavedSimple':'PNG gespeichert.','report.pngFailed':'PNG-Export fehlgeschlagen: {error}','report.shareFallback':'Teilen wird vom Browser nicht unterstützt; der Text wurde kopiert.','report.teamShared':'Team-Report an die Teilen-Funktion übergeben.','report.personalCopied':'Persönlicher Report als Text kopiert.','report.personalShared':'Persönlicher Report an die Teilen-Funktion übergeben.','report.trainerCopied':'Trainerreport als Text kopiert.','report.trainerShared':'Trainerreport an die Teilen-Funktion übergeben.','report.shareFailed':'Teilen fehlgeschlagen: {error}',
 'report.personal.brand':'VolleyTakt · Persönlicher Spielerinnenreport','report.personal.badge':'persönlich','report.personal.introTitle':'Individuelle Auswertung','report.personal.introBody':'Dieser Report zeigt die im ausgewählten Zeitraum erfassten Aktionen von {player}. Er nutzt die fachliche Logik der Spielerinnenanalyse, ohne die Spielerin mit Teamkolleginnen zu bewerten oder aus einzelnen Aktionen Ursachen abzuleiten. Alle vorhandenen Qualitätsbewertungen werden berücksichtigt; Aktionen ohne WIE-Bewertung werden separat ausgewiesen.',
 'report.personal.metricsTitle':'Kernwerte','report.personal.actions':'Aktionen','report.personal.allRated':'alle mit WIE','report.personal.unratedCount':'{count} ohne WIE','report.personal.positivePerfect':'positiv / perfekt','report.personal.highQuality':'# / + bzw. hohe Qualitätsstufe','report.personal.neutralLimited':'neutral / eingeschränkt','report.personal.intermediate':'Zwischenbewertungen','report.personal.negativeError':'negativ / Fehler','report.personal.lowQuality':'− / = bzw. niedrige Qualitätsstufe','report.personal.overallDistribution':'Qualitätsverteilung gesamt: {distribution}',
 'report.personal.strengthTitle':'✓ Individuelle Stärke','report.personal.noStrength':'Aus den erfassten Aktionen lässt sich noch keine belastbare positive Stärke ableiten. Eine niedrige Fehlerquote allein wird nicht als Stärke gewertet.','report.personal.focusTitle':'→ Persönlicher Entwicklungsfokus','report.personal.noFocus':'Noch kein eindeutiger Entwicklungsfokus aus den erfassten Aktionen ableitbar.',
 'report.personal.skillsTitle':'Techniken im ausgewählten Zeitraum','report.personal.skillsHelp':'Alle gespeicherten Qualitätswerte bleiben sichtbar. „ohne WIE“ kennzeichnet Aktionen ohne Qualitätsbewertung.','report.personal.skill':'Technik','report.personal.distribution':'Qualitätsverteilung','report.personal.positive':'positiv','report.personal.neutralShort':'neutral / eingeschr.','report.personal.negative':'negativ / Fehler','report.personal.unrated':'ohne WIE','report.personal.noActions':'Keine Aktionen.',
 'report.personal.rotationsTitle':'Rotationen im individuellen Kontext','report.personal.rotationRow':'{count} Aktionen · {neutral} neutral/eingeschr.{unrated}','report.personal.rotationUnrated':' · {count} ohne WIE','report.personal.noRotation':'Keine Rotationsdaten.','report.personal.balanceNote':'Die Bilanz hier ist ausschließlich positiv/perfekt minus negativ/fehlerhaft für die Aktionen dieser Spielerin. Neutrale/eingeschränkte Aktionen verändern die Bilanz nicht; Aktionen ohne WIE werden separat gezählt. Es handelt sich nicht um eine Punkt- oder Kausalitätsbilanz.','report.personal.glossaryTitle':'Begriffe kurz erklärt',
 'report.personal.metricLine':'{actions} Aktionen · positiv {positive} · neutral {neutral} · negativ {negative}','report.personal.qualityLine':'Qualität: {distribution}','report.personal.playerFallback':'Spielerin','report.personal.pngUnsupported':'Bildexport wird von diesem Browser nicht unterstützt.','report.personal.pngFailed':'PNG konnte nicht erzeugt werden.','report.personal.dataNote':'Aus erfassten VolleyTakt-Daten · keine bewiesene Ursache oder Rangliste.','report.personal.focusContext':'Die Kennzahlen beschreiben die erfassten Aktionen im ausgewählten Zeitraum und keine allgemeine Bewertung der Spielerin.'
};
export const REPORTS_EN={
 'report.language':'Report language','report.languageHelp':'The report language is independent of the user interface language.','report.german':'German','report.english':'English',
 'report.createTitle':'Create report','report.chooseAudience':'Choose the audience. All outputs use the same filtered data set; coach reports are available as a summary or detailed version.','report.team':'Team report for players','report.teamDesc':'Concise, easy to understand and action-oriented, with strengths, improvement areas, practice focus and a terminology guide.','report.personal':'Personal player report','report.personalDescLong':'Individual analysis of one player for the selected period, prepared as a personal report that can be shared.','report.openPersonal':'Open personal report','report.forCoach':'For coaches','report.forCoachDesc':'Prioritized findings, interpretations, match phases, rotations, context and practice implications.','report.short':'Summary report','report.detail':'Detailed report','report.teamCopied':'Team report copied as text.','report.copyFailed':'Copy failed: {error}','report.pngSaved':'PNG saved: {name}','report.pngSavedSimple':'PNG saved.','report.pngFailed':'PNG export failed: {error}','report.shareFallback':'Sharing is not supported by this browser; the text was copied instead.','report.teamShared':'Team report passed to the system share function.','report.personalCopied':'Personal report copied as text.','report.personalShared':'Personal report passed to the system share function.','report.trainerCopied':'Coach report copied as text.','report.trainerShared':'Coach report passed to the system share function.','report.shareFailed':'Sharing failed: {error}',
 'report.personal.brand':'VolleyTakt · Personal player report','report.personal.badge':'personal','report.personal.introTitle':'Individual analysis','report.personal.introBody':'This report shows the actions recorded for {player} during the selected period. It uses the player-analysis framework without ranking the player against teammates or inferring causes from individual actions. All available quality ratings are included; actions without a quality rating are shown separately.',
 'report.personal.metricsTitle':'Key metrics','report.personal.actions':'Actions','report.personal.allRated':'all rated','report.personal.unratedCount':'{count} without rating','report.personal.positivePerfect':'positive / perfect','report.personal.highQuality':'# / + or high quality level','report.personal.neutralLimited':'neutral / limited','report.personal.intermediate':'intermediate ratings','report.personal.negativeError':'negative / error','report.personal.lowQuality':'− / = or low quality level','report.personal.overallDistribution':'Overall quality distribution: {distribution}',
 'report.personal.strengthTitle':'✓ Individual strength','report.personal.noStrength':'The recorded actions do not yet support a robust positive strength. A low error rate alone is not treated as a strength.','report.personal.focusTitle':'→ Personal development focus','report.personal.noFocus':'No clear development focus can yet be derived from the recorded actions.',
 'report.personal.skillsTitle':'Skills in the selected period','report.personal.skillsHelp':'All stored quality ratings remain visible. “without rating” marks actions for which no quality rating was recorded.','report.personal.skill':'Skill','report.personal.distribution':'Quality distribution','report.personal.positive':'positive','report.personal.neutralShort':'neutral / limited','report.personal.negative':'negative / error','report.personal.unrated':'without rating','report.personal.noActions':'No actions.',
 'report.personal.rotationsTitle':'Rotations in the individual context','report.personal.rotationRow':'{count} actions · {neutral} neutral/limited{unrated}','report.personal.rotationUnrated':' · {count} without rating','report.personal.noRotation':'No rotation data.','report.personal.balanceNote':'The balance shown here is positive/perfect minus negative/error actions for this player only. Neutral/limited actions do not change the balance; actions without a rating are counted separately. This is not a score or a causal assessment.','report.personal.glossaryTitle':'Key terms',
 'report.personal.metricLine':'{actions} actions · positive {positive} · neutral {neutral} · negative {negative}','report.personal.qualityLine':'Quality: {distribution}','report.personal.playerFallback':'Player','report.personal.pngUnsupported':'Image export is not supported by this browser.','report.personal.pngFailed':'The PNG could not be created.','report.personal.dataNote':'Based on recorded VolleyTakt data · no proven cause or ranking.','report.personal.focusContext':'These metrics describe the recorded actions in the selected period and are not a general evaluation of the player.'
};
