export const SHELL_DE={
 'shell.startSubtitle':'Web {version} · Livescouting · modulare Kamera-Synchronisation','shell.matchSetup':'Spiel einrichten','shell.quickStart':'? Schnellstart','shell.sets':'Sätze {us} : {them}','shell.serve':'Aufschlag: {side}','shell.localReady':'lokal bereit',
 'shell.scout':'Scouten','shell.inputStep':'Eingabeschritt','shell.who':'WER','shell.what':'WAS','shell.how':'WIE','shell.where':'WO','shell.target':'WOHIN','shell.quickScout':'Spontan scouten','shell.detailedScout':'Detailliert scouten','shell.technique':'Technik (WAS)','shell.quality':'Qualität (WIE)',
 'shell.protocol':'Live-Protokoll','shell.insertBefore':'Aktion vor markierter Zeile einfügen','shell.time':'Zeit','shell.rotationShort':'Rot.','shell.player':'Spielerin','shell.action':'Aktion','shell.value':'Wert','shell.score':'Stand','shell.note':'Notiz','shell.optional':'optional',
 'shell.ownTeam':'Eigenes Team','shell.opponent':'Gegner','shell.fullscreen':'Vollbild wiederherstellen','shell.protocolButton':'☷ Protokoll','shell.switchCourt':'Felddarstellung umschalten','shell.net':'NETZ','shell.opponentAttackTarget':'Gegner-Angriff: Zielposition im eigenen Feld wählen.','shell.rotateBack':'↶ Rotation','shell.rotateForward':'Rotation ↷','shell.substitution':'↔ Wechsel','shell.libero':'L Libero',
 'shell.corrections':'Korrekturen','shell.pointUs':'+ Punkt Wir','shell.pointOpponent':'+ Punkt Gegner','shell.correctScore':'Spielstand korr.','shell.sideoutManual':'Side-out manuell','shell.cancelAction':'Aktion abbrechen','shell.ready':'Bereit.','shell.local':'☁ lokal','shell.cameraDisconnected':'Kamera getrennt',
 'shell.cameraConnected':'verbunden','shell.cameraStable':'Stabil','shell.cameraBattery':'Kamera-Akku','shell.recordStart':'● Aufnahme starten','shell.recordStop':'■ Aufnahme stoppen','shell.syncReady':'Sync bereit',
 'tour.close':'Einführung schließen','tour.dontShow':'nicht mehr zeigen',
 'startup.error':'Startfehler: {message}\nBitte Screenshot senden.','startup.unknownInit':'Unbekannter Initialisierungsfehler','startup.jsError':'JavaScript-Fehler','startup.promiseError':'Promise-Fehler','startup.moduleIncomplete':'App-Modul wurde nicht vollständig initialisiert.','startup.moduleLoadFailed':'Modul konnte nicht geladen werden'
};
export const SHELL_EN={
 'shell.startSubtitle':'Web {version} · live scouting · modular camera synchronization','shell.matchSetup':'Set up match','shell.quickStart':'? Quick start','shell.sets':'Sets {us} : {them}','shell.serve':'Serve: {side}','shell.localReady':'local ready',
 'shell.scout':'Scout','shell.inputStep':'Input step','shell.who':'WHO','shell.what':'WHAT','shell.how':'HOW','shell.where':'WHERE','shell.target':'TARGET','shell.quickScout':'Quick scouting','shell.detailedScout':'Detailed scouting','shell.technique':'Skill (WHAT)','shell.quality':'Quality (HOW)',
 'shell.protocol':'Live protocol','shell.insertBefore':'Insert action before selected row','shell.time':'Time','shell.rotationShort':'Rot.','shell.player':'Player','shell.action':'Action','shell.value':'Value','shell.score':'Score','shell.note':'Note','shell.optional':'optional',
 'shell.ownTeam':'Own team','shell.opponent':'Opponent','shell.fullscreen':'Restore fullscreen','shell.protocolButton':'☷ Protocol','shell.switchCourt':'Switch court display','shell.net':'NET','shell.opponentAttackTarget':'Opponent attack: select the target position on our court.','shell.rotateBack':'↶ Rotation','shell.rotateForward':'Rotation ↷','shell.substitution':'↔ Substitution','shell.libero':'L Libero',
 'shell.corrections':'Corrections','shell.pointUs':'+ Point us','shell.pointOpponent':'+ Point opponent','shell.correctScore':'Correct score','shell.sideoutManual':'Manual side-out','shell.cancelAction':'Cancel action','shell.ready':'Ready.','shell.local':'☁ local','shell.cameraDisconnected':'Camera disconnected',
 'shell.cameraConnected':'connected','shell.cameraStable':'Stable','shell.cameraBattery':'Camera battery','shell.recordStart':'● Start recording','shell.recordStop':'■ Stop recording','shell.syncReady':'Sync ready',
 'tour.close':'Close introduction','tour.dontShow':'do not show again',
 'startup.error':'Startup error: {message}\nPlease send a screenshot.','startup.unknownInit':'Unknown initialization error','startup.jsError':'JavaScript error','startup.promiseError':'Promise error','startup.moduleIncomplete':'The app module did not initialize completely.','startup.moduleLoadFailed':'Module could not be loaded'
};
