export const SYNC_DE={
 'sync.provider':'Anbieter','sync.serverUrl':'Server / WebDAV-URL','sync.user':'Benutzer','sync.appPassword':'App-Passwort','sync.cloudFolder':'Cloud-Ordner','sync.environment':'CloudKit Umgebung','sync.httpsDefault':'HTTPS ist Standard; fehlendes https:// wird automatisch ergänzt.','sync.autoStart':'Beim Start synchronisieren','sync.autoChange':'Live-Daten automatisch (nahezu live) synchronisieren','sync.runNow':'Jetzt synchronisieren','sync.ready':'Bereit.','sync.testing':'Teste Verbindung …','sync.testSuccess':'✓ Verbindung erfolgreich.','sync.syncing':'⏳ Synchronisiere …','sync.settingsSaved':'Synchronisationseinstellungen gespeichert.','sync.done':'✓ Synchronisation abgeschlossen.','sync.failed':'Synchronisation fehlgeschlagen: {error}','sync.liveDone':'✓ Live-Session synchron · {count} Einträge',
 'sync.note.none':'Keine Cloud-Synchronisation aktiv.','sync.note.nextcloud':'Nextcloud wird über WebDAV angebunden.','sync.note.webdav':'Generisches WebDAV. Der Zielhost muss serverseitig im Relay freigegeben sein.','sync.note.google':'Google Drive verwendet OAuth und die Google Drive API.','sync.note.icloud':'Apple iCloud ist als CloudKit-Adapter vorgesehen; benötigt Container-ID und API-Token.','sync.note.onedrive':'OneDrive verwendet Microsoft Graph/OAuth; benötigt eine App-/Client-ID.','sync.note.dropbox':'Dropbox verwendet die Dropbox API/OAuth; benötigt einen App-Key.','sync.note.box':'Box verwendet die Box API/OAuth; benötigt eine Client-ID.',
 'sync.badge.off':'☁ Cloud: aus','sync.badge.offTitle':'Keine Cloudverbindung eingerichtet.','sync.badge.pending':'ausstehend','sync.badge.offline':'offline','sync.badge.incomplete':'unvollständig','sync.badge.locked':'gesperrt','sync.badge.ready':'bereit','sync.badge.failed':'Cloud-Verbindung fehlgeschlagen.','sync.badge.success':'Cloud-Verbindung erfolgreich.','sync.badge.testing':'Cloud-Verbindung wird geprüft.'
};
export const SYNC_EN={
 'sync.provider':'Provider','sync.serverUrl':'Server / WebDAV URL','sync.user':'User','sync.appPassword':'App password','sync.cloudFolder':'Cloud folder','sync.environment':'CloudKit environment','sync.httpsDefault':'HTTPS is the default; a missing https:// prefix is added automatically.','sync.autoStart':'Synchronize on startup','sync.autoChange':'Synchronize live data automatically (near real time)','sync.runNow':'Synchronize now','sync.ready':'Ready.','sync.testing':'Testing connection …','sync.testSuccess':'✓ Connection successful.','sync.syncing':'⏳ Synchronizing …','sync.settingsSaved':'Synchronization settings saved.','sync.done':'✓ Synchronization completed.','sync.failed':'Synchronization failed: {error}','sync.liveDone':'✓ Live session synchronized · {count} entries',
 'sync.note.none':'Cloud synchronization is disabled.','sync.note.nextcloud':'Nextcloud is connected through WebDAV.','sync.note.webdav':'Generic WebDAV. The target host must be allowed by the server-side relay.','sync.note.google':'Google Drive uses OAuth and the Google Drive API.','sync.note.icloud':'Apple iCloud is planned as a CloudKit adapter and requires a container ID and API token.','sync.note.onedrive':'OneDrive uses Microsoft Graph/OAuth and requires an app/client ID.','sync.note.dropbox':'Dropbox uses the Dropbox API/OAuth and requires an app key.','sync.note.box':'Box uses the Box API/OAuth and requires a client ID.',
 'sync.badge.off':'☁ Cloud: off','sync.badge.offTitle':'No cloud connection configured.','sync.badge.pending':'pending','sync.badge.offline':'offline','sync.badge.incomplete':'incomplete','sync.badge.locked':'locked','sync.badge.ready':'ready','sync.badge.failed':'Cloud connection failed.','sync.badge.success':'Cloud connection successful.','sync.badge.testing':'Cloud connection is being checked.'
};
