export const UI_DE={
 'drawer.menu':'Menü','drawer.players':'👥 Spielerinnen','drawer.teams':'🛡️ Teams','drawer.seasons':'📅 Saisons','drawer.rosters':'📋 Kader','drawer.matchTypes':'🏷️ Spiel-/Kaderarten','drawer.camera':'📷 Kamera & Video','drawer.videoAssignments':'🎬 Videospeicher / Zuordnung','drawer.sync':'☁️ Cloud & Synchronisation','drawer.videoCut':'🎬 Videoschnitt','drawer.shortcuts':'⌨️ Tastaturkürzel','drawer.about':'ℹ️ About',
 'prep.masterRoster':'Stammdaten & Kader','prep.masterRosterDesc':'Alles, was vor einem regulären Spiel vorbereitet wird.','prep.players':'Spielerinnen','prep.teams':'Teams','prep.seasons':'Saisons','prep.rosters':'Kader','prep.cameraVideo':'Kamera & Video','prep.cameraVideoDesc':'Kamera verbinden und Video für das aktuelle Spiel vorbereiten oder zuordnen.','prep.camera':'Kamera','prep.videoAssignments':'Videospeicher / Zuordnung','prep.videoUnavailable':'Die Videozuordnung wird verfügbar, sobald ein reguläres oder spontanes Spiel aktiv ist.','prep.newbieTipTitle':'Tipp für Neueinsteiger:','prep.newbieTip':'Für einen schnellen Test sind keine Stammdaten nötig. Über Spiel kann direkt das Spontan-Scouting gestartet werden.','prep.startMatchFirst':'Bitte zuerst ein Spiel starten.',
 'players.title':'Spielerinnen','players.add':'+ Spielerin','players.showInactive':'Inaktive anzeigen','players.hideInactive':'Inaktive ausblenden','players.abbreviation':'Kürzel','players.name':'Name','players.number':'Nr.','players.position':'Position','players.status':'Status','players.active':'aktiv','players.inactive':'inaktiv','players.sortAria':'{label} sortieren',
 'teams.add':'+ Team','teams.name':'Name','teams.type':'Art','teams.logging':'Protokollierung','teams.own':'Eigenes','teams.opponent':'Gegner','teams.detail':'Detailliert (= / - / ! / / / + / #)','teams.basic':'Basis (= / - / 0 / + / #)',
 'seasons.add':'+ Saison','seasons.title':'Saison','seasons.from':'Von','seasons.to':'Bis',
 'roster.level':'Ebene','roster.seasonRoster':'Saisonkader','roster.matchRoster':'Spielkader','roster.matchType':'Spiel-/Kaderart','roster.show':'Kader anzeigen','roster.copySeason':'Saisonkader übernehmen','roster.manageTypes':'Spiel-/Kaderarten',
 'matchTypes.add':'+ Spiel-/Kaderart','matchTypes.label':'Bezeichnung','matchTypes.usage':'Nutzung','matchTypes.backRoster':'Kader','matchTypes.edit':'Spiel-/Kaderart bearbeiten','matchTypes.create':'Spiel-/Kaderart anlegen','matchTypes.enterLabel':'Bitte eine Bezeichnung eingeben.','matchTypes.exists':'Diese Spiel-/Kaderart existiert bereits.',
 'data.scouting':'Scoutingdaten','data.exportCsv':'CSV exportieren','data.importCsv':'CSV laden / fortsetzen','data.clearScouting':'Scouting leeren','data.master':'Stammdaten','data.exportMaster':'VolleyTakt-Daten exportieren','data.importMaster':'VolleyTakt-Daten importieren','data.masterDesc':'Enthält Spielerinnen, Teams, Saisons, Saison-/Spielkader und Spiel-/Kaderarten. Cloud-Zugangsdaten werden nicht exportiert.','data.migration':'Datenmigration / Sicherung','data.schema':'Datenschema: {schema}.','data.backupAvailable':'Vor der letzten Schema-Migration wurde eine unveränderte Sicherung vom {date} gespeichert. Die Zuordnung alter Event-IDs zu den neuen Kontext-IDs ist darin enthalten.','data.noBackup':'Aktuell liegt noch kein separates Migrationsbackup vor.','data.downloadBackup':'Migrationsbackup herunterladen','data.backupDesc':'Migrationsbackups werden getrennt von der Spielbibliothek gespeichert, damit sie Analyseergebnisse nicht durch ein dupliziertes Spiel verfälschen.','data.resetTitle':'Scouting dieses Spiels vollständig zurücksetzen?','data.resetBody':'Protokoll, Punkte, Sätze, Aufstellungen, Wechsel und Rallys dieses Spiels werden gelöscht.','data.resetKeep':'Teams, Kader und Spieleinstellungen bleiben erhalten.','data.resetConfirm':'Scouting zurücksetzen','data.backupDownloaded':'Migrationsbackup heruntergeladen.',
 'help.title':'Hilfe','help.contents':'Inhaltsverzeichnis','help.startTour':'Ersteinführung starten','help.resetTour':'↺ „Nicht mehr zeigen“ zurücksetzen','help.quickStart':'🚀 Schnellstart: So kannst du starten','help.backToc':'↑ Zum Inhaltsverzeichnis','help.tourResetStatus':'Einführungsstatus zurückgesetzt. Die Einführung wird beim nächsten Öffnen wieder angeboten.','help.tourDone':'Einführung wird für diese Tour-Version nicht mehr automatisch angezeigt.','help.done':'Fertig','help.next':'Weiter',
 'help.toc.quick':'0. Schnellstart: zwei Wege','help.toc.prepare':'1. Spiel vorbereiten','help.toc.scout':'2. Scouting durchführen','help.toc.rally':'3. Rally & Punkte','help.toc.sets':'4. Sätze','help.toc.sub':'5. Wechsel & Libero','help.toc.quality':'6. Bewertung','help.toc.shortcuts':'7. Tastaturkürzel','help.toc.camera':'8. Kamera','help.toc.sync':'9. Synchronisation','help.toc.data':'10. Datenverwaltung','help.toc.analysis':'11. Analyse','help.toc.settings':'12. Einstellungen','help.toc.about':'13. About & Lizenzen',
 'settings.savedLanguage':'Anzeigesprache gespeichert.','settings.statusConfiguredUntested':'eingerichtet · noch nicht getestet','settings.statusNotConfigured':'nicht eingerichtet',
 'videoCut.reachable':'✓ Erreichbar · Worker {worker} · API v{api}',
 'tour.1.title':'1. Sofort starten: Spontan scouten','tour.1.text':'Neu bei VolleyTakt? Du kannst ohne Spielerinnen, Teams, Saison oder Kader sofort starten. Aktiviere „Spontan scouten“, lege bei Bedarf Trikotnummern/Kürzel per Long-Touch fest und beginne direkt mit der Erfassung.','tour.2.title':'2. Beim Spontan-Scouting: Aufschlagrecht setzen','tour.2.text':'Für eine vollständige Rallylogik oben „Aufschlag: Wir“ oder „Gegner“ wählen. Danach kannst du direkt WER/WAS/WIE/WO erfassen. Stammdaten kannst du später anlegen.','tour.3.title':'3. Alternativ: reguläres Spiel vorbereiten','tour.3.text':'Für vollständige Spielerinnen-, Rotations-, Video- und Langzeitanalysen öffnest du Vorbereitung für Spielerinnen, Teams, Saison, Kader sowie Kamera & Video und legst anschließend unter Spiel ein reguläres Spiel an.','tour.4.title':'4. Reguläres Spiel und Satz vorbereiten','tour.4.text':'Menü → Spiel → Neues Spiel. Danach für jeden Satz die Startaufstellung P1–P6 und den Start-Libero festlegen; bei Gegner-Scouting zusätzlich die gegnerische Aufstellung.','tour.5.title':'5. Video optional vorbereiten','tour.5.text':'Für spätere Videoanalyse die lokale Zeit starten oder eine unterstützte Kamera verbinden. Ohne Video kannst du diesen Schritt überspringen.','tour.6.title':'6. Aktion scouten','tour.6.text':'WER, WAS und WIE können in beliebiger Reihenfolge gewählt werden. Danach folgen WO und – wenn benötigt – WOHIN. WER bestimmt die Spielerin, WO den tatsächlichen Aktionsort.','tour.7.title':'7. Rally abschließen','tour.7.text':'„+ Punkt Wir“ oder „+ Punkt Gegner“ beendet die Rally. Ein = beendet automatisch zugunsten der Gegenseite; # beendet bei Aufschlag, Angriff und Block automatisch zugunsten der ausführenden Seite.','about.title':'About','about.localCloud':'Lokale Datenspeicherung mit optionaler Cloud-Synchronisation','about.copyright':'Copyright','about.licenseUse':'© 2026 Ingo Zech. Nutzung gemäß PolyForm Perimeter License 1.0.1.','about.licenses':'Lizenzen / verwendete Medien','about.media':'Technik-Piktogramme: eigene, für VolleyTakt erstellte PNG-Piktogramme als separate App-Dateien; unabhängig austauschbar. Kameraadapter: DJI-Protokollimplementierung gegen die öffentliche DJI R SDK Referenz validiert; GoPro HERO über die offizielle Open-GoPro-BLE-API.',
 'common.status':'Status','common.name':'Name','common.type':'Art','common.apply':'Übernehmen','common.edit':'Bearbeiten','common.create':'Anlegen'
};
export const UI_EN={
 'drawer.menu':'Menu','drawer.players':'👥 Players','drawer.teams':'🛡️ Teams','drawer.seasons':'📅 Seasons','drawer.rosters':'📋 Rosters','drawer.matchTypes':'🏷️ Match / roster types','drawer.camera':'📷 Camera & video','drawer.videoAssignments':'🎬 Video storage / assignment','drawer.sync':'☁️ Cloud & synchronization','drawer.videoCut':'🎬 Video editing','drawer.shortcuts':'⌨️ Keyboard shortcuts','drawer.about':'ℹ️ About',
 'prep.masterRoster':'Master data & rosters','prep.masterRosterDesc':'Everything prepared before a regular match.','prep.players':'Players','prep.teams':'Teams','prep.seasons':'Seasons','prep.rosters':'Rosters','prep.cameraVideo':'Camera & video','prep.cameraVideoDesc':'Connect a camera and prepare or assign video for the current match.','prep.camera':'Camera','prep.videoAssignments':'Video storage / assignment','prep.videoUnavailable':'Video assignment becomes available as soon as a regular or quick-scout match is active.','prep.newbieTipTitle':'New to VolleyTakt:','prep.newbieTip':'For a quick test, no master data is required. Quick scouting can be started directly from Match.','prep.startMatchFirst':'Please start a match first.',
 'players.title':'Players','players.add':'+ Player','players.showInactive':'Show inactive','players.hideInactive':'Hide inactive','players.abbreviation':'Abbreviation','players.name':'Name','players.number':'No.','players.position':'Position','players.status':'Status','players.active':'active','players.inactive':'inactive','players.sortAria':'Sort by {label}',
 'teams.add':'+ Team','teams.name':'Name','teams.type':'Type','teams.logging':'Scouting profile','teams.own':'Own team','teams.opponent':'Opponent','teams.detail':'Detailed (= / - / ! / / / + / #)','teams.basic':'Basic (= / - / 0 / + / #)',
 'seasons.add':'+ Season','seasons.title':'Season','seasons.from':'From','seasons.to':'To',
 'roster.level':'Level','roster.seasonRoster':'Season roster','roster.matchRoster':'Match roster','roster.matchType':'Match / roster type','roster.show':'Show roster','roster.copySeason':'Use season roster','roster.manageTypes':'Match / roster types',
 'matchTypes.add':'+ Match / roster type','matchTypes.label':'Label','matchTypes.usage':'Usage','matchTypes.backRoster':'Roster','matchTypes.edit':'Edit match / roster type','matchTypes.create':'Create match / roster type','matchTypes.enterLabel':'Please enter a label.','matchTypes.exists':'This match / roster type already exists.',
 'data.scouting':'Scouting data','data.exportCsv':'Export CSV','data.importCsv':'Load / resume CSV','data.clearScouting':'Clear scouting','data.master':'Master data','data.exportMaster':'Export VolleyTakt data','data.importMaster':'Import VolleyTakt data','data.masterDesc':'Contains players, teams, seasons, season/match rosters and match/roster types. Cloud credentials are not exported.','data.migration':'Data migration / backup','data.schema':'Data schema: {schema}.','data.backupAvailable':'Before the last schema migration, an unchanged backup from {date} was saved. It contains the mapping from legacy event IDs to the new context IDs.','data.noBackup':'No separate migration backup is currently available.','data.downloadBackup':'Download migration backup','data.backupDesc':'Migration backups are stored separately from the match library so they cannot distort analysis results by duplicating a match.','data.resetTitle':'Reset all scouting data for this match?','data.resetBody':'Protocol, points, sets, lineups, substitutions and rallies for this match will be deleted.','data.resetKeep':'Teams, rosters and match settings will be retained.','data.resetConfirm':'Reset scouting','data.backupDownloaded':'Migration backup downloaded.',
 'help.title':'Help','help.contents':'Contents','help.startTour':'Start introduction','help.resetTour':'↺ Reset “Do not show again”','help.quickStart':'🚀 Quick start: how to begin','help.backToc':'↑ Back to contents','help.tourResetStatus':'Introduction status reset. The introduction will be offered again the next time it opens.','help.tourDone':'The introduction will no longer be shown automatically for this tour version.','help.done':'Done','help.next':'Next',
 'help.toc.quick':'0. Quick start: two paths','help.toc.prepare':'1. Prepare match','help.toc.scout':'2. Perform scouting','help.toc.rally':'3. Rally & points','help.toc.sets':'4. Sets','help.toc.sub':'5. Substitution & libero','help.toc.quality':'6. Rating','help.toc.shortcuts':'7. Keyboard shortcuts','help.toc.camera':'8. Camera','help.toc.sync':'9. Synchronization','help.toc.data':'10. Data management','help.toc.analysis':'11. Analysis','help.toc.settings':'12. Settings','help.toc.about':'13. About & licenses',
 'settings.savedLanguage':'Display language saved.','settings.statusConfiguredUntested':'configured · not yet tested','settings.statusNotConfigured':'not configured',
 'videoCut.reachable':'✓ Reachable · Worker {worker} · API v{api}',
 'tour.1.title':'1. Start immediately: quick scouting','tour.1.text':'New to VolleyTakt? You can start without players, teams, a season or a roster. Enable “Quick scouting”, optionally add jersey numbers/abbreviations by long-press, and begin recording actions.','tour.2.title':'2. Quick scouting: set serving team','tour.2.text':'For complete rally logic, select “Serve: Us” or “Opponent”. You can then record WHO/WHAT/HOW/WHERE directly and add master data later.','tour.3.title':'3. Alternative: prepare a regular match','tour.3.text':'For complete player, rotation, video and long-term analysis, open Setup for players, teams, season, roster and camera/video, then create a regular match under Match.','tour.4.title':'4. Prepare regular match and set','tour.4.text':'Menu → Match → New match. For every set, define the P1–P6 starting lineup and starting libero; with opponent scouting enabled, also enter the opponent lineup.','tour.5.title':'5. Optional video preparation','tour.5.text':'For later video analysis, start local time or connect a supported camera. Skip this step if no video is needed.','tour.6.title':'6. Scout an action','tour.6.text':'WHO, WHAT and HOW can be selected in any order. WHERE and, when required, TARGET follow. WHO identifies the player; WHERE identifies the actual action location.','tour.7.title':'7. Finish the rally','tour.7.text':'“+ Point us” or “+ Point opponent” ends the rally. = automatically awards the point to the other side; # automatically ends serve, attack and block in favor of the acting side.','about.title':'About','about.localCloud':'Local data storage with optional cloud synchronization','about.copyright':'Copyright','about.licenseUse':'© 2026 Ingo Zech. Use according to the PolyForm Perimeter License 1.0.1.','about.licenses':'Licenses / media used','about.media':'Skill pictograms: original PNG pictograms created for VolleyTakt as separate app files and independently replaceable. Camera adapters: DJI protocol implementation validated against the public DJI R SDK reference; GoPro HERO via the official Open GoPro BLE API.',
 'common.status':'Status','common.name':'Name','common.type':'Type','common.apply':'Apply','common.edit':'Edit','common.create':'Create'
};
