export const VOLLEYBALL_DE={
 'volleyball.attack':'Angriff','volleyball.reception':'Annahme','volleyball.serve':'Aufschlag','volleyball.block':'Block','volleyball.dig':'Abwehr','volleyball.set':'Zuspiel',
 'quality.serve.eq':'Fehler – Punkt Gegner','quality.serve.minus':'negativ – Gegner kann frei angreifen','quality.serve.bang':'okay – kein erster Tempoangriff möglich','quality.serve.slash':'positiv – Gegner kann nicht angreifen','quality.serve.plus':'positiv – Gegner kann eingeschränkt angreifen','quality.serve.hash':'Ass',
 'quality.reception.eq':'Annahmefehler','quality.reception.slash':'schlecht – kein Angriff möglich','quality.reception.minus':'negativ – Angriff nur eingeschränkt möglich','quality.reception.bang':'okay – kein erster Tempoangriff möglich','quality.reception.plus':'positiv – Angriff möglich','quality.reception.hash':'perfekte Annahme',
 'quality.attack.eq':'Angriffsfehler','quality.attack.slash':'geblockt','quality.attack.minus':'schwach – leicht abwehrbar','quality.attack.bang':'geblockt – eigener Wiederangriff möglich','quality.attack.plus':'positiv – guter Angriff','quality.attack.hash':'direkter Angriffspunkt',
 'quality.block.eq':'Blockfehler','quality.block.slash':'Übergriff / Invasion','quality.block.minus':'schwach – Gegner kann weiterspielen','quality.block.bang':'schwach – Gegner kann weiterspielen','quality.block.plus':'positiv – Blockberührung','quality.block.hash':'direkter Blockpunkt',
 'quality.dig.eq':'Abwehrfehler','quality.dig.minus':'kein strukturierter Angriff möglich','quality.dig.slash':'Ball direkt zurück über das Netz','quality.dig.bang':'okay – kein erster Tempoangriff möglich','quality.dig.plus':'gute Abwehr','quality.dig.hash':'perfekte Abwehr',
 'quality.meaningFor':'Bedeutung für {skill}','quality.selectSkill':'Bedeutung wird nach Auswahl der Technik konkretisiert',
 'quality.basic.error':'Fehler','quality.basic.negative':'negativ','quality.basic.neutral':'neutral','quality.basic.positive':'positiv','quality.basic.perfect':'perfekt',
 'quality.set.eq':'Zuspiel-Fehler','quality.set.slash':'schlecht','quality.set.minus':'okay – nur hoher Pass möglich','quality.set.bang':'okay – kein erster Tempoangriff möglich','quality.set.plus':'gutes Zuspiel','quality.set.hash':'perfektes Zuspiel'
};
export const VOLLEYBALL_EN={
 'volleyball.attack':'Attack','volleyball.reception':'Reception','volleyball.serve':'Serve','volleyball.block':'Block','volleyball.dig':'Dig','volleyball.set':'Set',
 'quality.serve.eq':'Error – point opponent','quality.serve.minus':'negative – opponent can run a full attack','quality.serve.bang':'okay – no first-tempo attack available','quality.serve.slash':'positive – opponent cannot attack','quality.serve.plus':'positive – opponent attack options are limited','quality.serve.hash':'Ace',
 'quality.reception.eq':'Reception error','quality.reception.slash':'poor – no attack available','quality.reception.minus':'negative – attack options are limited','quality.reception.bang':'okay – no first-tempo attack available','quality.reception.plus':'positive – attack available','quality.reception.hash':'perfect reception',
 'quality.attack.eq':'Attack error','quality.attack.slash':'blocked','quality.attack.minus':'weak – easy to defend','quality.attack.bang':'blocked – own re-attack remains possible','quality.attack.plus':'positive – good attack','quality.attack.hash':'direct attack point',
 'quality.block.eq':'Block error','quality.block.slash':'net penetration / invasion','quality.block.minus':'weak – opponent can continue play','quality.block.bang':'weak – opponent can continue play','quality.block.plus':'positive – block touch','quality.block.hash':'direct block point',
 'quality.dig.eq':'Dig error','quality.dig.minus':'no structured attack possible','quality.dig.slash':'ball returned directly over the net','quality.dig.bang':'okay – no first-tempo attack available','quality.dig.plus':'good dig','quality.dig.hash':'perfect dig',
 'quality.meaningFor':'Meaning for {skill}','quality.selectSkill':'Meaning is shown after selecting a skill',
 'quality.basic.error':'Error','quality.basic.negative':'negative','quality.basic.neutral':'neutral','quality.basic.positive':'positive','quality.basic.perfect':'perfect',
 'quality.set.eq':'Setting error','quality.set.slash':'poor','quality.set.minus':'okay – only a high set is possible','quality.set.bang':'okay – no first-tempo attack available','quality.set.plus':'good set','quality.set.hash':'perfect set'
};
