import assert from 'node:assert/strict';
import {buildVideoCutManifest,buildSelectionContext,proposeVideoFilename,safeVideoFilename,validateVideoCutManifest} from '../js/video/cut-manifest.js';
import {normalizeWorkerBaseUrl} from '../js/video/worker-client.js';
const assignment={id:'vid1',storageType:'youtube',reference:'https://youtu.be/abcdefghijk',playbackSource:{type:'youtube',reference:'https://youtu.be/abcdefghijk'},processingSource:{type:'local',reference:'spiel.mp4'}};
const clip={matchId:'match-1',eventId:'evt-1',player:'Joke',action:'Zuspiel',quality:'+',position:4,rawVideoStart:10.5,rawVideoEnd:15.5,videoAssignment:assignment,sourceEvent:{}};
const selection={clips:[clip]};
const context=buildSelectionContext({clips:selection.clips,description:'Alle guten Zuspiele von Joke auf Position 4'});
const manifest=buildVideoCutManifest(selection,{selectionContext:context,preRollSeconds:3,postRollSeconds:2,filename:'Joke/Zuspiele auf P4?.mp4',profile:'1080p-h264'});
assert.equal(manifest.schemaVersion,'1.1');
assert.equal(manifest.clips[0].start,10.5);assert.equal(manifest.padding.preRollSeconds,3);
assert.equal(manifest.sources[0].type,'local');assert.equal(manifest.sources[0].path,'spiel.mp4');
assert.equal(validateVideoCutManifest(manifest),'');
assert(!manifest.output.filename.includes('/'));assert(proposeVideoFilename(context).endsWith('.mp4'));assert.equal(safeVideoFilename('../a?.mp4'),'a.mp4');
assert.equal(normalizeWorkerBaseUrl('volleyvideo.local'),'https://volleyvideo.local');
console.log('0.4.2 RC2 video worker manifest/client checks passed.');
