import {analyzeServeSemantic,analyzeFirstBallDeep,analyzeK3,analyzeBlockDefense,analyzeReceptionDeep,analyzeSetDeep,analyzeAttackDeep,analyzeTargets,analyzePlayerDeep,analyzeOpponentDeep,analyzeRotationsDeep,summarizeCompareDeep,analyzeChainPatterns} from './deep.js';
import {actionName,actionSide,isAction,percent,qualityCounts,zoneLabel,playerLabel,attackEfficiency} from './domain.js';
import {rallyMap,rallyForEvent,wonOwn,firstBallSideout,rallyContext,analyzeRallies} from './rallies.js';
import {analyzeChains} from './chains.js';
import {analyzeOpponent} from './opponent.js';
export function analyzeQuality(events,{actions=[],qualityLevel={}}={}){const ownActions=events.filter(e=>isAction(e,actions)&&actionSide(e)==='own');const counts=qualityCounts(ownActions);return {total:ownActions.length,rows:Object.entries(counts).sort((a,b)=>(qualityLevel[a[0]]??9)-(qualityLevel[b[0]]??9)).map(([quality,count])=>({quality,count,share:percent(count,ownActions.length)}))};}
export function analyzeRotations(events,{actions=[],rotations=[]}={}){const {rallies}=rallyContext(events,actions);return rotations.map(rotation=>{const rr=rallies.filter(r=>r.result.rotation===rotation),won=rr.filter(wonOwn).length,lost=rr.length-won,k1=rr.filter(r=>r.result.serving_before==='them'),k2=rr.filter(r=>r.result.serving_before==='us'),receptions=rr.flatMap(r=>r.actions).filter(e=>actionSide(e)==='own'&&actionName(e)==='Annahme'),attacks=rr.flatMap(r=>r.actions).filter(e=>actionSide(e)==='own'&&actionName(e)==='Angriff');return {rotation,rallies:rr.length,points:won-lost,k1Sideout:percent(k1.filter(wonOwn).length,k1.length),firstBall:percent(k1.filter(firstBallSideout).length,k1.length),k2Break:percent(k2.filter(wonOwn).length,k2.length),receptionPositive:percent(receptions.filter(e=>['+','#'].includes(e.value)).length,receptions.length),attackKill:percent(attacks.filter(e=>e.value==='#').length,attacks.length)};});}
export function analyzePlayers(events,{actions=[],players=[]}={}){const map=rallyMap(events,actions);return players.map(player=>{const own=events.filter(e=>e.player_id===player.id&&isAction(e,actions)&&actionSide(e)==='own');if(!own.length)return null;const won=new Set(own.filter(e=>wonOwn(rallyForEvent(map,e))).map(e=>e.rally_id)).size;return {player,actions:own.length,hash:own.filter(e=>e.value==='#').length,plus:own.filter(e=>e.value==='+').length,neutral:own.filter(e=>['0','!'].includes(e.value)).length,minus:own.filter(e=>['-','/'].includes(e.value)).length,error:own.filter(e=>e.value==='=').length,rallyWon:won};}).filter(Boolean).sort((a,b)=>b.actions-a.actions);}
export function analyzePlayersOverview(events,{actions=[],players=[]}={}){const rm=rallyMap(events,actions);return players.map(player=>{const own=events.filter(e=>e.player_id===player.id&&isAction(e,actions)&&actionSide(e)==='own');if(!own.length)return null;const by=Object.fromEntries(actions.map(t=>[t,own.filter(e=>actionName(e)===t).length]));const rallyIds=new Set(own.map(e=>e.rally_id).filter(Boolean));let won=0,lost=0;for(const rid of rallyIds){if(wonOwn(rm.get(rid)))won++;else if(rm.get(rid)?.result)lost++;}return {player,actions:own.length,by,won,lost};}).filter(Boolean).sort((a,b)=>b.actions-a.actions);}
export function analyzeK1K2(events,{actions=[],rotations=[]}={}){const {rallies,k1,k2}=rallyContext(events,actions),fb=k1.filter(firstBallSideout),recByQ={};for(const r of k1){const rec=r.actions.find(e=>actionSide(e)==='own'&&actionName(e)==='Annahme'),q=rec?.value||'ohne Annahme';if(!recByQ[q])recByQ[q]={n:0,w:0,fb:0};recByQ[q].n++;if(wonOwn(r))recByQ[q].w++;if(firstBallSideout(r))recByQ[q].fb++;}return {k1Sideout:percent(k1.filter(wonOwn).length,k1.length),firstBall:percent(fb.length,k1.length),k2Break:percent(k2.filter(wonOwn).length,k2.length),k1Count:k1.length,k2Count:k2.length,rotations:analyzeRotations(events,{actions,rotations}),receptionQuality:Object.entries(recByQ).map(([quality,x])=>({quality,rallies:x.n,sideout:percent(x.w,x.n),firstBall:percent(x.fb,x.n)}))};}
export function analyzeServe(events,{actions=[]}={}){const rm=rallyMap(events,actions),serves=events.filter(e=>isAction(e,actions)&&actionSide(e)==='own'&&actionName(e)==='Aufschlag'),groups=new Map();for(const e of serves){const p=playerLabel(e),tech=e.serve_technique||'nicht erfasst',z=zoneLabel(e.target_zone),k=`${p}|${tech}|${z}`;if(!groups.has(k))groups.set(k,{p,tech,z,n:0,err:0,ace:0,breaks:0,oppRec:0,oppGood:0});const g=groups.get(k),r=rallyForEvent(rm,e);g.n++;if(e.value==='=')g.err++;if(e.value==='#')g.ace++;if(wonOwn(r))g.breaks++;const rec=r?.actions.find(x=>actionSide(x)==='opponent'&&actionName(x)==='Annahme');if(rec){g.oppRec++;if(['+','#'].includes(rec.value))g.oppGood++;}}return [...groups.values()].sort((a,b)=>b.n-a.n).map(g=>({...g,errorRate:percent(g.err,g.n),aceRate:percent(g.ace,g.n),breakRate:percent(g.breaks,g.n),oppGoodRate:percent(g.oppGood,g.oppRec)}));}
export function analyzeReception(events,{actions=[]}={}){const rm=rallyMap(events,actions),rows=new Map();for(const e of events.filter(e=>isAction(e,actions)&&actionSide(e)==='own'&&actionName(e)==='Annahme')){const p=playerLabel(e);if(!rows.has(p))rows.set(p,{p,n:0,pos:0,perfect:0,err:0,so:0,fb:0});const g=rows.get(p),r=rallyForEvent(rm,e);g.n++;if(['+','#'].includes(e.value))g.pos++;if(e.value==='#')g.perfect++;if(e.value==='=')g.err++;if(r?.result?.serving_before==='them'&&wonOwn(r))g.so++;if(firstBallSideout(r))g.fb++;}return [...rows.values()].sort((a,b)=>b.n-a.n).map(g=>({...g,posRate:percent(g.pos,g.n),perfectRate:percent(g.perfect,g.n),errorRate:percent(g.err,g.n),sideoutRate:percent(g.so,g.n),firstBallRate:percent(g.fb,g.n)}));}
export function analyzeSet(events,{actions=[]}={}){const rm=rallyMap(events,actions),groups=new Map();for(const e of events.filter(e=>isAction(e,actions)&&actionSide(e)==='own'&&actionName(e)==='Zuspiel')){const r=rallyForEvent(rm,e),next=r?.actions.find(x=>(+x.rally_sequence||0)>(+e.rally_sequence||0)&&actionSide(x)==='own'&&actionName(x)==='Angriff'),from=zoneLabel(e.action_zone),to=zoneLabel(e.target_zone),tempo=e.set_tempo||'–',dist=e.set_distance||'–',k=`${from}|${to}|${tempo}|${dist}`;if(!groups.has(k))groups.set(k,{from,to,tempo,dist,n:0,kill:0,att:0});const g=groups.get(k);g.n++;if(next){g.att++;if(next.value==='#')g.kill++;}}return [...groups.values()].sort((a,b)=>b.n-a.n).map(g=>({...g,followKillRate:percent(g.kill,g.att)}));}
export function analyzeAttack(events,{actions=[]}={}){const groups=new Map();for(const e of events.filter(e=>isAction(e,actions)&&actionSide(e)==='own'&&actionName(e)==='Angriff')){const p=playerLabel(e),from=zoneLabel(e.action_zone),to=zoneLabel(e.target_zone),k=`${p}|${from}|${to}`;if(!groups.has(k))groups.set(k,{p,from,to,n:0,kill:0,err:0,blocked:0});const g=groups.get(k);g.n++;if(e.value==='#')g.kill++;if(e.value==='=')g.err++;if(e.value==='/')g.blocked++;}return [...groups.values()].sort((a,b)=>b.n-a.n).map(g=>({...g,killRate:percent(g.kill,g.n),errorRate:percent(g.err,g.n),blockedRate:percent(g.blocked,g.n),efficiency:attackEfficiency(g.kill,g.err,g.blocked,g.n)}));}
export function analyzeOverview(events,matches,{actions=[],rotations=[]}={}){const rm=rallyMap(events,actions),rallies=[...rm.values()].filter(r=>r.result),own=rallies.filter(wonOwn),k1=rallies.filter(r=>r.result.serving_before==='them'),k2=rallies.filter(r=>r.result.serving_before==='us'),fb=k1.filter(firstBallSideout),acts=events.filter(e=>isAction(e,actions)),ownTerminal=acts.filter(e=>actionSide(e)==='own'&&['Aufschlag','Angriff','Block'].includes(actionName(e))&&e.value==='#'),oppErrors=acts.filter(e=>actionSide(e)==='opponent'&&e.value==='='),bySource={Aufschlag:0,Angriff:0,Block:0};for(const e of ownTerminal)bySource[actionName(e)]++;const insights=[];const rotStats=rotations.map(rot=>{const rr=k1.filter(r=>r.result.rotation===rot);return {rot,n:rr.length,rate:rr.length?rr.filter(wonOwn).length/rr.length:null};}).filter(x=>x.n>=3).sort((a,b)=>a.rate-b.rate);if(rotStats[0])insights.push(`${rotStats[0].rot}: ${percent(rotStats[0].rate*rotStats[0].n,rotStats[0].n)} Sideout bei ${rotStats[0].n} K1-Rallys.`);const bestServe=(()=>{const m=new Map();for(const e of acts.filter(e=>actionSide(e)==='own'&&actionName(e)==='Aufschlag')){const p=playerLabel(e),r=rallyForEvent(rm,e);if(!m.has(p))m.set(p,{n:0,w:0});const x=m.get(p);x.n++;if(wonOwn(r))x.w++;}return [...m].filter(([,x])=>x.n>=4).sort((a,b)=>b[1].w/b[1].n-a[1].w/a[1].n)[0];})();if(bestServe)insights.push(`${bestServe[0]}: ${percent(bestServe[1].w,bestServe[1].n)} Breakpoint während eigener Aufschläge (${bestServe[1].n}).`);return {matches:matches.length,rallies:rallies.length,rallyRate:percent(own.length,rallies.length),k1Sideout:percent(k1.filter(wonOwn).length,k1.length),k2Break:percent(k2.filter(wonOwn).length,k2.length),firstBall:percent(fb.length,k1.length),bySource,opponentErrors:oppErrors.length,insights,rotations:analyzeRotations(events,{actions,rotations})};}
export function analyzeView(view,events,matches,context={}){
  if(view==='k1k2')return analyzeK1K2(events,context);
  if(view==='firstball')return analyzeFirstBallDeep(events,context);
  if(view==='k3')return analyzeK3(events,context);
  if(view==='rotations')return analyzeRotationsDeep(events,context);
  if(view==='serve')return analyzeServeSemantic(events,context);
  if(view==='reception')return analyzeReceptionDeep(events,context);
  if(view==='sets')return analyzeSetDeep(events,context);
  if(view==='attacks')return analyzeAttackDeep(events,context);
  if(view==='blockdef')return analyzeBlockDefense(events,context);
  if(view==='targets')return analyzeTargets(events,context);
  if(view==='chains')return analyzeChains(events,context);
  if(view==='chainPatterns')return analyzeChainPatterns(events,context);
  if(view==='opponent')return {...analyzeOpponent(events,context),contextRows:analyzeOpponentDeep(events,context)};
  if(view==='playersOverview')return analyzePlayersOverview(events,context);
  if(view==='players')return analyzePlayers(events,context);
  if(view==='playerContext')return analyzePlayerDeep(events,context);
  if(view==='techniques')return analyzeQuality(events,context);
  if(view==='rallies')return analyzeRallies(events);
  if(view==='compareDeep')return summarizeCompareDeep(events,context);
  return analyzeOverview(events,matches,context);
}
