export function optionHtml(rows,{selected='',label=x=>x.name,escapeHtml=x=>String(x??'')}={}){
  return '<option value="">Alle</option>'+(rows||[]).map(x=>`<option value="${escapeHtml(x.id)}" ${x.id===selected?'selected':''}>${escapeHtml(label(x))}</option>`).join('');
}
export function filterBlockHtml({prefix,title,compare=false,minDate='',maxDate='',seasons=[],teams=[],matchTypes=[],players=[],actions=[],rotations=[],selectedTeamId='',escapeHtml=x=>String(x??'')}){
  const opts=(rows,selected='',label=x=>x.name)=>optionHtml(rows,{selected,label,escapeHtml});
  return `<div class="analysis-filter${compare?' compare':''}"><div class="analysis-filter-shell"><div class="analysis-filter-title"><span>⌕</span><strong>${title}</strong></div><div class="analysis-filter-grid"><label>Von <input id="${prefix}From" type="date" value="${escapeHtml(minDate)}"></label><label>Bis <input id="${prefix}To" type="date" value="${escapeHtml(maxDate)}"></label><label>Saison <select id="${prefix}Season">${opts(seasons)}</select></label><label>Team <select id="${prefix}Team">${opts(teams,selectedTeamId)}</select></label><label>Gegner <select id="${prefix}Opponent">${opts(teams)}</select></label><label>Spielart <select id="${prefix}Type">${opts(matchTypes)}</select></label><label class="analysis-player-filter">Spielerin <select id="${prefix}Player" title="Spielerin auswählen">${opts(players,'',x=>`${x.abbreviation} · ${x.firstName} ${x.lastName}`)}</select></label><label class="analysis-technique-filter">Technik <select id="${prefix}Technique"><option value="">Alle</option>${actions.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Rotation <select id="${prefix}Rotation"><option value="">Alle</option>${rotations.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Satz <select id="${prefix}Set"><option value="">Alle</option>${[1,2,3,4,5].map(x=>`<option value="${x}">${x}</option>`).join('')}</select></label></div></div></div>`;
}
export function resultShellHtml({content,compareContent='',compare=false}){return `<div class="card"><h3>Auswertung A</h3>${content}</div>${compare?compareContent:''}`;}
export function analysisDrawerHtml({pinnedHtml='',version,filterAHtml,filterBHtml}){return `${pinnedHtml}<div class="card analysis-card"><div class="analysis-heading"><h3>Analyse <span class="preview-pill">${version}</span></h3><p class="small">Fachlich gruppierte Übersichten und Detailanalysen · gleiche Datenbasis für einfaches und detailliertes Scouting.</p></div><div class="analysis-top"><label>Ansicht <select id="analysisView"><optgroup label="Spiel &amp; Phasen"><option value="priorityA">Spielsteuerung im Überblick</option><option value="overview">Spiel- / Satzübersicht</option><option value="rotations">Rotations-Dashboard</option><option value="k1k2">K1, First Ball &amp; K2</option></optgroup><optgroup label="Technik &amp; Wirkung"><option value="priorityB">Technik- und Spielerinnenwirkung</option><option value="serve">Aufschlagwirkung</option><option value="reception">Annahme &amp; Sideout</option><option value="sets">Zuspielverteilung</option><option value="attacks">Angriff Quelle → Ziel</option><option value="players">Spielerinnenwirkung</option></optgroup><optgroup label="Vertiefende Analysen"><option value="chains">Kontextketten</option><option value="opponent">Gegner-Tendenzen</option><option value="playersOverview">Spielerinnen – Übersicht</option><option value="techniques">Techniken / Qualität</option><option value="rallies">Rallys</option></optgroup></select></label><label class="analysis-compare-toggle"><input id="analysisCompare" type="checkbox"> Zeitraum A mit B vergleichen</label></div>${filterAHtml}<div id="analysisB" hidden>${filterBHtml}</div><div class="toolbar mt"><button id="runAnalysis" class="primary">Auswerten</button><button id="openSavedAnalysis" hidden>Gespeichertes Ergebnis öffnen</button></div></div><div id="analysisResult"><div class="card small">Mit „Auswerten“ wird das Ergebnis in einem eigenen Analysefenster geöffnet.</div></div>`;}

const signalHtml=(title,signal,escapeHtml)=>signal?.best?`<div><strong>${escapeHtml(title)}</strong><span>Beste: ${escapeHtml(signal.best.label)} · ${escapeHtml(signal.best.value)}</span>${signal.worst&&signal.worst.label!==signal.best.label?`<small>Schwächste: ${escapeHtml(signal.worst.label)} · ${escapeHtml(signal.worst.value)}</small>`:''}</div>`:'';
const sectionNav=labels=>`<nav class="analysis-section-nav" aria-label="Analysebereiche"><button data-analysis-section="all" class="selected">Gesamtübersicht</button>${labels.map(([key,label])=>`<button data-analysis-section="${key}">${label}</button>`).join('')}</nav>`;
export function renderPriorityA(r,{escapeHtml=x=>String(x??'')}={}){const o=r.overview,p=r.phases;return `<section class="analysis-cluster"><h3>Spiel &amp; Phasen</h3>${sectionNav([['game','Spielverlauf'],['rotation','Rotation'],['sideout','K1 / Sideout'],['firstball','First-Ball-Sideout'],['breakpoint','K2 / Breakpoint']])}<section class="analysis-detail-section" data-analysis-detail="game"><h4>Spielverlauf</h4><div class="analysis-kpis"><div><strong>${o.matches}</strong><span>Spiele</span></div><div><strong>${o.rallies}</strong><span>Rallys</span></div><div><strong>${o.rallyRate}</strong><span>Rallyquote Wir</span></div></div><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Satz</th><th>Rallys</th><th>Rallyquote</th><th>K1 Sideout</th><th>First Ball</th><th>K2 Break</th></tr></thead><tbody>${r.bySet.map(x=>`<tr><td>${x.set}</td><td>${x.rallies}</td><td>${x.rallyRate}</td><td>${x.sideout}</td><td>${x.firstBall}</td><td>${x.breakpoint}</td></tr>`).join('')||'<tr><td colspan="6">Keine abgeschlossenen Rallys</td></tr>'}</tbody></table></div></section><section class="analysis-detail-section" data-analysis-detail="rotation"><h4>Rotation</h4>${renderRotations(r.rotations)}</section><section class="analysis-detail-section" data-analysis-detail="sideout"><h4>K1 / Sideout</h4><div class="analysis-kpis"><div><strong>${p.k1Sideout}</strong><span>Sideout</span></div><div><strong>${p.k1Count}</strong><span>K1-Rallys</span></div></div></section><section class="analysis-detail-section" data-analysis-detail="firstball"><h4>First-Ball-Sideout</h4><div class="analysis-kpis"><div><strong>${p.firstBall}</strong><span>First Ball</span></div><div><strong>${p.k1Count}</strong><span>K1-Rallys</span></div></div></section><section class="analysis-detail-section" data-analysis-detail="breakpoint"><h4>K2 / Breakpoint</h4><div class="analysis-kpis"><div><strong>${p.k2Break}</strong><span>Breakpoint</span></div><div><strong>${p.k2Count}</strong><span>K2-Rallys</span></div></div></section></section>`;}
export function renderPriorityB(r,{escapeHtml=x=>String(x??'')}={}){return `<section class="analysis-cluster"><h3>Technik &amp; Wirkung</h3>${sectionNav([['serve','Aufschlag'],['reception','Annahme'],['set','Zuspiel'],['attack','Angriff'],['players','Spielerinnenwirkung']])}<section class="analysis-detail-section" data-analysis-detail="serve"><h4>Aufschlagwirkung</h4>${renderServe(r.serve,{escapeHtml})}</section><section class="analysis-detail-section" data-analysis-detail="reception"><h4>Annahme &amp; Sideout</h4>${renderReception(r.reception,{escapeHtml})}</section><section class="analysis-detail-section" data-analysis-detail="set"><h4>Zuspielverteilung</h4>${renderSet(r.sets,{escapeHtml})}</section><section class="analysis-detail-section" data-analysis-detail="attack"><h4>Angriffseffizienz</h4>${renderAttack(r.attacks,{escapeHtml})}</section><section class="analysis-detail-section" data-analysis-detail="players"><h4>Spielerinnenwirkung</h4>${renderPlayers(r.players,{escapeHtml})}</section></section>`;}
export function renderQuality(result,{escapeHtml=x=>String(x??''),qualityChip=q=>escapeHtml(q)}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Qualität</th><th>Anzahl</th><th>Anteil</th></tr></thead><tbody>${result.rows.map(r=>`<tr><td>${qualityChip(r.quality)}</td><td>${r.count}</td><td>${r.share}</td></tr>`).join('')||'<tr><td colspan="3">Keine Aktionen</td></tr>'}</tbody></table></div>`;}
export function renderRotations(rows){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Rotation</th><th>Rallys</th><th>Punkte +/−</th><th>K1 Sideout</th><th>First Ball</th><th>K2 Break</th><th>Annahme +/#</th><th>Angriff #</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.rotation}</td><td>${r.rallies}</td><td>${r.points>=0?'+':''}${r.points}</td><td>${r.k1Sideout}</td><td>${r.firstBall}</td><td>${r.k2Break}</td><td>${r.receptionPositive}</td><td>${r.attackKill}</td></tr>`).join('')}</tbody></table></div>`;}
export function renderPlayers(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Spielerin</th><th>Aktionen</th><th>#</th><th>+</th><th>0/!</th><th>−</th><th>=</th><th>Rally +*</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.player.abbreviation)} · ${escapeHtml(r.player.firstName)} ${escapeHtml(r.player.lastName)}</td><td>${r.actions}</td><td>${r.hash}</td><td>${r.plus}</td><td>${r.neutral}</td><td>${r.minus}</td><td>${r.error}</td><td>${r.rallyWon}</td></tr>`).join('')||'<tr><td colspan="8">Keine Spielerinnenaktionen</td></tr>'}</tbody></table></div><p class="small">* Gewonnene Rallys mit mindestens einer Aktion dieser Spielerin; keine Kausalitätsaussage.</p>`;}
export function renderPlayersOverview(rows,{actions=[],escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact players-overview"><thead><tr><th>Spielerin</th><th>Aktionen</th>${actions.map(t=>`<th title="${escapeHtml(t)}">${escapeHtml(t)}</th>`).join('')}<th>Rallys +</th><th>Rallys −</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.player.abbreviation)} · ${escapeHtml(r.player.firstName)} ${escapeHtml(r.player.lastName)}</td><td>${r.actions}</td>${actions.map(t=>`<td>${r.by[t]||0}</td>`).join('')}<td>${r.won}</td><td>${r.lost}</td></tr>`).join('')||`<tr><td colspan="${actions.length+4}">Keine Spielerinnenaktionen</td></tr>`}</tbody></table></div><p class="small">Rallys +/− zeigen Mannschaftserfolg während der Beteiligung; Einzelaktionen bleiben getrennt auswertbar.</p>`;}
export function renderK1K2(result,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-kpis"><div><strong>${result.k1Sideout}</strong><span>K1 Sideout</span></div><div><strong>${result.firstBall}</strong><span>First-Ball-Sideout</span></div><div><strong>${result.k2Break}</strong><span>K2 Breakpoint</span></div><div><strong>${result.k1Count}</strong><span>K1 Rallys</span></div><div><strong>${result.k2Count}</strong><span>K2 Rallys</span></div></div>${renderRotations(result.rotations)}<h4>Sideout nach Annahmequalität</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Annahme</th><th>Rallys</th><th>Sideout</th><th>First Ball</th></tr></thead><tbody>${result.receptionQuality.map(r=>`<tr><td>${escapeHtml(r.quality)}</td><td>${r.rallies}</td><td>${r.sideout}</td><td>${r.firstBall}</td></tr>`).join('')||'<tr><td colspan="4">Keine K1-Daten</td></tr>'}</tbody></table></div>`;}
export function renderServe(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Spielerin</th><th>Technik</th><th>Ziel</th><th>Aufschläge</th><th>Fehler</th><th>Asse</th><th>Breakpoint</th><th>Gegner +/#</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.p)}</td><td>${escapeHtml(g.tech)}</td><td>${g.z}</td><td>${g.n}</td><td>${g.errorRate}</td><td>${g.aceRate}</td><td>${g.breakRate}</td><td>${g.oppGoodRate}</td></tr>`).join('')||'<tr><td colspan="8">Keine Aufschläge</td></tr>'}</tbody></table></div>`;}
export function renderReception(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Spielerin</th><th>Annahmen</th><th>+/#</th><th># perfekt</th><th>= Fehler</th><th>Sideout danach</th><th>First Ball</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.p)}</td><td>${g.n}</td><td>${g.posRate}</td><td>${g.perfectRate}</td><td>${g.errorRate}</td><td>${g.sideoutRate}</td><td>${g.firstBallRate}</td></tr>`).join('')||'<tr><td colspan="7">Keine Annahmen</td></tr>'}</tbody></table></div>`;}
export function renderSet(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Zuspiel von</th><th>Ziel</th><th>Tempo</th><th>Distanz</th><th>Anzahl</th><th>Folgeangriff #</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${g.from}</td><td>${g.to}</td><td>${escapeHtml(g.tempo)}</td><td>${escapeHtml(g.dist)}</td><td>${g.n}</td><td>${g.followKillRate}</td></tr>`).join('')||'<tr><td colspan="6">Keine Zuspiele</td></tr>'}</tbody></table></div>`;}
export function renderAttack(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Angreiferin</th><th>Von</th><th>Nach</th><th>Angriffe</th><th>Punktquote</th><th>Fehler</th><th>Geblockt</th><th>Effizienz</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.p)}</td><td>${g.from}</td><td>${g.to}</td><td>${g.n}</td><td>${g.killRate}</td><td>${g.errorRate}</td><td>${g.blockedRate}</td><td>${g.efficiency}</td></tr>`).join('')||'<tr><td colspan="8">Keine Angriffe</td></tr>'}</tbody></table></div>`;}
export function renderChains(rows,{escapeHtml=x=>String(x??'')}={}){return `<p class="small">Kontextketten werden nur gebildet, wenn Annahme → Zuspiel → Angriff innerhalb derselben Rally vollständig erfasst wurde.</p><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Annahme</th><th>Qual.</th><th>Zuspiel von→nach</th><th>Angriff</th><th>von→nach</th><th>Anzahl</th><th>Angriff #</th><th>Rally +</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.rec)}</td><td>${escapeHtml(g.rq)}</td><td>P${g.sz} → P${g.st}</td><td>${escapeHtml(g.att)}</td><td>P${g.az} → P${g.at}</td><td>${g.n}</td><td>${g.killRate}</td><td>${g.winRate}</td></tr>`).join('')||'<tr><td colspan="8">Noch keine vollständigen Kontextketten</td></tr>'}</tbody></table></div>`;}
export function renderOpponent(result,{escapeHtml=x=>String(x??'')}={}){const attackRows=result.attacks.map(g=>`<tr><td>${escapeHtml(g.player)}</td><td>${g.from}</td><td>${g.to}</td><td>${g.n}</td><td>${g.share}</td></tr>`).join(''),serveRows=result.serves.map(g=>`<tr><td>${g.target}</td><td>${escapeHtml(g.technique)}</td><td>${g.n}</td><td>${g.share}</td></tr>`).join(''),setRows=result.sets.map(g=>`<tr><td>${g.from}</td><td>${g.to}</td><td>${g.n}</td><td>${g.share}</td></tr>`).join('');return `<div class="analysis-split"><section><h4>Angriffstendenzen</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Spielerin</th><th>Von</th><th>Nach</th><th>Anzahl</th><th>Anteil</th></tr></thead><tbody>${attackRows||'<tr><td colspan="5">Keine Gegnerangriffe</td></tr>'}</tbody></table></div></section><section><h4>Aufschlagziele</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Ziel</th><th>Technik</th><th>Anzahl</th><th>Anteil</th></tr></thead><tbody>${serveRows||'<tr><td colspan="4">Keine Gegneraufschläge</td></tr>'}</tbody></table></div></section><section><h4>Zuspielwege</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Von</th><th>Nach</th><th>Anzahl</th><th>Anteil</th></tr></thead><tbody>${setRows||'<tr><td colspan="4">Keine Gegnerzuspiele</td></tr>'}</tbody></table></div></section></div>`;}
export function renderOverview(result,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-kpis"><div><strong>${result.matches}</strong><span>Spiele</span></div><div><strong>${result.rallies}</strong><span>Rallys</span></div><div><strong>${result.rallyRate}</strong><span>Rallyquote Wir</span></div><div><strong>${result.k1Sideout}</strong><span>K1 Sideout</span></div><div><strong>${result.k2Break}</strong><span>K2 Break</span></div><div><strong>${result.firstBall}</strong><span>First Ball</span></div></div><div class="analysis-split"><section><h4>Eigene direkte Punktaktionen</h4><div class="analysis-mini-bars">${Object.entries(result.bySource).map(([k,n])=>`<div><span>${k}</span><strong>${n}</strong></div>`).join('')}<div><span>Gegnerfehler</span><strong>${result.opponentErrors}</strong></div></div></section><section><h4>Auffälligkeiten</h4><ul class="analysis-insights">${result.insights.map(x=>`<li>${escapeHtml(x)}</li>`).join('')||'<li>Noch zu wenig Daten für belastbare Tendenzen.</li>'}</ul></section></div><h4>Rotationen</h4>${renderRotations(result.rotations)}`;}
export function renderRallies(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Rally</th><th>Satz</th><th>Rotation</th><th>Aktionen</th><th>Gewinner</th><th>Stand</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.rally)}</td><td>${escapeHtml(r.set)}</td><td>${escapeHtml(r.rotation)}</td><td>${r.actions}</td><td>${r.winner==='us'?'Wir':'Gegner'}</td><td>${escapeHtml(r.scoreUs)}:${escapeHtml(r.scoreThem)}</td></tr>`).join('')||'<tr><td colspan="6">Keine abgeschlossenen Rallys</td></tr>'}</tbody></table></div>`;}
export function renderCompareStats(stats){return `<div class="analysis-kpis"><div><strong>${stats.matches}</strong><span>Spiele</span></div><div><strong>${stats.actions}</strong><span>Aktionen</span></div><div><strong>${stats.rallies}</strong><span>Rallys</span></div><div><strong>${stats.own}:${stats.opp}</strong><span>Rallys Wir:Gegner</span></div><div><strong>${stats.win}</strong><span>Rallyquote Wir</span></div></div>`;}
export function createAnalysisController({query,getMatches,getPinnedMatchId,clearPinnedMatch,filterMatches,filterEvents,stats,actions,rotations,qualityLevel,getPlayers,getSeasons,getTeams,getMatchTypes,getSelectedTeamId,escapeHtml,qualityChip,version,matchNames,matchScoreText,analyzeView,renderView,onSaveResult}){
  const resultWindow=createResultWindow();
  const value=(prefix,id)=>query('#'+prefix+id)?.value||'';
  const filteredMatches=(prefix='a')=>filterMatches(getMatches(),{from:value(prefix,'From'),to:value(prefix,'To'),seasonId:value(prefix,'Season'),teamId:value(prefix,'Team'),oppId:value(prefix,'Opponent'),typeId:value(prefix,'Type')},getPinnedMatchId());
  const filteredEvents=(matches,prefix='a')=>filterEvents(matches,{playerId:value(prefix,'Player'),technique:value(prefix,'Technique'),rotation:value(prefix,'Rotation'),setNo:value(prefix,'Set')},actions);
  const filterBlock=(prefix,title,compare=false)=>{const dates=getMatches().map(m=>String(m?.matchDate||m?.events?.find(e=>e.createdAt)?.createdAt||'').slice(0,10)).filter(Boolean).sort();return filterBlockHtml({prefix,title,compare,minDate:dates[0]||'',maxDate:dates.at(-1)||'',seasons:getSeasons(),teams:getTeams(),matchTypes:getMatchTypes(),players:getPlayers(),actions,rotations,selectedTeamId:getSelectedTeamId(),escapeHtml});};
  const filterValues=prefix=>Object.fromEntries(['From','To','Season','Team','Opponent','Type','Player','Technique','Rotation','Set'].map(id=>[id,value(prefix,id)]));
  const titleFor=view=>query('#analysisView')?.selectedOptions?.[0]?.textContent?.trim()||view;
  const compute=(view,events,matches)=>{const context={actions,rotations,qualityLevel,players:getPlayers()};return view==='priorityA'||view==='priorityB'?analyzePriorityView(view,events,matches,context):analyzeView(view,events,matches,context)};
  const showResult=({view,content,compareContent='',compare=false,record=null})=>{const full=record?record.content:resultShellHtml({content,compareContent,compare}),title=record?.title||titleFor(view),subtitle=record?`Gespeichert am ${new Date(record.savedAt).toLocaleString('de-DE')}`:`Erstellt am ${new Date().toLocaleString('de-DE')}`;resultWindow.open({title:`Analyse · ${title}`,subtitle,content:full,accept:record?()=>{}:async()=>{const filters={a:filterValues('a'),b:compare?filterValues('b'):null,compare};const saved={id:analysisResultId(view,filters),schema:1,view,title,filters,content:full,savedAt:new Date().toISOString(),version};saveAnalysisResult(saved);await onSaveResult?.(saved);},print:{title:`VolleyTakt · ${title}`,subtitle,content:full}})};
  const renderResult=()=>{const ma=filteredMatches('a'),ea=filteredEvents(ma,'a'),compare=query('#analysisCompare')?.checked,mb=compare?filteredMatches('b'):[],eb=compare?filteredEvents(mb,'b'):[],sb=compare?stats(mb,eb,actions):null,view=query('#analysisView')?.value||'priorityA',ra=compute(view,ea,ma),content=renderView(view,ra,{actions,escapeHtml,qualityChip});let compareContent='';if(compare&&sb){const rb=compute(view,eb,mb);compareContent=`<div class="card analysis-compare-result"><h3>Vergleich B</h3>${renderCompareStats(sb)}${renderView(view,rb,{actions,escapeHtml,qualityChip})}</div>`}showResult({view,content,compareContent,compare});};
  const draw=()=>{const matches=getMatches(),pinned=getPinnedMatchId()?matches.find(m=>m.matchId===getPinnedMatchId()):null,pinnedHtml=pinned?`<div class="card analysis-pinned"><strong>Spielanalyse: ${escapeHtml(matchNames(pinned))}</strong><span>${escapeHtml(pinned.matchDate||'')} · ${escapeHtml(matchScoreText(pinned))}</span><button id="analysisAllMatches">Alle Spiele analysieren</button></div>`:'';query('#drawerBody').innerHTML=analysisDrawerHtml({pinnedHtml,version,filterAHtml:filterBlock('a','Zeitraum / Filter A'),filterBHtml:filterBlock('b','Zeitraum / Filter B',true)});if(query('#analysisAllMatches'))query('#analysisAllMatches').onclick=()=>{clearPinnedMatch();draw();};query('#analysisCompare').onchange=()=>{query('#analysisB').hidden=!query('#analysisCompare').checked;};const updateSaved=()=>{const view=query('#analysisView')?.value||'priorityA',saved=latestAnalysisResult(view),button=query('#openSavedAnalysis');button.hidden=!saved;button.onclick=saved?()=>showResult({view,content:saved.content,record:saved}):null};query('#runAnalysis').onclick=renderResult;query('#analysisView').onchange=updateSaved;updateSaved();};
  return {draw,renderResult,filteredMatches,filteredEvents};
}
export function renderView(view,result,context={}){
  if(view==='priorityA')return renderPriorityA(result,context);
  if(view==='priorityB')return renderPriorityB(result,context);
  if(view==='k1k2')return renderK1K2(result,context);
  if(view==='rotations')return renderRotations(result);
  if(view==='serve')return renderServe(result,context);
  if(view==='reception')return renderReception(result,context);
  if(view==='sets')return renderSet(result,context);
  if(view==='attacks')return renderAttack(result,context);
  if(view==='chains')return renderChains(result,context);
  if(view==='opponent')return renderOpponent(result,context);
  if(view==='playersOverview')return renderPlayersOverview(result,context);
  if(view==='players')return renderPlayers(result,context);
  if(view==='techniques')return renderQuality(result,context);
  if(view==='rallies')return renderRallies(result,context);
  return renderOverview(result,context);
}
import {analyzePriorityView} from './priorities.js';
import {analysisResultId,latestAnalysisResult,saveAnalysisResult} from './cache.js';
import {createResultWindow} from './result-window.js';
