import {t} from '../i18n.js';
import {insightsFor,confidenceText} from './insights.js';
import {advancedInsightsFor} from './insights-advanced.js';
export function optionHtml(rows,{selected='',label=x=>x.name,escapeHtml=x=>String(x??'')}={}){
  return `<option value="">${t('analysis.filter.all')}</option>`+(rows||[]).map(x=>`<option value="${escapeHtml(x.id)}" ${x.id===selected?'selected':''}>${escapeHtml(label(x))}</option>`).join('');
}
export function filterBlockHtml({prefix,title,compare=false,minDate='',maxDate='',seasons=[],teams=[],matchTypes=[],players=[],actions=[],rotations=[],selectedTeamId='',escapeHtml=x=>String(x??'')}){
  const opts=(rows,selected='',label=x=>x.name)=>optionHtml(rows,{selected,label,escapeHtml});
  const all=t('analysis.filter.all');
  return `<div class="analysis-filter${compare?' compare':''}"><div class="analysis-filter-shell"><div class="analysis-filter-title"><span>⌕</span><strong>${title}</strong></div><div class="analysis-filter-grid"><label>${t('analysis.filter.from')} <input id="${prefix}From" type="date" value="${escapeHtml(minDate)}"></label><label>${t('analysis.filter.to')} <input id="${prefix}To" type="date" value="${escapeHtml(maxDate)}"></label><label>${t('analysis.filter.season')} <select id="${prefix}Season">${opts(seasons)}</select></label><label>${t('analysis.filter.team')} <select id="${prefix}Team">${opts(teams,selectedTeamId)}</select></label><label>${t('analysis.filter.opponent')} <select id="${prefix}Opponent">${opts(teams)}</select></label><label>${t('analysis.filter.matchType')} <select id="${prefix}Type">${opts(matchTypes)}</select></label><label class="analysis-player-filter">${t('analysis.filter.player')} <select id="${prefix}Player" title="${t('analysis.playerSelect')}">${opts(players,'',x=>`${x.abbreviation} · ${x.firstName} ${x.lastName}`)}</select></label><label class="analysis-technique-filter">${t('analysis.filter.technique')} <select id="${prefix}Technique"><option value="">${all}</option>${actions.map(x=>`<option>${x}</option>`).join('')}</select></label><label>${t('analysis.filter.position')} <select id="${prefix}Position"><option value="">${all}</option>${[1,2,3,4,5,6].map(x=>`<option value="${x}">P${x}</option>`).join('')}</select></label><label>${t('analysis.filter.rotation')} <select id="${prefix}Rotation"><option value="">${all}</option>${rotations.map(x=>`<option>${x}</option>`).join('')}</select></label><label>${t('analysis.filter.set')} <select id="${prefix}Set"><option value="">${all}</option>${[1,2,3,4,5].map(x=>`<option value="${x}">${x}</option>`).join('')}</select></label></div></div></div>`;
}

const ANALYSIS_VIEW_KEYS={
 priorityA:'analysis.view.priorityA',overview:'analysis.view.overview',rotations:'analysis.view.rotations',k1k2:'analysis.view.k1k2',firstball:'analysis.view.firstball',k3:'analysis.view.k3',
 priorityB:'analysis.view.priorityB',serve:'analysis.view.serve',reception:'analysis.view.reception',sets:'analysis.view.sets',attacks:'analysis.view.attacks',blockdef:'analysis.view.blockdef',targets:'analysis.view.targets',players:'analysis.view.players',playerContext:'analysis.view.playerContext',
 chains:'analysis.view.chains',chainPatterns:'analysis.view.chainPatterns',opponent:'analysis.view.opponent',playersOverview:'analysis.view.playersOverview',techniques:'analysis.view.techniques',rallies:'analysis.view.rallies',actions:'analysis.view.actions'
};
export const analysisViewLabel=view=>ANALYSIS_VIEW_KEYS[view]?t(ANALYSIS_VIEW_KEYS[view]):String(view||'');

const ANALYSIS_VIEW_HELP={
 priorityA:'analysis.help.priorityA',overview:'analysis.help.overview',rotations:'analysis.help.rotations',k1k2:'analysis.help.k1k2',
 priorityB:'analysis.help.priorityB',actions:'analysis.help.players',serve:'analysis.help.serve',reception:'analysis.help.reception',sets:'analysis.help.sets',attacks:'analysis.help.attacks',players:'analysis.help.players',
 chains:'analysis.help.chains',chainPatterns:'analysis.help.chains',opponent:'analysis.help.opponent',playersOverview:'analysis.help.playersOverview',playerContext:'analysis.help.players',techniques:'analysis.help.techniques',rallies:'analysis.help.rallies',firstball:'analysis.help.k1k2',k3:'analysis.help.k1k2',blockdef:'analysis.help.techniques',targets:'analysis.help.attacks'
};
const analysisTip=view=>t(ANALYSIS_VIEW_HELP[view]||'analysis.help.overview');
const analysisOption=(value,label)=>`<option value="${value}" title="${analysisTip(value)}">${label}</option>`;
const metricTip=key=>t(`analysis.metric.${key}`);
const tipAttr=key=>` title="${metricTip(key)}"`;
const pctNumber=value=>{const n=Number.parseFloat(String(value??'').replace(',','.'));return Number.isFinite(n)?n:0};
const weightedPercent=(rows,valueKey,countKey='n')=>{let n=0,total=0;for(const row of rows||[]){const count=Number(row?.[countKey]||0),value=pctNumber(row?.[valueKey]);n+=count;total+=value*count;}return n?`${(total/n).toFixed(1).replace('.',',')} %`:'–'};
const sum=(rows,key)=> (rows||[]).reduce((acc,row)=>acc+Number(row?.[key]||0),0);
const pct=value=>Math.max(0,Math.min(100,pctNumber(value)));
const donut=(value,label='')=>`<div class="analysis-mini-donut" style="--p:${pct(value)}"><span>${value||'–'}</span>${label?`<small>${label}</small>`:''}</div>`;
const bars=(rows,valueKey,labelKey,{limit=6}={})=>{const data=(rows||[]).slice(0,limit),max=Math.max(1,...data.map(r=>Number(r?.[valueKey]||0)));return `<div class="analysis-mini-bars-chart">${data.map(r=>`<div><span>${r?.[labelKey]??''}</span><i><b style="width:${Math.max(4,Number(r?.[valueKey]||0)/max*100)}%"></b></i><strong>${r?.[valueKey]??0}</strong></div>`).join('')||`<em>${t('analysis.noData')}</em>`}</div>`};
const rotationBars=rows=>bars((rows||[]).filter(r=>Number(r.rallies)>0).map(r=>({label:r.rotation,value:pctNumber(r.k1Sideout)})),'value','label');
const card=(view,icon,title,help,metrics,viz='',detail=t('analysis.details'))=>`<article class="analysis-dashboard-card" data-analysis-card="${view}"><header><span class="analysis-dashboard-icon">${icon}</span><h4>${title}</h4><button type="button" class="analysis-card-help" title="${help}" aria-label="${title}: ${t('analysis.explainInterpretation')}">ⓘ</button></header><div class="analysis-card-popover" hidden role="note">${help}</div><div class="analysis-card-body"><div class="analysis-card-metrics">${metrics}</div>${viz?`<div class="analysis-card-viz">${viz}</div>`:''}</div><button type="button" class="analysis-card-detail" data-analysis-detail-view="${view}">${detail} →</button></article>`;

const DASHBOARD_VIEW_CARDS={
 priorityA:['overview','k1k2','rotations','serve','reception','attacks','players','opponent','chains','rallies'],
 overview:['overview','rotations','k1k2','rallies','serve','reception','attacks'],
 rotations:['rotations','k1k2','reception','sets','attacks','players','chains'],
 firstball:['firstball','k1k2','reception','sets','attacks','rotations','players'],
 k3:['k3','blockdef','rotations','attacks','sets','chains','players'],
 k1k2:['k1k2','rotations','reception','sets','attacks','players'],
 priorityB:['serve','reception','sets','attacks','players','techniques','chains'],
 serve:['serve','k1k2','rotations','opponent','chains','rallies'],
 blockdef:['blockdef','k3','rotations','attacks','sets','chains','players'],
 targets:['targets','serve','attacks','opponent','chains'],
 reception:['reception','k1k2','rotations','sets','attacks','players'],
 sets:['sets','reception','attacks','players','chains','rotations'],
 attacks:['attacks','sets','reception','players','chains','rotations'],
 players:['players','playersOverview','techniques','rotations','reception','attacks','serve'],
 playerContext:['players','playersOverview','rotations','reception','attacks','serve','chains'],
 chains:['chains','reception','sets','attacks','rallies','players'],
 chainPatterns:['chains','reception','sets','attacks','rallies','players'],
 opponent:['opponent','serve','reception','attacks','chains','rallies'],
 playersOverview:['playersOverview','players','techniques','rotations','serve','reception','attacks'],
 techniques:['techniques','serve','reception','sets','attacks','players'],
 rallies:['rallies','overview','rotations','k1k2','chains']
};
const dashboardAllows=(activeView,cardView)=>{
  const allowed=DASHBOARD_VIEW_CARDS[activeView]||DASHBOARD_VIEW_CARDS.priorityA;
  return allowed.includes(cardView);
};
const detailBars=(rows,valueKey,labelKey,{limit=8,suffix=''}={})=>{
 const data=(rows||[]).slice(0,limit),max=Math.max(1,...data.map(r=>Math.abs(Number(r?.[valueKey]||0))));
 return `<div class="analysis-detail-bars">${data.map(r=>`<div><span>${r?.[labelKey]??'–'}</span><i><b style="width:${Math.max(2,Math.abs(Number(r?.[valueKey]||0))/max*100)}%"></b></i><strong>${r?.[valueKey]??0}${suffix}</strong></div>`).join('')||`<em>${t('analysis.noData')}</em>`}</div>`;
};
const insightsHtml=(view,result,context={})=>{
 const rows=[...insightsFor(view,result),...advancedInsightsFor(view,result,context)];
 if(!rows.length)return '';
 return `<section class="analysis-insights"><header><h4>${t('analysis.interpretation')}</h4><button type="button" class="analysis-insight-info" aria-label="${t('analysis.explainInterpretation')}" title="${t('analysis.autoHints')}">ⓘ</button></header><div class="analysis-insight-explain" hidden>${t('analysis.hintsExplain')}</div>${rows.map(x=>`<article class="analysis-insight ${x.kind||'neutral'}"><strong>${x.finding}</strong><p>${x.context}</p><p><b>${t('analysis.analyzeFurther')}</b> ${x.next}</p><small>${confidenceText(x.confidence,x.sample)}</small></article>`).join('')}<div class="analysis-confidence-legend">${t('analysis.dataBasisLegend')}</div></section>`;
};
const detailVizHtml=(view,result)=>{
 if(view==='rotations')return `<section class="analysis-detail-viz"><h4>K1 / K2 / K3 · ${t('analysis.byRotation')}</h4><div class="analysis-triple-bars">${(result||[]).filter(r=>Number(r.rallies)>0).map(r=>`<div class="analysis-triple-row"><strong>${r.rotation}</strong><span>K1</span><i><b style="width:${pct(r.k1Sideout)}%"></b></i><em>${r.k1Sideout}</em><span>K2</span><i><b style="width:${pct(r.k2Break)}%"></b></i><em>${r.k2Break}</em><span>K3</span><i><b style="width:${pct(r.k3WinRate)}%"></b></i><em>${r.k3WinRate||'–'}</em></div>`).join('')||'<em>Keine Rotationsdaten</em>'}</div></section>`;
 if(view==='firstball')return `<section class="analysis-detail-viz"><h4>First-Ball nach Rotation</h4>${detailBars((result?.byRotation||[]).filter(r=>r.rallies).map(r=>({label:r.rotation,value:pctNumber(r.firstBall)})),'value','label',{suffix:' %'})}</section>`;
 if(view==='k3')return `<section class="analysis-detail-viz"><h4>K3 / Transition nach Rotation</h4>${detailBars((result?.byRotation||[]).filter(r=>r.n).map(r=>({label:r.rotation,value:pctNumber(r.winRate)})),'value','label',{suffix:' %'})}</section>`;
 if(view==='k1k2')return `<section class="analysis-detail-viz"><h4>Phasenvergleich</h4><div class="analysis-big-donuts">${donut(result.k1Sideout,'K1 Sideout')}${donut(result.firstBall,'First Ball')}${donut(result.k2Break,'K2 Break')}</div>${detailBars((result.rotations||[]).filter(r=>Number(r.rallies)>0).map(r=>({label:r.rotation,value:pctNumber(r.k1Sideout)})),'value','label',{suffix:' %'})}</section>`;
 if(view==='serve')return `<section class="analysis-detail-viz"><h4>${t('analysis.servePatterns')}</h4>${detailBars(result,'n','tech',{limit:10})}</section>`;
 if(view==='reception')return `<section class="analysis-detail-viz"><h4>${t('analysis.receptionByPlayer')}</h4>${detailBars((result||[]).map(r=>({label:r.p,value:pctNumber(r.posRate)})),'value','label',{limit:10,suffix:' %'})}</section>`;
 if(view==='sets')return `<section class="analysis-detail-viz"><h4>${t('analysis.setTargetDistribution')}</h4>${detailBars(result,'n','to',{limit:10})}</section>`;
 if(view==='attacks')return `<section class="analysis-detail-viz"><h4>${t('analysis.attackPatterns')}</h4>${detailBars((result||[]).map(r=>({label:`${r.p} ${r.from}→${r.to}`,value:pctNumber(r.efficiency)})),'value','label',{limit:10,suffix:' %'})}</section>`;
 if(view==='blockdef')return `<section class="analysis-detail-viz"><h4>${t('analysis.blockDefenseImpact')}</h4>${detailBars((result||[]).map(r=>({label:`${r.technique} ${r.p}`,value:pctNumber(r.transitionWinRate)})),'value','label',{limit:10,suffix:' %'})}</section>`;
 if(view==='targets')return `<section class="analysis-detail-viz"><h4>${t('analysis.targetFrequency')}</h4>${detailBars((result||[]).map(r=>({label:`${r.technique} ${r.from}→${r.to}`,value:r.n||0})),'value','label',{limit:12})}</section>`;
 if(view==='chainPatterns')return `<section class="analysis-detail-viz"><h4>Gewinn-/Verlustketten</h4>${detailBars((result||[]).map(r=>({label:`${r.phase} ${r.rotation} ${r.label}`,value:pctNumber(r.winRate)})),'value','label',{limit:12,suffix:' %'})}</section>`;
 if(view==='playerContext')return `<section class="analysis-detail-viz"><h4>${t('analysis.view.playerContext')}</h4>${detailBars((result||[]).map(r=>({label:r.player?.abbreviation||'–',value:r.actions||0})),'value','label',{limit:10})}</section>`;
 if(view==='players')return `<section class="analysis-detail-viz"><h4>Aktionsvolumen</h4>${detailBars((result||[]).map(r=>({label:r.player?.abbreviation||'–',value:r.actions||0})),'value','label',{limit:10})}</section>`;
 if(view==='playersOverview')return `<section class="analysis-detail-viz"><h4>${t('analysis.playerOverview')}</h4>${detailBars((result||[]).map(r=>({label:r.player?.abbreviation||'–',value:r.actions||0})),'value','label',{limit:10})}</section>`;
 if(view==='chains')return `<section class="analysis-detail-viz"><h4>${t('analysis.frequentChains')}</h4>${detailBars((result||[]).map((r,i)=>({label:`${r.rec||'–'}→${r.att||'–'}`,value:r.n||0})),'value','label',{limit:10})}</section>`;
 if(view==='opponent')return `<section class="analysis-detail-viz"><h4>${t('analysis.opponentTargetPatterns')}</h4>${detailBars([...(result?.attacks||[]).map(r=>({label:`${t('analysis.attack')} ${r.from}→${r.to}`,value:r.n||0})),...(result?.serves||[]).map(r=>({label:`${t('analysis.serve')} → ${r.target}`,value:r.n||0}))],'value','label',{limit:10})}</section>`;
 if(view==='techniques')return `<section class="analysis-detail-viz"><h4>${t('extra.qualityDistribution')}</h4>${detailBars((result?.rows||[]).map(r=>({label:r.quality,value:r.count||0})),'value','label',{limit:8})}</section>`;
 if(view==='overview')return `<section class="analysis-detail-viz"><h4>${t('analysis.matchPhases')}</h4><div class="analysis-big-donuts">${donut(result.rallyRate,t('analysis.rallyRateUs'))}${donut(result.k1Sideout,'K1')}${donut(result.firstBall,'First Ball')}${donut(result.k2Break,'K2')}</div>${detailBars(Object.entries(result.bySource||{}).map(([label,value])=>({label,value})),'value','label',{limit:6})}</section>`;
 if(view==='rallies')return `<section class="analysis-detail-viz"><h4>${t('analysis.rallyDistribution')}</h4>${detailBars((result||[]).map((r,i)=>({label:`R${i+1}`,value:r.actions||r.actionCount||0})),'value','label',{limit:12})}</section>`;
 return '';
};
export function analysisDashboardHtml({overview,k1k2,firstball,k3,rotations,serve,reception,sets,attacks,blockdef,targets,players,playersOverview,opponent,chains,quality,rallies},{activeView='priorityA',compareSummary=null,compareDeep=null}={}){
  const activeRot=(rotations||[]).filter(r=>Number(r.rallies)>0), best=activeRot.slice().sort((a,b)=>pctNumber(b.k1Sideout)-pctNumber(a.k1Sideout))[0], worst=activeRot.slice().sort((a,b)=>pctNumber(a.k1Sideout)-pctNumber(b.k1Sideout))[0];
  const totalServes=sum(serve,'n'), topServe=(serve||[])[0];
  const totalRec=sum(reception,'n'), recPos=weightedPercent(reception,'posRate');
  const totalSets=sum(sets,'n'), topSet=(sets||[])[0];
  const totalAttacks=sum(attacks,'n'), attackEff=weightedPercent(attacks,'efficiency');
  const topPlayer=(players||[])[0];
  const oppAttack=sum(opponent?.attacks,'n'), oppServe=sum(opponent?.serves,'n');
  const topChain=(chains||[])[0], qualityTop=(quality?.rows||[])[0];
  const firstBallTotal=firstball?.total||{};
  const k3Total=k3?.total||{};
  const blockDefTotal=(blockdef||[]).reduce((a,r)=>a+Number(r.n||0),0);
  const targetTotal=(targets||[]).reduce((a,r)=>a+Number(r.n||0),0);
  const attackByFrom=Object.values((attacks||[]).reduce((a,r)=>{const k=r.from||'–';a[k]??={label:k,n:0};a[k].n+=Number(r.n||0);return a},{})).sort((a,b)=>b.n-a.n);
  const serveByTech=Object.values((serve||[]).reduce((a,r)=>{const k=r.tech||'–';a[k]??={label:k,n:0};a[k].n+=Number(r.n||0);return a},{})).sort((a,b)=>b.n-a.n);
  const setByTarget=Object.values((sets||[]).reduce((a,r)=>{const k=r.to||'–';a[k]??={label:k,n:0};a[k].n+=Number(r.n||0);return a},{})).sort((a,b)=>b.n-a.n);
  const oppByZone=Object.values([...(opponent?.attacks||[]),...(opponent?.serves||[])].reduce((a,r)=>{const k=r.to||r.z||r.target||'–';a[k]??={label:k,n:0};a[k].n+=Number(r.n||0);return a},{})).sort((a,b)=>b.n-a.n);
  const rallyHist=Object.values((rallies||[]).reduce((a,r)=>{const n=Number(r.actions||r.actionCount||r.n||0),k=n>=9?'9+':String(n||0);a[k]??={label:k,n:0};a[k].n++;return a},{})).sort((a,b)=>{const av=a.label==='9+'?9:Number(a.label),bv=b.label==='9+'?9:Number(b.label);return av-bv});
  const m=(big,label,small='')=>`<div><strong>${big}</strong><span>${label}</span>${small?`<small>${small}</small>`:''}</div>`;
  return `<section class="analysis-dashboard" aria-label="Analyse-Dashboard"><div class="analysis-dashboard-head"><div><h3>${t('analysis.dashboard')}</h3><span class="analysis-dashboard-context">${t('analysis.view')}: ${analysisViewLabel(activeView)}</span><p class="small">${t('analysis.dashboardHelp')}</p></div><div class="analysis-dashboard-actions"><button type="button" data-analysis-team-report>${t('analysis.report')}</button></div></div><div class="analysis-dashboard-grid">
  ${dashboardAllows(activeView,'overview')?card('overview','▥',t('extra.matchOverview'),analysisTip('overview'),m(overview.rallyRate,t('analysis.rallyRateUs'),`${overview.rallies} ${t('analysis.rallies')}`)+m(overview.matches,t('analysis.matches')),donut(overview.rallyRate,t('analysis.rallyRateUs'))):''}
  ${dashboardAllows(activeView,'k1k2')?card('k1k2','↻','K1 / Sideout',analysisTip('k1k2'),m(k1k2.k1Sideout,'Sideout',`${k1k2.k1Count} ${t('analysis.k1Rallies')}`)+m(k1k2.firstBall,'First Ball'),donut(k1k2.k1Sideout,'K1')+rotationBars(k1k2.rotations)):''}
  ${dashboardAllows(activeView,'k1k2')?card('k1k2','⚡','K2 / Break',analysisTip('k1k2'),m(k1k2.k2Break,t('analysis.breakRate'),`${k1k2.k2Count} ${t('analysis.k2Rallies')}`),donut(k1k2.k2Break,'K2')+rotationBars((k1k2.rotations||[]).map(r=>({...r,k1Sideout:r.k2Break})))):''}
  ${dashboardAllows(activeView,'firstball')?card('firstball','◎',t('analysis.firstBallSideout'),analysisTip('firstball'),m(firstBallTotal.firstBall||'–','First Ball',`${firstBallTotal.rallies||0} ${t('analysis.k1Rallies')}`)+m(firstBallTotal.recPositive||'–',t('analysis.receptionPositive')),donut(firstBallTotal.firstBall||'0 %','First Ball')):''}
  ${dashboardAllows(activeView,'k3')?card('k3','↺','K3 / Transition',analysisTip('k3'),m(k3Total.winRate||'–',t('analysis.k3Success'),`${k3Total.n||0} Transitionen`)+m(k3Total.killRate||'–',t('analysis.transitionAttackKill')),donut(k3Total.winRate||'0 %','K3')):''}
  ${dashboardAllows(activeView,'rotations')?card('rotations','⟳',t('analysis.rotation'),analysisTip('rotations'),m(best?.rotation||'–',t('analysis.bestRotation'),best?.k1Sideout||'')+m(worst?.rotation||'–',t('analysis.weakestRotation'),worst?.k1Sideout||''),rotationBars(rotations)):''}
  ${dashboardAllows(activeView,'serve')?card('serve','▶',t('analysis.serve'),analysisTip('serve'),m(totalServes,t('analysis.serves'),topServe?`Top Break: ${topServe.breakRate}`:'')+m((serve||[]).length,t('analysis.patterns')),bars(serveByTech,'n','label',{limit:4})):''}
  ${dashboardAllows(activeView,'reception')?card('reception','◉',t('analysis.reception'),analysisTip('reception'),m(recPos,t('analysis.positiveShort'),t('analysis.receptionsCount',{count:totalRec}))+m((reception||[]).length,t('analysis.players')),donut(recPos,t('analysis.positive'))+bars((reception||[]).map(r=>({label:r.p,n:r.n})),'n','label',{limit:4})):''}
  ${dashboardAllows(activeView,'sets')?card('sets','⌁',t('analysis.setting'),analysisTip('sets'),m(totalSets,t('analysis.sets'),topSet?`${topSet.from} → ${topSet.to}`:'')+m((sets||[]).length,t('analysis.setRoutes')),bars(setByTarget,'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'attacks')?card('attacks','➤',t('analysis.attack'),analysisTip('attacks'),m(attackEff,t('analysis.efficiency'),t('analysis.attacksCount',{count:totalAttacks}))+m((attacks||[]).length,t('analysis.sourceTargetPatterns')),donut(attackEff,t('analysis.efficiency'))+bars(attackByFrom,'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'blockdef')?card('blockdef','✋',t('analysis.blockDefense'),analysisTip('blockdef'),m(blockDefTotal,t('analysis.actions'))+m((blockdef||[]).reduce((a,r)=>a+Number(r.transitionAttack||0),0),t('analysis.transitionAttacks')),bars((blockdef||[]).map(r=>({label:`${r.technique} ${r.p}`,n:r.n})),'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'targets')?card('targets','⌖','WO / WOHIN',analysisTip('targets'),m(targetTotal,'Zielaktionen')+m((targets||[]).length,t('analysis.patterns')),bars((targets||[]).map(r=>({label:`${r.technique} ${r.from}→${r.to}`,n:r.n})),'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'players')?card('players','♟',t('analysis.playerImpact'),analysisTip('players'),m((players||[]).length,t('analysis.players'),topPlayer?`Meiste Aktionen: ${topPlayer.actions}`:'')+m(topPlayer?.player?.abbreviation||'–',t('analysis.topActivity')),bars((players||[]).map(r=>({label:r.player?.abbreviation||r.p||'–',n:r.actions||r.n||0})),'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'opponent')?card('opponent','⌖',t('analysis.opponentAnalysis'),analysisTip('opponent'),m(oppAttack,t('analysis.opponentAttacksCount'))+m(oppServe,t('analysis.opponentServesCount')),bars(oppByZone,'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'chains')?card('chains','⛓',t('analysis.actionChains'),analysisTip('chains'),m((chains||[]).length,t('analysis.chainPatterns'),topChain?`${topChain.n}× ${t('analysis.mostFrequentChain')}`:''),bars((chains||[]).map((r,i)=>({label:r.label||r.chain||`K${i+1}`,n:r.n||0})),'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'techniques')?card('techniques','★',t('analysis.skillQuality'),analysisTip('techniques'),m(quality?.total||0,t('analysis.actions'),qualityTop?`${qualityTop.quality}: ${qualityTop.share}`:''),bars((quality?.rows||[]).map(r=>({label:r.quality,n:r.n||r.count||0})),'n','label',{limit:6})):''}
  ${dashboardAllows(activeView,'rallies')?card('rallies','⌁',t('analysis.rallyAnalysis'),analysisTip('rallies'),m((rallies||[]).length,t('analysis.ralliesInView'))+m((rallies||[]).filter(r=>r.winner==='us').length,t('analysis.wonTitle')),bars(rallyHist,'n','label',{limit:9})):''}
  ${dashboardAllows(activeView,'playersOverview')?card('playersOverview','♟',t('analysis.playerOverview'),analysisTip('playersOverview'),m((playersOverview||[]).length,t('analysis.players'))+m(sum(playersOverview,'actions'),t('analysis.actions')),bars((playersOverview||[]).map(r=>({label:r.player?.abbreviation||r.p||'–',n:r.actions||0})),'n','label',{limit:5})):''}
  </div>${compareSummary?`<section class="analysis-compare-summary"><h4>${t('analysis.periodCompare')}</h4><div><span>A</span><strong>${compareSummary.a.matches} ${t('analysis.matches')} · ${compareSummary.a.rallies} ${t('analysis.rallies')} · ${compareSummary.a.rallyRate}</strong></div><div><span>B</span><strong>${compareSummary.b.matches} ${t('analysis.matches')} · ${compareSummary.b.rallies} ${t('analysis.rallies')} · ${compareSummary.b.rallyRate}</strong></div>${compareDeep?`<div class="analysis-compare-deltas">${compareDeep.map(x=>`<span><b>${x.label}</b><strong class="${x.direction}">${x.deltaLabel}</strong></span>`).join('')}</div>`:''}</section>`:''}</section>`;
}

export function resultShellHtml({content,compareContent='',compare=false}){return `<div class="card"><h3>Auswertung A</h3>${content}</div>${compare?compareContent:''}`;}
export function analysisDrawerHtml({pinnedHtml='',version,filterAHtml,filterBHtml}){return `${pinnedHtml}<div class="card analysis-card"><div class="analysis-heading"><h3>${t('nav.analysis').replace(/^📊\s*/, '')} <span class="preview-pill">${version}</span></h3><p class="small">${t('analysis.intro')}</p></div><div class="analysis-top"><label>${t('analysis.view')} <select id="analysisView"><optgroup label="${t('analysis.group.phases')}">${analysisOption('priorityA',analysisViewLabel('priorityA'))}${analysisOption('overview',analysisViewLabel('overview'))}${analysisOption('rotations',analysisViewLabel('rotations'))}${analysisOption('k1k2',analysisViewLabel('k1k2'))}${analysisOption('firstball',analysisViewLabel('firstball'))}${analysisOption('k3',analysisViewLabel('k3'))}</optgroup><optgroup label="${t('analysis.group.impact')}">${analysisOption('priorityB',analysisViewLabel('priorityB'))}${analysisOption('serve',analysisViewLabel('serve'))}${analysisOption('reception',analysisViewLabel('reception'))}${analysisOption('sets',analysisViewLabel('sets'))}${analysisOption('attacks',analysisViewLabel('attacks'))}${analysisOption('blockdef',analysisViewLabel('blockdef'))}${analysisOption('targets',analysisViewLabel('targets'))}${analysisOption('players',analysisViewLabel('players'))}${analysisOption('playerContext',analysisViewLabel('playerContext'))}</optgroup><optgroup label="${t('analysis.group.deep')}">${analysisOption('chains',analysisViewLabel('chains'))}${analysisOption('chainPatterns',analysisViewLabel('chainPatterns'))}${analysisOption('opponent',analysisViewLabel('opponent'))}${analysisOption('playersOverview',analysisViewLabel('playersOverview'))}${analysisOption('techniques',analysisViewLabel('techniques'))}${analysisOption('rallies',analysisViewLabel('rallies'))}${analysisOption('actions',analysisViewLabel('actions'))}</optgroup></select></label><button type="button" id="analysisViewHelp" class="analysis-help-button" title="${analysisTip('priorityA')}" aria-label="${t('nav.analysis').replace(/^📊\s*/, '')} erklären">ⓘ</button><label class="analysis-compare-toggle"><input id="analysisCompare" type="checkbox"> ${t('analysis.compare')}</label></div><p id="analysisViewHelpText" class="analysis-view-help small" hidden>${analysisTip('priorityA')}</p>${filterAHtml}<div id="analysisB" hidden>${filterBHtml}</div><div class="toolbar mt"><button id="runAnalysis" class="primary">${t('analysis.run')}</button><button id="openSavedAnalysis" hidden>${t('analysis.openSaved')}</button></div></div><div id="analysisResult"><div class="card small">${t('analysis.emptyPrompt')}</div></div>`;}
const sectionNav=labels=>`<nav class="analysis-section-nav" aria-label="${t('nav.analysis').replace(/^📊\s*/, '')}"><button data-analysis-section="all" class="selected" title="${analysisTip('priorityA')}">${t('analysis.overall')}</button>${labels.map(([key,label,view=key])=>`<button data-analysis-section="${key}" title="${analysisTip(view)}">${label}</button>`).join('')}</nav>`;
export function renderPriorityA(r,{escapeHtml=x=>String(x??'')}={}){const o=r.overview,p=r.phases;return `<section class="analysis-cluster"><h3>${t('analysis.group.phases')}</h3>${sectionNav([['game',t('analysis.matchFlow'),'overview'],['rotation',t('analysis.rotation'),'rotations'],['sideout','K1 / Sideout','k1k2'],['firstball',t('analysis.firstBallSideout'),'k1k2'],['breakpoint','K2 / Breakpoint','k1k2']])}<section class="analysis-detail-section" data-analysis-detail="game"><h4>${t('analysis.matchFlow')}</h4><div class="analysis-kpis"><div><strong>${o.matches}</strong><span>${t('analysis.matches')}</span></div><div><strong>${o.rallies}</strong><span>${t('analysis.rallies')}</span></div><div><strong>${o.rallyRate}</strong><span title="${metricTip('rallyRate')}">${t('analysis.rallyRateUs')}</span></div></div><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Satz</th><th>Rallys</th><th>Rallyquote</th><th>K1 Sideout</th><th>First Ball</th><th>K2 Break</th></tr></thead><tbody>${r.bySet.map(x=>`<tr><td>${x.set}</td><td>${x.rallies}</td><td>${x.rallyRate}</td><td>${x.sideout}</td><td>${x.firstBall}</td><td>${x.breakpoint}</td></tr>`).join('')||`<tr><td colspan="6">${t('analysis.noCompletedRallies')}</td></tr>`}</tbody></table></div></section><section class="analysis-detail-section" data-analysis-detail="rotation"><h4>Rotation</h4>${renderRotations(r.rotations)}</section><section class="analysis-detail-section" data-analysis-detail="sideout"><h4>K1 / Sideout</h4><div class="analysis-kpis"><div><strong>${p.k1Sideout}</strong><span title="${metricTip('k1Sideout')}">Sideout</span></div><div><strong>${p.k1Count}</strong><span>${t('analysis.k1Rallies')}</span></div></div></section><section class="analysis-detail-section" data-analysis-detail="firstball"><h4>First-Ball-Sideout</h4><div class="analysis-kpis"><div><strong>${p.firstBall}</strong><span title="${metricTip('firstBall')}">First Ball</span></div><div><strong>${p.k1Count}</strong><span>${t('analysis.k1Rallies')}</span></div></div></section><section class="analysis-detail-section" data-analysis-detail="breakpoint"><h4>K2 / Breakpoint</h4><div class="analysis-kpis"><div><strong>${p.k2Break}</strong><span title="${metricTip('k2Break')}">Breakpoint</span></div><div><strong>${p.k2Count}</strong><span>${t('analysis.k2Rallies')}</span></div></div></section></section>`;}
export function renderPriorityB(r,{escapeHtml=x=>String(x??'')}={}){return `<section class="analysis-cluster"><h3>${t('analysis.group.impact')}</h3>${sectionNav([['serve',t('analysis.serve'),'serve'],['reception',t('analysis.reception'),'reception'],['set',t('analysis.setting'),'sets'],['attack',t('analysis.attack'),'attacks'],['players',t('analysis.playerImpact'),'players']])}<section class="analysis-detail-section" data-analysis-detail="serve"><h4>${t('analysis.view.serve')}</h4>${renderServe(r.serve,{escapeHtml})}</section><section class="analysis-detail-section" data-analysis-detail="reception"><h4>${t('analysis.view.reception')}</h4>${renderReception(r.reception,{escapeHtml})}</section><section class="analysis-detail-section" data-analysis-detail="set"><h4>${t('analysis.view.sets')}</h4>${renderSet(r.sets,{escapeHtml})}</section><section class="analysis-detail-section" data-analysis-detail="attack"><h4>${t('analysis.attackEfficiency')}</h4>${renderAttack(r.attacks,{escapeHtml})}</section><section class="analysis-detail-section" data-analysis-detail="players"><h4>${t('analysis.playerImpact')}</h4>${renderPlayers(r.players,{escapeHtml})}</section></section>`;}
export function renderQuality(result,{escapeHtml=x=>String(x??''),qualityChip=q=>escapeHtml(q)}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.quality')}</th><th>${t('analysis.count')}</th><th>${t('analysis.share')}</th></tr></thead><tbody>${result.rows.map(r=>`<tr><td>${qualityChip(r.quality)}</td><td>${r.count}</td><td>${r.share}</td></tr>`).join('')||'<tr><td colspan="3">Keine Aktionen</td></tr>'}</tbody></table></div>`;}
export function renderRotations(rows){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.rotation')}</th><th>${t('analysis.rallies')}</th><th>${t('analysis.rallyBalance')}</th><th>K1</th><th>First Ball</th><th>K2</th><th>K3</th><th>${t('analysis.receptionPositive')}</th><th>${t('analysis.firstAttackKill')}</th><th>${t('analysis.attackKill')}</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.rotation}</td><td>${r.rallies}</td><td>${r.points>=0?'+':''}${r.points}</td><td>${r.k1Sideout}</td><td>${r.firstBall}</td><td>${r.k2Break}</td><td>${r.k3WinRate||'–'}</td><td>${r.receptionPositive}</td><td>${r.firstAttackKill||'–'}</td><td>${r.attackKill}</td></tr>`).join('')||'<tr><td colspan="10">Keine Rotationsdaten</td></tr>'}</tbody></table></div><p class="small">Rallybilanz = gewonnene minus verlorene Rallys während dieser Rotation. K3 = Transition nach gegnerischem Angriff über Block/Abwehr.</p>`;}
export function renderPlayers(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.player')}</th><th>${t('analysis.actions')}</th><th>#</th><th>+</th><th>0/!</th><th>−</th><th>=</th><th>Rally +*</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.player.abbreviation)} · ${escapeHtml(r.player.firstName)} ${escapeHtml(r.player.lastName)}</td><td>${r.actions}</td><td>${r.hash}</td><td>${r.plus}</td><td>${r.neutral}</td><td>${r.minus}</td><td>${r.error}</td><td>${r.rallyWon}</td></tr>`).join('')||'<tr><td colspan="8">Keine Spielerinnenaktionen</td></tr>'}</tbody></table></div><p class="small">* Gewonnene Rallys mit mindestens einer Aktion dieser Spielerin; keine Kausalitätsaussage.</p>`;}
export function renderPlayersOverview(rows,{actions=[],escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact players-overview"><thead><tr><th>${t('analysis.player')}</th><th>${t('analysis.actions')}</th>${actions.map(actionName=>`<th title="${escapeHtml(actionName)}">${escapeHtml(actionName)}</th>`).join('')}<th>${t('analysis.rallyPlus')}</th><th>${t('analysis.rallyMinus')}</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.player.abbreviation)} · ${escapeHtml(r.player.firstName)} ${escapeHtml(r.player.lastName)}</td><td>${r.actions}</td>${actions.map(actionName=>`<td>${r.by[actionName]||0}</td>`).join('')}<td>${r.won}</td><td>${r.lost}</td></tr>`).join('')||`<tr><td colspan="${actions.length+4}">Keine Spielerinnenaktionen</td></tr>`}</tbody></table></div><p class="small">Rallys +/− zeigen Mannschaftserfolg während der Beteiligung; Einzelaktionen bleiben getrennt auswertbar.</p>`;}
export function renderK1K2(result,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-kpis"><div><strong>${result.k1Sideout}</strong><span title="${metricTip('k1Sideout')}">K1 Sideout</span></div><div><strong>${result.firstBall}</strong><span>First-Ball-Sideout</span></div><div><strong>${result.k2Break}</strong><span title="${metricTip('k2Break')}">K2 Breakpoint</span></div><div><strong>${result.k1Count}</strong><span>${t('analysis.k1RalliesLabel')}</span></div><div><strong>${result.k2Count}</strong><span>${t('analysis.k2RalliesLabel')}</span></div></div>${renderRotations(result.rotations)}<h4>Sideout nach Annahmequalität</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Annahme</th><th>Rallys</th><th>Sideout</th><th>First Ball</th></tr></thead><tbody>${result.receptionQuality.map(r=>`<tr><td>${escapeHtml(r.quality)}</td><td>${r.rallies}</td><td>${r.sideout}</td><td>${r.firstBall}</td></tr>`).join('')||'<tr><td colspan="4">Keine K1-Daten</td></tr>'}</tbody></table></div>`;}

export function renderFirstBallDeep(result,{escapeHtml=x=>String(x??'')}={}){
 const total=result.total||{};
 return `<div class="analysis-kpis"><div><strong>${total.rallies||0}</strong><span>${t('analysis.k1Rallies')}</span></div><div><strong>${total.sideout||'–'}</strong><span>Sideout</span></div><div><strong>${total.firstBall||'–'}</strong><span>First Ball</span></div><div><strong>${total.recPositive||'–'}</strong><span>${t('analysis.receptionPositive')}</span></div><div><strong>${total.attackKill||'–'}</strong><span>${t('analysis.firstAttackKill')}</span></div></div><h4>${t('analysis.byRotation')}</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Rotation</th><th>K1</th><th>Sideout</th><th>First Ball</th><th>Annahme +/#</th><th>Annahme #</th><th>1. Angriff #</th></tr></thead><tbody>${(result.byRotation||[]).filter(r=>r.rallies).map(r=>`<tr><td>${r.rotation}</td><td>${r.rallies}</td><td>${r.sideout}</td><td>${r.firstBall}</td><td>${r.recPositive}</td><td>${r.recPerfect}</td><td>${r.attackKill}</td></tr>`).join('')||'<tr><td colspan="7">Keine K1-Daten</td></tr>'}</tbody></table></div><h4>Nach Annahmequalität</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Qualität</th><th>Rallys</th><th>Sideout</th><th>First Ball</th><th>1. Angriff #</th></tr></thead><tbody>${(result.byReception||[]).map(r=>`<tr><td>${escapeHtml(r.quality)}</td><td>${r.rallies}</td><td>${r.sideout}</td><td>${r.firstBall}</td><td>${r.attackKill}</td></tr>`).join('')||'<tr><td colspan="5">Keine Annahmegruppen</td></tr>'}</tbody></table></div>`;
}
export function renderK3(result){
 const total=result.total||{};
 return `<div class="analysis-kpis"><div><strong>${total.n||0}</strong><span>${t('analysis.transitions')}</span></div><div><strong>${total.winRate||'–'}</strong><span>${t('analysis.k3Success')}</span></div><div><strong>${total.killRate||'–'}</strong><span>${t('analysis.transitionAttackKill')}</span></div><div><strong>${total.attackErrors||0}</strong><span>${t('analysis.errors')}</span></div></div><h4>${t('analysis.byRotation')}</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Rotation</th><th>K3</th><th>gewonnen</th><th>K3-Erfolg</th><th>Angriff #</th></tr></thead><tbody>${(result.byRotation||[]).filter(r=>r.n).map(r=>`<tr><td>${r.rotation}</td><td>${r.n}</td><td>${r.won}</td><td>${r.winRate}</td><td>${r.killRate}</td></tr>`).join('')||'<tr><td colspan="5">Noch keine vollständigen Transition-Ketten</td></tr>'}</tbody></table></div><h4>Auslöser</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Block/Abwehr</th><th>K3</th><th>K3-Erfolg</th><th>Angriff #</th></tr></thead><tbody>${(result.byTrigger||[]).filter(r=>r.n).map(r=>`<tr><td>${r.trigger}</td><td>${r.n}</td><td>${r.winRate}</td><td>${r.killRate}</td></tr>`).join('')||'<tr><td colspan="4">Keine Transitionen</td></tr>'}</tbody></table></div>`;
}
export function renderBlockDefense(rows,{escapeHtml=x=>String(x??'')}={}){
 return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.skill')}</th><th>${t('analysis.player')}</th><th>${t('analysis.actions')}</th><th>${t('analysis.directPoint')}</th><th>${t('analysis.continued')}</th><th>${t('analysis.transitionAttacks')}</th><th>${t('analysis.transitionWon')}</th></tr></thead><tbody>${(rows||[]).map(r=>`<tr><td>${r.technique}</td><td>${escapeHtml(r.p)}</td><td>${r.n}</td><td>${r.directRate}</td><td>${r.continuedRate}</td><td>${r.transitionAttack}</td><td>${r.transitionWinRate}</td></tr>`).join('')||`<tr><td colspan="7">${t('analysis.noBlockDefense')}</td></tr>`}</tbody></table></div>`;
}
export function renderTargets(rows){
 return `<div class="analysis-target-grid">${[t('analysis.serve'),t('analysis.attack')].map(tech=>{const r=(rows||[]).filter(x=>x.technique===tech);return `<section><h4>${tech} – WO → WOHIN</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.from')}</th><th>${t('analysis.to')}</th><th>${t('analysis.count')}</th><th>${t('analysis.success')}</th><th>${t('analysis.errors')}</th></tr></thead><tbody>${r.map(x=>`<tr><td>${x.from}</td><td>${x.to}</td><td>${x.n}</td><td>${x.successRate}</td><td>${x.errorRate}</td></tr>`).join('')||'<tr><td colspan="5">Keine Daten</td></tr>'}</tbody></table></div></section>`}).join('')}</div>`;
}
export function renderPlayerContext(rows,{escapeHtml=x=>String(x??'')}={}){
 return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.player')}</th><th>${t('analysis.actions')}</th><th>${t('analysis.k1Effect')}</th><th>${t('analysis.k2Effect')}</th><th>${t('analysis.k3Effect')}</th><th>${t('analysis.mostCommonSkill')}</th><th>${t('analysis.notableRotation')}</th></tr></thead><tbody>${(rows||[]).map(r=>{const rot=[...(r.rotations||[])].sort((a,b)=>b.n-a.n)[0];return `<tr><td>${escapeHtml(r.player?.abbreviation||'–')}</td><td>${r.actions}</td><td>${r.phases?.K1?.winRate||'–'}</td><td>${r.phases?.K2?.winRate||'–'}</td><td>${r.phases?.K3?.winRate||'–'}</td><td>${escapeHtml(r.techniques?.[0]?.[0]||'–')}</td><td>${rot?`${rot.rotation} (${rot.winRate})`:'–'}</td></tr>`}).join('')||'<tr><td colspan="7">Keine Spielerinnenkontexte</td></tr>'}</tbody></table></div><p class="small">${t('analysis.notCausal')}</p>`;
}
export function renderChainPatterns(rows,{escapeHtml=x=>String(x??'')}={}){
 return `<p class="small">${t('analysis.chainPatternDesc')}</p><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.phase')}</th><th>${t('analysis.rotation')}</th><th>${t('analysis.actionChains')}</th><th>${t('analysis.count')}</th><th>${t('analysis.won')}</th><th>${t('analysis.lost')}</th><th>${t('analysis.success')}</th></tr></thead><tbody>${(rows||[]).map(r=>`<tr><td>${r.phase}</td><td>${r.rotation||'–'}</td><td>${escapeHtml(r.label)}</td><td>${r.n}</td><td>${r.won}</td><td>${r.lost}</td><td>${r.winRate}</td></tr>`).join('')||`<tr><td colspan="7">${t('analysis.noChainPatterns')}</td></tr>`}</tbody></table></div>`;
}
export function renderServe(rows,{escapeHtml=x=>String(x??'')}={}){return `<p class="small">${t('analysis.serveSemantics')}</p><div class="analysis-table-wrap"><table class="data-table compact serve-semantic-table"><thead><tr><th rowspan="2">${t('analysis.player')}</th><th rowspan="2">${t('analysis.skill')}</th><th rowspan="2">${t('analysis.target')}</th><th rowspan="2">${t('analysis.serves')}</th><th colspan="3">${t('analysis.directServeResult')} = 100 %</th><th colspan="2">${t('analysis.followImpact')}</th></tr><tr><th>${t('analysis.errors')}</th><th>Ass</th><th>${t('analysis.inPlay')}</th><th>${t('analysis.breakRate')}</th><th>${t('analysis.opponentPositive')}</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.p)}</td><td>${escapeHtml(g.tech)}</td><td>${g.z}</td><td>${g.n}</td><td>${g.errorRate}</td><td>${g.aceRate}</td><td>${g.inPlayRate}</td><td>${g.breakRate}</td><td>${g.oppPositiveRate}</td></tr>`).join('')||'<tr><td colspan="9">Keine Aufschläge</td></tr>'}</tbody></table></div>`;}
export function renderReception(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.player')}</th><th>${t('analysis.rotation')}</th><th>${t('analysis.receptions')}</th><th>+/#</th><th>${t('analysis.perfect')}</th><th>${t('analysis.errorEq')}</th><th>${t('analysis.sideoutAfter')}</th><th>${t('analysis.firstBall')}</th><th>${t('analysis.followAttackKill')}</th><th>${t('analysis.commonSetTarget')}</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.p)}</td><td>${g.rotation||'–'}</td><td>${g.n}</td><td>${g.posRate}</td><td>${g.perfectRate}</td><td>${g.errorRate}</td><td>${g.sideoutRate}</td><td>${g.firstBallRate}</td><td>${g.followKillRate||'–'}</td><td>${g.setTargets?.[0]?.[0]||'–'}</td></tr>`).join('')||'<tr><td colspan="10">Keine Annahmen</td></tr>'}</tbody></table></div>`;}
export function renderSet(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.setter')}</th><th>${t('analysis.rotation')}</th><th>${t('analysis.phase')}</th><th>${t('analysis.from')}</th><th>${t('analysis.target')}</th><th>${t('analysis.tempo')}</th><th>${t('analysis.distance')}</th><th>${t('analysis.receptionBefore')}</th><th>${t('analysis.count')}</th><th>${t('analysis.followAttackKill')}</th><th>${t('analysis.rallyWon')}</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.p||'–')}</td><td>${g.rotation||'–'}</td><td>${g.phase||'–'}</td><td>${g.from}</td><td>${g.to}</td><td>${escapeHtml(g.tempo)}</td><td>${escapeHtml(g.dist)}</td><td>${escapeHtml(g.recQ||'–')}</td><td>${g.n}</td><td>${g.followKillRate}</td><td>${g.rallyWinRate||'–'}</td></tr>`).join('')||'<tr><td colspan="11">Keine Zuspiele</td></tr>'}</tbody></table></div>`;}
export function renderAttack(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.attacker')}</th><th>${t('analysis.rotation')}</th><th>${t('analysis.phase')}</th><th>${t('analysis.from')}</th><th>${t('analysis.to')}</th><th>${t('analysis.receptionBefore')}</th><th>${t('analysis.tempo')}</th><th>${t('analysis.attacks')}</th><th>${t('analysis.pointRate')}</th><th>${t('analysis.errors')}</th><th>${t('analysis.blocked')}</th><th>${t('analysis.efficiency')}</th><th>${t('analysis.rallyWon')}</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.p)}</td><td>${g.rotation||'–'}</td><td>${g.phase||'–'}</td><td>${g.from}</td><td>${g.to}</td><td>${escapeHtml(g.recQ||'–')}</td><td>${escapeHtml(g.tempo||'–')}</td><td>${g.n}</td><td>${g.killRate}</td><td>${g.errorRate}</td><td>${g.blockedRate}</td><td>${g.efficiency}</td><td>${g.rallyWinRate||'–'}</td></tr>`).join('')||'<tr><td colspan="13">Keine Angriffe</td></tr>'}</tbody></table></div>`;}
export function renderChains(rows,{escapeHtml=x=>String(x??'')}={}){return `<p class="small">${t('analysis.chainContext')}</p><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.reception')}</th><th>${t('analysis.quality')}</th><th>${t('analysis.setting')} ${t('analysis.from')}→${t('analysis.to')}</th><th>${t('analysis.attack')}</th><th>${t('analysis.from')}→${t('analysis.to')}</th><th>${t('analysis.count')}</th><th>${t('analysis.attackKill')}</th><th>${t('analysis.rallyPlus')}</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.rec)}</td><td>${escapeHtml(g.rq)}</td><td>P${g.sz} → P${g.st}</td><td>${escapeHtml(g.att)}</td><td>P${g.az} → P${g.at}</td><td>${g.n}</td><td>${g.killRate}</td><td>${g.winRate}</td></tr>`).join('')||`<tr><td colspan="8">${t('analysis.noChains')}</td></tr>`}</tbody></table></div>`;}
export function renderOpponent(result,{escapeHtml=x=>String(x??'')}={}){
 const attackRows=result.attacks.map(g=>`<tr><td>${escapeHtml(g.player)}</td><td>${g.from}</td><td>${g.to}</td><td>${g.n}</td><td>${g.share}</td></tr>`).join('');
 const serveRows=result.serves.map(g=>`<tr><td>${g.target}</td><td>${escapeHtml(g.technique)}</td><td>${g.n}</td><td>${g.share}</td></tr>`).join('');
 const setRows=result.sets.map(g=>`<tr><td>${g.from}</td><td>${g.to}</td><td>${g.n}</td><td>${g.share}</td></tr>`).join('');
 const contextRows=(result.contextRows||[]).slice(0,30).map(g=>`<tr><td>${escapeHtml(g.technique)}</td><td>${escapeHtml(g.rotation||'–')}</td><td>${g.from}</td><td>${g.to}</td><td>${g.n}</td><td>${g.oppWinRate}</td></tr>`).join('');
 return `<div class="analysis-split"><section><h4>${t('analysis.attackTendencies')}</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.player')}</th><th>${t('analysis.from')}</th><th>${t('analysis.to')}</th><th>${t('analysis.count')}</th><th>${t('analysis.share')}</th></tr></thead><tbody>${attackRows||`<tr><td colspan="5">${t('analysis.noOpponentAttacks')}</td></tr>`}</tbody></table></div></section><section><h4>${t('analysis.serveTargets')}</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.target')}</th><th>${t('analysis.skill')}</th><th>${t('analysis.count')}</th><th>${t('analysis.share')}</th></tr></thead><tbody>${serveRows||`<tr><td colspan="4">${t('analysis.noOpponentServes')}</td></tr>`}</tbody></table></div></section><section><h4>${t('analysis.setPaths')}</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.from')}</th><th>${t('analysis.to')}</th><th>${t('analysis.count')}</th><th>${t('analysis.share')}</th></tr></thead><tbody>${setRows||`<tr><td colspan="4">${t('analysis.noOpponentSets')}</td></tr>`}</tbody></table></div></section></div><h4>${t('analysis.opponentContext')}</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>${t('analysis.skill')}</th><th>${t('analysis.ownRotation')}</th><th>${t('analysis.from')}</th><th>${t('analysis.to')}</th><th>${t('analysis.count')}</th><th>${t('analysis.opponentWinsRally')}</th></tr></thead><tbody>${contextRows||`<tr><td colspan="6">${t('analysis.noOpponentContext')}</td></tr>`}</tbody></table></div>`;
}
export function renderOverview(result,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-kpis"><div><strong>${result.matches}</strong><span>${t('analysis.matches')}</span></div><div><strong>${result.rallies}</strong><span>${t('analysis.rallies')}</span></div><div><strong>${result.rallyRate}</strong><span title="${metricTip('rallyRate')}">${t('analysis.rallyRateUs')}</span></div><div><strong>${result.k1Sideout}</strong><span title="${metricTip('k1Sideout')}">K1 Sideout</span></div><div><strong>${result.k2Break}</strong><span title="${metricTip('k2Break')}">K2 Break</span></div><div><strong>${result.firstBall}</strong><span title="${metricTip('firstBall')}">First Ball</span></div></div><div class="analysis-split"><section><h4>${t('analysis.ownDirectPoints')}</h4><div class="analysis-mini-bars">${Object.entries(result.bySource).map(([k,n])=>`<div><span>${k}</span><strong>${n}</strong></div>`).join('')}<div><span>${t('analysis.opponentErrors')}</span><strong>${result.opponentErrors}</strong></div></div></section><section><h4>${t('analysis.notable')}</h4><ul class="analysis-insights">${result.insights.map(x=>`<li>${escapeHtml(x)}</li>`).join('')||`<li>${t('analysis.notEnoughTrends')}</li>`}</ul></section></div><h4>${t('analysis.rotationsTitle')}</h4>${renderRotations(result.rotations)}`;}
export function renderRallies(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Rally</th><th>${t('extra.set')}</th><th>${t('analysis.rotation')}</th><th>${t('analysis.actions')}</th><th>${t('analysis.winner')}</th><th>${t('analysis.score')}</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.rally)}</td><td>${escapeHtml(r.set)}</td><td>${escapeHtml(r.rotation)}</td><td>${r.actions}</td><td>${r.winner==='us'?t('analysis.us'):t('analysis.opponent')}</td><td>${escapeHtml(r.scoreUs)}:${escapeHtml(r.scoreThem)}</td></tr>`).join('')||`<tr><td colspan="6">${t('analysis.noCompletedRallies')}</td></tr>`}</tbody></table></div>`;}
export function renderCompareStats(stats){return `<div class="analysis-kpis"><div><strong>${stats.matches}</strong><span>${t('analysis.matches')}</span></div><div><strong>${stats.actions}</strong><span>${t('analysis.actions')}</span></div><div><strong>${stats.rallies}</strong><span>${t('analysis.rallies')}</span></div><div><strong>${stats.own}:${stats.opp}</strong><span>${t('analysis.rallyUsOpponent')}</span></div><div><strong>${stats.win}</strong><span title="${metricTip('rallyRate')}">${t('analysis.rallyRateUs')}</span></div></div>`;}
export function createAnalysisController({query,getMatches,getPinnedMatchId,clearPinnedMatch,filterMatches,filterEvents,stats,actions,rotations,qualityLevel,getPlayers,getSeasons,getTeams,getMatchTypes,getSelectedTeamId,escapeHtml,qualityChip,version,matchNames,matchScoreText,analyzeView,renderView,onSaveResult}){
  const resultWindow=createResultWindow();
  const value=(prefix,id)=>query('#'+prefix+id)?.value||'';
  const filteredMatches=(prefix='a')=>filterMatches(getMatches(),{from:value(prefix,'From'),to:value(prefix,'To'),seasonId:value(prefix,'Season'),teamId:value(prefix,'Team'),oppId:value(prefix,'Opponent'),typeId:value(prefix,'Type')},getPinnedMatchId());
  const filteredEvents=(matches,prefix='a')=>filterEvents(matches,{playerId:value(prefix,'Player'),technique:value(prefix,'Technique'),position:value(prefix,'Position'),rotation:value(prefix,t('analysis.rotation')),setNo:value(prefix,'Set')},actions);
  const filterBlock=(prefix,title,compare=false)=>{const dates=getMatches().map(m=>String(m?.matchDate||m?.events?.find(e=>e.createdAt)?.createdAt||'').slice(0,10)).filter(Boolean).sort();return filterBlockHtml({prefix,title,compare,minDate:dates[0]||'',maxDate:dates.at(-1)||'',seasons:getSeasons(),teams:getTeams(),matchTypes:getMatchTypes(),players:getPlayers(),actions,rotations,selectedTeamId:getSelectedTeamId(),escapeHtml});};
  const filterValues=prefix=>Object.fromEntries(['From','To','Season','Team','Opponent','Type','Player','Technique','Position',t('analysis.rotation'),'Set'].map(id=>[id,value(prefix,id)]));
  const titleFor=view=>query('#analysisView')?.selectedOptions?.[0]?.textContent?.trim()||view;
  const compute=(view,events,matches)=>{const context={actions,rotations,qualityLevel,players:getPlayers()};return view==='priorityA'||view==='priorityB'?analyzePriorityView(view,events,matches,context):analyzeView(view,events,matches,context)};
  const showResult=({view,content,compareContent='',compare=false,record=null,teamReport=null,trainerReport=null,playerReports=[],videoSelection=null})=>{const full=record?record.content:resultShellHtml({content,compareContent,compare}),title=record?.title||titleFor(view),subtitle=record?t('analysis.savedAt',{date:new Date(record.savedAt).toLocaleString()}):t('analysis.createdAt',{date:new Date().toLocaleString()}),report=record?.teamReport||teamReport||null,coach=record?.trainerReport||trainerReport||null;resultWindow.open({title:t('analysis.titlePrefix',{title}),subtitle,content:full,teamReport:report,trainerReport:coach,playerReports,videoSelection,accept:record?()=>{}:async()=>{const filters={a:filterValues('a'),b:compare?filterValues('b'):null,compare};const saved={id:analysisResultId(view,filters),schema:4,view,title,filters,content:full,teamReport:report,trainerReport:coach,savedAt:new Date().toISOString(),version};saveAnalysisResult(saved);await onSaveResult?.(saved);},print:{title:`VolleyTakt · ${title}`,subtitle,content:full}})};
  const renderResult=()=>{
    const selectedView=query('#analysisView')?.value||'priorityA';
    const ma=filteredMatches('a'),ea=filteredEvents(ma,'a'),compare=query('#analysisCompare')?.checked,mb=compare?filteredMatches('b'):[],eb=compare?filteredEvents(mb,'b'):[];
    const buildDash=(events,matches)=>({overview:compute('overview',events,matches),k1k2:compute('k1k2',events,matches),firstball:compute('firstball',events,matches),k3:compute('k3',events,matches),rotations:compute('rotations',events,matches),serve:compute('serve',events,matches),reception:compute('reception',events,matches),sets:compute('sets',events,matches),attacks:compute('attacks',events,matches),blockdef:compute('blockdef',events,matches),targets:compute('targets',events,matches),players:compute('players',events,matches),playerContext:compute('playerContext',events,matches),playersOverview:compute('playersOverview',events,matches),opponent:compute('opponent',events,matches),chains:compute('chains',events,matches),quality:compute('techniques',events,matches),rallies:compute('rallies',events,matches)});
    const host=query('#analysisResult');
    if(!ma.length){host.innerHTML=`<div class="card analysis-empty"><strong>${t('analysis.emptyMatches')}</strong><p class="small">${t('analysis.adjustFilters')}</p></div>`;return;}
    const dash=buildDash(ea,ma), dashB=compare?buildDash(eb,mb):null;
    const compareSummary=compare?{a:dash.overview,b:dashB.overview}:null;
    const num=v=>{const n=Number.parseFloat(String(v??'').replace(',','.'));return Number.isFinite(n)?n:null};
    const compareDeep=compare?(()=>{
      const a=compute('compareDeep',ea,ma),b=compute('compareDeep',eb,mb);
      const labels={rallyRate:t('analysis.rallyRateUs'),k1Sideout:'K1',firstBall:'First Ball',k2Break:'K2',k3WinRate:'K3',receptionPositive:t('analysis.receptionPositive'),attackEfficiency:t('analysis.attackEfficiencyMetric')};
      return Object.keys(labels).map(key=>{const av=num(a[key]),bv=num(b[key]),delta=av==null||bv==null?null:bv-av;return {key,label:labels[key],delta,direction:delta==null?'na':delta>0?'up':delta<0?'down':'same',deltaLabel:delta==null?'–':`${delta>0?'+':''}${delta.toFixed(1).replace('.',',')} PP`}});
    })():null;
    host.innerHTML=analysisDashboardHtml(dash,{activeView:selectedView,compareSummary,compareDeep});
    const filtersA=filterValues('a');
    const teamReport=buildTeamReport({matches:ma,dash,filters:filtersA,matchNames,matchScoreText});
    const trainerReport=buildTrainerReport({matches:ma,dash,filters:filtersA,matchNames,matchScoreText});
    trainerReport.exportBase=reportExportBase({matches:ma,filters:filtersA,matchNames,target:'Trainer'});
    const playersById=new Map(getPlayers().map(p=>[p.id,p]));
    const playerIds=[...new Set(ea.map(e=>e.player_id).filter(id=>playersById.has(id)))];
    const personalReports=playerIds.map(id=>buildPlayerReport({player:playersById.get(id),events:ea.filter(e=>e.player_id===id),matches:ma,filters:filtersA,matchNames}));
    if(selectedView==='actions'){
      const selection=buildActionSelection(ea);selection.analysisFilters=filtersA;selection.analysisView='actions';selection.matches=ma;const content=actionSelectionHtml(selection,{title:t('analysis.actionsPeriod')});
      showResult({view:'actions',content,compare:false,teamReport,trainerReport,playerReports:personalReports,videoSelection:selection});
      wireActionSelection(document,selection,{base:'VolleyTakt_Aktionsauswahl'});return;
    }
    const teamBtn=host.querySelector('[data-analysis-team-report]');
    if(teamBtn)teamBtn.onclick=()=>resultWindow.openDashboardReports({report:teamReport,trainer:trainerReport,players:personalReports});
    host.querySelectorAll('[data-analysis-detail-view]').forEach(button=>button.onclick=()=>{
      const view=button.dataset.analysisDetailView,ra=compute(view,ea,ma);
      const base=renderView(view,ra,{actions,escapeHtml,qualityChip});
      const content=`<div class="analysis-modern-detail">${detailVizHtml(view,ra)}${insightsHtml(view,ra,{events:ea,actions})}<section class="analysis-detail-table"><h4>Detaildaten</h4>${base}</section></div>`;
      let compareContent='';
      if(compare){
        const rb=compute(view,eb,mb),baseB=renderView(view,rb,{actions,escapeHtml,qualityChip});
        compareContent=`<div class="card analysis-compare-result"><h3>Vergleich B</h3><div class="analysis-modern-detail">${detailVizHtml(view,rb)}${insightsHtml(view,rb,{events:eb,actions})}<section class="analysis-detail-table">${baseB}</section></div></div>`;
      }
      const videoSelection=buildActionSelection(eventsForAnalysisView(view,ea));videoSelection.analysisFilters=filtersA;videoSelection.analysisView=view;videoSelection.matches=ma;
      showResult({view,content,compareContent,compare,teamReport,trainerReport,playerReports:personalReports,videoSelection});
    });
    const closePopovers=except=>host.querySelectorAll('.analysis-card-popover').forEach(p=>{if(p!==except)p.hidden=true});
    host.querySelectorAll('.analysis-card-help').forEach(button=>button.onclick=e=>{
      e.stopPropagation();const pop=button.closest('.analysis-dashboard-card')?.querySelector('.analysis-card-popover');if(!pop)return;const next=pop.hidden;closePopovers(pop);pop.hidden=!next;button.classList.toggle('active',next);
    });
    host.onclick=e=>{if(!e.target.closest('.analysis-card-help')&&!e.target.closest('.analysis-card-popover'))closePopovers(null)};
  };
  const draw=()=>{const matches=getMatches(),pinned=getPinnedMatchId()?matches.find(m=>m.matchId===getPinnedMatchId()):null,pinnedHtml=pinned?`<div class="card analysis-pinned"><strong>${escapeHtml(t('analysis.matchAnalysis',{name:matchNames(pinned)}))}</strong><span>${escapeHtml(pinned.matchDate||'')} · ${escapeHtml(matchScoreText(pinned))}</span><button id="analysisAllMatches">${t('analysis.allMatches')}</button></div>`:'';query('#drawerBody').innerHTML=analysisDrawerHtml({pinnedHtml,version,filterAHtml:filterBlock('a','Zeitraum / Filter A'),filterBHtml:filterBlock('b','Zeitraum / Filter B',true)});if(query('#analysisAllMatches'))query('#analysisAllMatches').onclick=()=>{clearPinnedMatch();draw();};query('#analysisCompare').onchange=()=>{query('#analysisB').hidden=!query('#analysisCompare').checked;};const updateSaved=()=>{const view=query('#analysisView')?.value||'priorityA',saved=latestAnalysisResult(view),button=query('#openSavedAnalysis');button.hidden=!saved;button.onclick=saved?()=>showResult({view,content:saved.content,record:saved}):null};query('#runAnalysis').onclick=renderResult;const viewSelect=query('#analysisView'),helpBtn=query('#analysisViewHelp'),helpText=query('#analysisViewHelpText');const updateHelp=()=>{const view=viewSelect?.value||'priorityA',tip=analysisTip(view);if(helpBtn)helpBtn.title=tip;if(helpText)helpText.textContent=tip};if(viewSelect)viewSelect.onchange=()=>{updateSaved();updateHelp()};if(helpBtn)helpBtn.onclick=()=>{if(helpText)helpText.hidden=!helpText.hidden};updateSaved();updateHelp();};
  return {draw,renderResult,filteredMatches,filteredEvents};
}
export function renderView(view,result,context={}){
  if(view==='priorityA')return renderPriorityA(result,context);
  if(view==='priorityB')return renderPriorityB(result,context);
  if(view==='k1k2')return renderK1K2(result,context);
  if(view==='firstball')return renderFirstBallDeep(result,context);
  if(view==='k3')return renderK3(result);
  if(view==='rotations')return renderRotations(result);
  if(view==='serve')return renderServe(result,context);
  if(view==='reception')return renderReception(result,context);
  if(view==='sets')return renderSet(result,context);
  if(view==='attacks')return renderAttack(result,context);
  if(view==='blockdef')return renderBlockDefense(result,context);
  if(view==='targets')return renderTargets(result);
  if(view==='chains')return renderChains(result,context);
  if(view==='chainPatterns')return renderChainPatterns(result,context);
  if(view==='opponent')return renderOpponent(result,context);
  if(view==='playersOverview')return renderPlayersOverview(result,context);
  if(view==='players')return renderPlayers(result,context);
  if(view==='playerContext')return renderPlayerContext(result,context);
  if(view==='techniques')return renderQuality(result,context);
  if(view==='rallies')return renderRallies(result,context);
  if(view==='actions')return actionSelectionHtml(result,context);
  return renderOverview(result,context);
}
import {analyzePriorityView} from './priorities.js';
import {analysisResultId,latestAnalysisResult,saveAnalysisResult} from './cache.js';
import {createResultWindow} from './result-window.js';
import {buildTeamReport} from './team-report.js';
import {buildTrainerReport} from './trainer-report.js';
import {reportExportBase} from './report-export.js';
import {buildActionSelection,eventsForAnalysisView,actionSelectionHtml,wireActionSelection} from './action-video.js';
import {buildPlayerReport} from './player-report.js';
