import {t} from '../i18n.js';
import {insightsFor,confidenceText} from './insights.js';
import {advancedInsightsFor} from './insights-advanced.js';
export function optionHtml(rows,{selected='',label=x=>x.name,escapeHtml=x=>String(x??'')}={}){
  return '<option value="">Alle</option>'+(rows||[]).map(x=>`<option value="${escapeHtml(x.id)}" ${x.id===selected?'selected':''}>${escapeHtml(label(x))}</option>`).join('');
}
export function filterBlockHtml({prefix,title,compare=false,minDate='',maxDate='',seasons=[],teams=[],matchTypes=[],players=[],actions=[],rotations=[],selectedTeamId='',escapeHtml=x=>String(x??'')}){
  const opts=(rows,selected='',label=x=>x.name)=>optionHtml(rows,{selected,label,escapeHtml});
  return `<div class="analysis-filter${compare?' compare':''}"><div class="analysis-filter-shell"><div class="analysis-filter-title"><span>⌕</span><strong>${title}</strong></div><div class="analysis-filter-grid"><label>Von <input id="${prefix}From" type="date" value="${escapeHtml(minDate)}"></label><label>Bis <input id="${prefix}To" type="date" value="${escapeHtml(maxDate)}"></label><label>Saison <select id="${prefix}Season">${opts(seasons)}</select></label><label>Team <select id="${prefix}Team">${opts(teams,selectedTeamId)}</select></label><label>Gegner <select id="${prefix}Opponent">${opts(teams)}</select></label><label>Spielart <select id="${prefix}Type">${opts(matchTypes)}</select></label><label class="analysis-player-filter">Spielerin <select id="${prefix}Player" title="Spielerin auswählen">${opts(players,'',x=>`${x.abbreviation} · ${x.firstName} ${x.lastName}`)}</select></label><label class="analysis-technique-filter">Technik <select id="${prefix}Technique"><option value="">Alle</option>${actions.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Rotation <select id="${prefix}Rotation"><option value="">Alle</option>${rotations.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Satz <select id="${prefix}Set"><option value="">Alle</option>${[1,2,3,4,5].map(x=>`<option value="${x}">${x}</option>`).join('')}</select></label></div></div></div>`;
}

const ANALYSIS_VIEW_HELP={
 priorityA:'analysis.help.priorityA',overview:'analysis.help.overview',rotations:'analysis.help.rotations',k1k2:'analysis.help.k1k2',
 priorityB:'analysis.help.priorityB',serve:'analysis.help.serve',reception:'analysis.help.reception',sets:'analysis.help.sets',attacks:'analysis.help.attacks',players:'analysis.help.players',
 chains:'analysis.help.chains',chainPatterns:'analysis.help.chains',opponent:'analysis.help.opponent',playersOverview:'analysis.help.playersOverview',playerContext:'analysis.help.players',techniques:'analysis.help.techniques',rallies:'analysis.help.rallies',firstball:'analysis.help.k1k2',k3:'analysis.help.k1k2',blockdef:'analysis.help.techniques',targets:'analysis.help.attacks'
};
const analysisTip=view=>t(ANALYSIS_VIEW_HELP[view]||'analysis.help.overview');
const analysisOption=(value,label)=>`<option value="${value}" title="${analysisTip(value)}">${label}</option>`;
const metricTip=key=>t(`analysis.metric.${key}`);
const tipAttr=key=>` title="${metricTip(key)}"`;
const pctNumber=value=>{const n=Number.parseFloat(String(value??'').replace(',','.'));return Number.isFinite(n)?n:0};
const weightedPercent=(rows,valueKey,countKey='n')=>{let n=0,total=0;for(const row of rows||[]){const count=Number(row?.[countKey]||0),value=pctNumber(row?.[valueKey]);n+=count;total+=value*count;}return n?`${(total/n).toFixed(1).replace('.',',')} %`:'–'};
const sum=(rows,key)=> (rows||[]).reduce((acc,row)=>acc+Number(row?.[key]||0),0);
const pct=value=>Math.max(0,Math.min(100,pctNumber(value)));
const donut=(value,label='')=>`<div class="analysis-mini-donut" style="--p:${pct(value)}"><span>${value||'–'}</span>${label?`<small>${label}</small>`:''}</div>`;
const bars=(rows,valueKey,labelKey,{limit=6}={})=>{const data=(rows||[]).slice(0,limit),max=Math.max(1,...data.map(r=>Number(r?.[valueKey]||0)));return `<div class="analysis-mini-bars-chart">${data.map(r=>`<div><span>${r?.[labelKey]??''}</span><i><b style="width:${Math.max(4,Number(r?.[valueKey]||0)/max*100)}%"></b></i><strong>${r?.[valueKey]??0}</strong></div>`).join('')||'<em>Keine Daten</em>'}</div>`};
const rotationBars=rows=>bars((rows||[]).filter(r=>Number(r.rallies)>0).map(r=>({label:r.rotation,value:pctNumber(r.k1Sideout)})),'value','label');
const card=(view,icon,title,help,metrics,viz='',detail='Details')=>`<article class="analysis-dashboard-card" data-analysis-card="${view}"><header><span class="analysis-dashboard-icon">${icon}</span><h4>${title}</h4><button type="button" class="analysis-card-help" title="${help}" aria-label="${title} erklären">ⓘ</button></header><div class="analysis-card-popover" hidden role="note">${help}</div><div class="analysis-card-body"><div class="analysis-card-metrics">${metrics}</div>${viz?`<div class="analysis-card-viz">${viz}</div>`:''}</div><button type="button" class="analysis-card-detail" data-analysis-detail-view="${view}">${detail} →</button></article>`;

const DASHBOARD_VIEW_CARDS={
 priorityA:['overview','k1k2','rotations','serve','reception','attacks','players','opponent','chains','rallies'],
 overview:['overview','rotations','k1k2','rallies','serve','reception','attacks'],
 rotations:['rotations','k1k2','reception','sets','attacks','players','chains'],
 firstball:['firstball','k1k2','reception','sets','attacks','rotations','players'],
 k3:['k3','blockdef','rotations','attacks','sets','chains','players'],
 k1k2:['k1k2','rotations','reception','sets','attacks','players'],
 priorityB:['serve','reception','sets','attacks','players','techniques','chains'],
 serve:['serve','k1k2','rotations','opponent','chains','rallies'],
 blockdef:['blockdef','k3','rotations','attacks','sets','chains','players'],
 targets:['targets','serve','attacks','opponent','chains'],
 reception:['reception','k1k2','rotations','sets','attacks','players'],
 sets:['sets','reception','attacks','players','chains','rotations'],
 attacks:['attacks','sets','reception','players','chains','rotations'],
 players:['players','playersOverview','techniques','rotations','reception','attacks','serve'],
 playerContext:['players','playersOverview','rotations','reception','attacks','serve','chains'],
 chains:['chains','reception','sets','attacks','rallies','players'],
 chainPatterns:['chains','reception','sets','attacks','rallies','players'],
 opponent:['opponent','serve','reception','attacks','chains','rallies'],
 playersOverview:['playersOverview','players','techniques','rotations','serve','reception','attacks'],
 techniques:['techniques','serve','reception','sets','attacks','players'],
 rallies:['rallies','overview','rotations','k1k2','chains']
};
const dashboardAllows=(activeView,cardView)=>{
  const allowed=DASHBOARD_VIEW_CARDS[activeView]||DASHBOARD_VIEW_CARDS.priorityA;
  return allowed.includes(cardView);
};
const detailBars=(rows,valueKey,labelKey,{limit=8,suffix=''}={})=>{
 const data=(rows||[]).slice(0,limit),max=Math.max(1,...data.map(r=>Math.abs(Number(r?.[valueKey]||0))));
 return `<div class="analysis-detail-bars">${data.map(r=>`<div><span>${r?.[labelKey]??'–'}</span><i><b style="width:${Math.max(2,Math.abs(Number(r?.[valueKey]||0))/max*100)}%"></b></i><strong>${r?.[valueKey]??0}${suffix}</strong></div>`).join('')||'<em>Keine Daten</em>'}</div>`;
};
const insightsHtml=(view,result,context={})=>{
 const rows=[...insightsFor(view,result),...advancedInsightsFor(view,result,context)];
 if(!rows.length)return '';
 return `<section class="analysis-insights"><header><h4>Interpretation</h4><button type="button" class="analysis-insight-info" aria-label="Interpretation erklären" title="Automatisch aus den aktuell gefilterten Daten abgeleitete Hinweise.">ⓘ</button></header><div class="analysis-insight-explain" hidden>Die Hinweise werden lokal aus Kennzahlen, Vergleichswerten und Datenmenge erzeugt. Sie sind eine Analysehilfe und keine automatische Trainerentscheidung.</div>${rows.map(x=>`<article class="analysis-insight ${x.kind||'neutral'}"><strong>${x.finding}</strong><p>${x.context}</p><p><b>Weiter analysieren:</b> ${x.next}</p><small>${confidenceText(x.confidence,x.sample)}</small></article>`).join('')}<div class="analysis-confidence-legend">Datenbasis: n &lt; 4 = zu wenig Daten · 4–7 = kleine Datenbasis · 8–17 = mittlere Datenbasis · ab 18 = gute Datenbasis.</div></section>`;
};
const detailVizHtml=(view,result)=>{
 if(view==='rotations')return `<section class="analysis-detail-viz"><h4>K1 / K2 / K3 nach Rotation</h4><div class="analysis-triple-bars">${(result||[]).filter(r=>Number(r.rallies)>0).map(r=>`<div class="analysis-triple-row"><strong>${r.rotation}</strong><span>K1</span><i><b style="width:${pct(r.k1Sideout)}%"></b></i><em>${r.k1Sideout}</em><span>K2</span><i><b style="width:${pct(r.k2Break)}%"></b></i><em>${r.k2Break}</em><span>K3</span><i><b style="width:${pct(r.k3WinRate)}%"></b></i><em>${r.k3WinRate||'–'}</em></div>`).join('')||'<em>Keine Rotationsdaten</em>'}</div></section>`;
 if(view==='firstball')return `<section class="analysis-detail-viz"><h4>First-Ball nach Rotation</h4>${detailBars((result?.byRotation||[]).filter(r=>r.rallies).map(r=>({label:r.rotation,value:pctNumber(r.firstBall)})),'value','label',{suffix:' %'})}</section>`;
 if(view==='k3')return `<section class="analysis-detail-viz"><h4>K3 / Transition nach Rotation</h4>${detailBars((result?.byRotation||[]).filter(r=>r.n).map(r=>({label:r.rotation,value:pctNumber(r.winRate)})),'value','label',{suffix:' %'})}</section>`;
 if(view==='k1k2')return `<section class="analysis-detail-viz"><h4>Phasenvergleich</h4><div class="analysis-big-donuts">${donut(result.k1Sideout,'K1 Sideout')}${donut(result.firstBall,'First Ball')}${donut(result.k2Break,'K2 Break')}</div>${detailBars((result.rotations||[]).filter(r=>Number(r.rallies)>0).map(r=>({label:r.rotation,value:pctNumber(r.k1Sideout)})),'value','label',{suffix:' %'})}</section>`;
 if(view==='serve')return `<section class="analysis-detail-viz"><h4>Aufschlagmuster</h4>${detailBars(result,'n','tech',{limit:10})}</section>`;
 if(view==='reception')return `<section class="analysis-detail-viz"><h4>Positive Annahme nach Spielerin</h4>${detailBars((result||[]).map(r=>({label:r.p,value:pctNumber(r.posRate)})),'value','label',{limit:10,suffix:' %'})}</section>`;
 if(view==='sets')return `<section class="analysis-detail-viz"><h4>Zuspiel-Zielverteilung</h4>${detailBars(result,'n','to',{limit:10})}</section>`;
 if(view==='attacks')return `<section class="analysis-detail-viz"><h4>Angriffseffizienz nach Muster</h4>${detailBars((result||[]).map(r=>({label:`${r.p} ${r.from}→${r.to}`,value:pctNumber(r.efficiency)})),'value','label',{limit:10,suffix:' %'})}</section>`;
 if(view==='blockdef')return `<section class="analysis-detail-viz"><h4>Block-/Abwehrwirkung</h4>${detailBars((result||[]).map(r=>({label:`${r.technique} ${r.p}`,value:pctNumber(r.transitionWinRate)})),'value','label',{limit:10,suffix:' %'})}</section>`;
 if(view==='targets')return `<section class="analysis-detail-viz"><h4>Zielzonen – Häufigkeit</h4>${detailBars((result||[]).map(r=>({label:`${r.technique} ${r.from}→${r.to}`,value:r.n||0})),'value','label',{limit:12})}</section>`;
 if(view==='chainPatterns')return `<section class="analysis-detail-viz"><h4>Gewinn-/Verlustketten</h4>${detailBars((result||[]).map(r=>({label:`${r.phase} ${r.rotation} ${r.label}`,value:pctNumber(r.winRate)})),'value','label',{limit:12,suffix:' %'})}</section>`;
 if(view==='playerContext')return `<section class="analysis-detail-viz"><h4>Spielerinnen im Kontext</h4>${detailBars((result||[]).map(r=>({label:r.player?.abbreviation||'–',value:r.actions||0})),'value','label',{limit:10})}</section>`;
 if(view==='players')return `<section class="analysis-detail-viz"><h4>Aktionsvolumen</h4>${detailBars((result||[]).map(r=>({label:r.player?.abbreviation||'–',value:r.actions||0})),'value','label',{limit:10})}</section>`;
 if(view==='playersOverview')return `<section class="analysis-detail-viz"><h4>Spielerinnen – Aktionsvolumen</h4>${detailBars((result||[]).map(r=>({label:r.player?.abbreviation||'–',value:r.actions||0})),'value','label',{limit:10})}</section>`;
 if(view==='chains')return `<section class="analysis-detail-viz"><h4>Häufigste Aktionsketten</h4>${detailBars((result||[]).map((r,i)=>({label:`${r.rec||'–'}→${r.att||'–'}`,value:r.n||0})),'value','label',{limit:10})}</section>`;
 if(view==='opponent')return `<section class="analysis-detail-viz"><h4>Gegnerische Ziel-/Angriffsmuster</h4>${detailBars([...(result?.attacks||[]).map(r=>({label:`Angriff ${r.from}→${r.to}`,value:r.n||0})),...(result?.serves||[]).map(r=>({label:`Aufschlag → ${r.target}`,value:r.n||0}))],'value','label',{limit:10})}</section>`;
 if(view==='techniques')return `<section class="analysis-detail-viz"><h4>Qualitätsverteilung</h4>${detailBars((result?.rows||[]).map(r=>({label:r.quality,value:r.count||0})),'value','label',{limit:8})}</section>`;
 if(view==='overview')return `<section class="analysis-detail-viz"><h4>Spielphasen</h4><div class="analysis-big-donuts">${donut(result.rallyRate,'Rallyquote')}${donut(result.k1Sideout,'K1')}${donut(result.firstBall,'First Ball')}${donut(result.k2Break,'K2')}</div>${detailBars(Object.entries(result.bySource||{}).map(([label,value])=>({label,value})),'value','label',{limit:6})}</section>`;
 if(view==='rallies')return `<section class="analysis-detail-viz"><h4>Rally-Verteilung</h4>${detailBars((result||[]).map((r,i)=>({label:`R${i+1}`,value:r.actions||r.actionCount||0})),'value','label',{limit:12})}</section>`;
 return '';
};
export function analysisDashboardHtml({overview,k1k2,firstball,k3,rotations,serve,reception,sets,attacks,blockdef,targets,players,playersOverview,opponent,chains,quality,rallies},{activeView='priorityA',compareSummary=null,compareDeep=null}={}){
  const activeRot=(rotations||[]).filter(r=>Number(r.rallies)>0), best=activeRot.slice().sort((a,b)=>pctNumber(b.k1Sideout)-pctNumber(a.k1Sideout))[0], worst=activeRot.slice().sort((a,b)=>pctNumber(a.k1Sideout)-pctNumber(b.k1Sideout))[0];
  const totalServes=sum(serve,'n'), topServe=(serve||[])[0];
  const totalRec=sum(reception,'n'), recPos=weightedPercent(reception,'posRate');
  const totalSets=sum(sets,'n'), topSet=(sets||[])[0];
  const totalAttacks=sum(attacks,'n'), attackEff=weightedPercent(attacks,'efficiency');
  const topPlayer=(players||[])[0];
  const oppAttack=sum(opponent?.attacks,'n'), oppServe=sum(opponent?.serves,'n');
  const topChain=(chains||[])[0], qualityTop=(quality?.rows||[])[0];
  const firstBallTotal=firstball?.total||{};
  const k3Total=k3?.total||{};
  const blockDefTotal=(blockdef||[]).reduce((a,r)=>a+Number(r.n||0),0);
  const targetTotal=(targets||[]).reduce((a,r)=>a+Number(r.n||0),0);
  const attackByFrom=Object.values((attacks||[]).reduce((a,r)=>{const k=r.from||'–';a[k]??={label:k,n:0};a[k].n+=Number(r.n||0);return a},{})).sort((a,b)=>b.n-a.n);
  const serveByTech=Object.values((serve||[]).reduce((a,r)=>{const k=r.tech||'–';a[k]??={label:k,n:0};a[k].n+=Number(r.n||0);return a},{})).sort((a,b)=>b.n-a.n);
  const setByTarget=Object.values((sets||[]).reduce((a,r)=>{const k=r.to||'–';a[k]??={label:k,n:0};a[k].n+=Number(r.n||0);return a},{})).sort((a,b)=>b.n-a.n);
  const oppByZone=Object.values([...(opponent?.attacks||[]),...(opponent?.serves||[])].reduce((a,r)=>{const k=r.to||r.z||r.target||'–';a[k]??={label:k,n:0};a[k].n+=Number(r.n||0);return a},{})).sort((a,b)=>b.n-a.n);
  const rallyHist=Object.values((rallies||[]).reduce((a,r)=>{const n=Number(r.actions||r.actionCount||r.n||0),k=n>=9?'9+':String(n||0);a[k]??={label:k,n:0};a[k].n++;return a},{})).sort((a,b)=>{const av=a.label==='9+'?9:Number(a.label),bv=b.label==='9+'?9:Number(b.label);return av-bv});
  const m=(big,label,small='')=>`<div><strong>${big}</strong><span>${label}</span>${small?`<small>${small}</small>`:''}</div>`;
  return `<section class="analysis-dashboard" aria-label="Analyse-Dashboard"><div class="analysis-dashboard-head"><div><h3>Analyse – Dashboard</h3><span class="analysis-dashboard-context">Ansicht: ${activeView}</span><p class="small">Die Kacheln passen sich automatisch an die verfügbare Breite an. Details öffnen die jeweilige vollständige Analyse.</p></div><div class="analysis-dashboard-actions"><button type="button" data-analysis-team-report>Report erzeugen</button></div></div><div class="analysis-dashboard-grid">
  ${dashboardAllows(activeView,'overview')?card('overview','▥','Spielübersicht',analysisTip('overview'),m(overview.rallyRate,'Rallyquote Wir',`${overview.rallies} Rallys`)+m(overview.matches,'Spiele'),donut(overview.rallyRate,'Rallyquote')):''}
  ${dashboardAllows(activeView,'k1k2')?card('k1k2','↻','K1 / Sideout',analysisTip('k1k2'),m(k1k2.k1Sideout,'Sideout',`${k1k2.k1Count} K1-Rallys`)+m(k1k2.firstBall,'First Ball'),donut(k1k2.k1Sideout,'K1')+rotationBars(k1k2.rotations)):''}
  ${dashboardAllows(activeView,'k1k2')?card('k1k2','⚡','K2 / Break',analysisTip('k1k2'),m(k1k2.k2Break,'Breakquote',`${k1k2.k2Count} K2-Rallys`),donut(k1k2.k2Break,'K2')+rotationBars((k1k2.rotations||[]).map(r=>({...r,k1Sideout:r.k2Break})))):''}
  ${dashboardAllows(activeView,'firstball')?card('firstball','◎','First-Ball-Sideout',analysisTip('firstball'),m(firstBallTotal.firstBall||'–','First Ball',`${firstBallTotal.rallies||0} K1-Rallys`)+m(firstBallTotal.recPositive||'–','Annahme +/#'),donut(firstBallTotal.firstBall||'0 %','First Ball')):''}
  ${dashboardAllows(activeView,'k3')?card('k3','↺','K3 / Transition',analysisTip('k3'),m(k3Total.winRate||'–','K3-Erfolg',`${k3Total.n||0} Transitionen`)+m(k3Total.killRate||'–','Transition-Angriff #'),donut(k3Total.winRate||'0 %','K3')):''}
  ${dashboardAllows(activeView,'rotations')?card('rotations','⟳','Rotationen',analysisTip('rotations'),m(best?.rotation||'–','Beste Rotation',best?.k1Sideout||'')+m(worst?.rotation||'–','Schwächste Rotation',worst?.k1Sideout||''),rotationBars(rotations)):''}
  ${dashboardAllows(activeView,'serve')?card('serve','▶','Aufschlag',analysisTip('serve'),m(totalServes,'Aufschläge',topServe?`Top Break: ${topServe.breakRate}`:'')+m((serve||[]).length,'Muster'),bars(serveByTech,'n','label',{limit:4})):''}
  ${dashboardAllows(activeView,'reception')?card('reception','◉','Annahme',analysisTip('reception'),m(recPos,'Positiv +/#',`${totalRec} Annahmen`)+m((reception||[]).length,'Spielerinnen'),donut(recPos,'positiv')+bars((reception||[]).map(r=>({label:r.p,n:r.n})),'n','label',{limit:4})):''}
  ${dashboardAllows(activeView,'sets')?card('sets','⌁','Zuspiel',analysisTip('sets'),m(totalSets,'Zuspiele',topSet?`${topSet.from} → ${topSet.to}`:'')+m((sets||[]).length,'Zuspielwege'),bars(setByTarget,'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'attacks')?card('attacks','➤','Angriff',analysisTip('attacks'),m(attackEff,'Effizienz',`${totalAttacks} Angriffe`)+m((attacks||[]).length,'Quelle/Ziel-Muster'),donut(attackEff,'Effizienz')+bars(attackByFrom,'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'blockdef')?card('blockdef','✋','Block / Abwehr',analysisTip('blockdef'),m(blockDefTotal,'Aktionen')+m((blockdef||[]).reduce((a,r)=>a+Number(r.transitionAttack||0),0),'Transition-Angriffe'),bars((blockdef||[]).map(r=>({label:`${r.technique} ${r.p}`,n:r.n})),'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'targets')?card('targets','⌖','WO / WOHIN',analysisTip('targets'),m(targetTotal,'Zielaktionen')+m((targets||[]).length,'Muster'),bars((targets||[]).map(r=>({label:`${r.technique} ${r.from}→${r.to}`,n:r.n})),'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'players')?card('players','♟','Spielerinnenwirkung',analysisTip('players'),m((players||[]).length,'Spielerinnen',topPlayer?`Meiste Aktionen: ${topPlayer.actions}`:'')+m(topPlayer?.player?.abbreviation||'–','Top Aktivität'),bars((players||[]).map(r=>({label:r.player?.abbreviation||r.p||'–',n:r.actions||r.n||0})),'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'opponent')?card('opponent','⌖','Gegneranalyse',analysisTip('opponent'),m(oppAttack,'Gegnerangriffe')+m(oppServe,'Gegneraufschläge'),bars(oppByZone,'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'chains')?card('chains','⛓','Aktionsketten',analysisTip('chains'),m((chains||[]).length,'Kettenmuster',topChain?`${topChain.n}× häufigste Kette`:''),bars((chains||[]).map((r,i)=>({label:r.label||r.chain||`K${i+1}`,n:r.n||0})),'n','label',{limit:5})):''}
  ${dashboardAllows(activeView,'techniques')?card('techniques','★','Technikqualität',analysisTip('techniques'),m(quality?.total||0,'Aktionen',qualityTop?`${qualityTop.quality}: ${qualityTop.share}`:''),bars((quality?.rows||[]).map(r=>({label:r.quality,n:r.n||r.count||0})),'n','label',{limit:6})):''}
  ${dashboardAllows(activeView,'rallies')?card('rallies','⌁','Rallyanalyse',analysisTip('rallies'),m((rallies||[]).length,'Rallys in Ansicht')+m((rallies||[]).filter(r=>r.winner==='us').length,'Gewonnen'),bars(rallyHist,'n','label',{limit:9})):''}
  ${dashboardAllows(activeView,'playersOverview')?card('playersOverview','♟','Spielerinnen – Übersicht',analysisTip('playersOverview'),m((playersOverview||[]).length,'Spielerinnen')+m(sum(playersOverview,'actions'),'Aktionen'),bars((playersOverview||[]).map(r=>({label:r.player?.abbreviation||r.p||'–',n:r.actions||0})),'n','label',{limit:5})):''}
  </div>${compareSummary?`<section class="analysis-compare-summary"><h4>Zeitraum A ↔ B</h4><div><span>A</span><strong>${compareSummary.a.matches} Spiele · ${compareSummary.a.rallies} Rallys · ${compareSummary.a.rallyRate}</strong></div><div><span>B</span><strong>${compareSummary.b.matches} Spiele · ${compareSummary.b.rallies} Rallys · ${compareSummary.b.rallyRate}</strong></div>${compareDeep?`<div class="analysis-compare-deltas">${compareDeep.map(x=>`<span><b>${x.label}</b><strong class="${x.direction}">${x.deltaLabel}</strong></span>`).join('')}</div>`:''}</section>`:''}</section>`;
}

export function resultShellHtml({content,compareContent='',compare=false}){return `<div class="card"><h3>Auswertung A</h3>${content}</div>${compare?compareContent:''}`;}
export function analysisDrawerHtml({pinnedHtml='',version,filterAHtml,filterBHtml}){return `${pinnedHtml}<div class="card analysis-card"><div class="analysis-heading"><h3>Analyse <span class="preview-pill">${version}</span></h3><p class="small">Fachlich gruppierte Übersichten und Detailanalysen · gleiche Datenbasis für einfaches und detailliertes Scouting.</p></div><div class="analysis-top"><label>Ansicht <select id="analysisView"><optgroup label="Spiel &amp; Phasen">${analysisOption('priorityA','Spielsteuerung im Überblick')}${analysisOption('overview','Spiel- / Satzübersicht')}${analysisOption('rotations','Rotations-Dashboard')}${analysisOption('k1k2','K1, First Ball &amp; K2')}${analysisOption('firstball','First-Ball-Sideout vertieft')}${analysisOption('k3','K3 / Transition')}</optgroup><optgroup label="Technik &amp; Wirkung">${analysisOption('priorityB','Technik- und Spielerinnenwirkung')}${analysisOption('serve','Aufschlagwirkung')}${analysisOption('reception','Annahme &amp; Sideout')}${analysisOption('sets','Zuspielverteilung')}${analysisOption('attacks','Angriff Quelle → Ziel')}${analysisOption('blockdef','Block / Abwehr &amp; Transition')}${analysisOption('targets','WO / WOHIN Zielzonen')}${analysisOption('players','Spielerinnenwirkung')}${analysisOption('playerContext','Spielerinnen im Kontext')}</optgroup><optgroup label="Vertiefende Analysen">${analysisOption('chains','Kontextketten')}${analysisOption('chainPatterns','Gewinn-/Verlustketten')}${analysisOption('opponent','Gegner-Tendenzen')}${analysisOption('playersOverview','Spielerinnen – Übersicht')}${analysisOption('techniques','Techniken / Qualität')}${analysisOption('rallies','Rallys')}</optgroup></select></label><button type="button" id="analysisViewHelp" class="analysis-help-button" title="${analysisTip('priorityA')}" aria-label="Analyse erklären">ⓘ</button><label class="analysis-compare-toggle"><input id="analysisCompare" type="checkbox"> Zeitraum A mit B vergleichen</label></div><p id="analysisViewHelpText" class="analysis-view-help small" hidden>${analysisTip('priorityA')}</p>${filterAHtml}<div id="analysisB" hidden>${filterBHtml}</div><div class="toolbar mt"><button id="runAnalysis" class="primary">Auswerten</button><button id="openSavedAnalysis" hidden>Gespeichertes Ergebnis öffnen</button></div></div><div id="analysisResult"><div class="card small">Mit „Auswerten“ wird das Dashboard für die gewählten Filter aufgebaut.</div></div>`;}

const signalHtml=(title,signal,escapeHtml)=>signal?.best?`<div><strong>${escapeHtml(title)}</strong><span>Beste: ${escapeHtml(signal.best.label)} · ${escapeHtml(signal.best.value)}</span>${signal.worst&&signal.worst.label!==signal.best.label?`<small>Schwächste: ${escapeHtml(signal.worst.label)} · ${escapeHtml(signal.worst.value)}</small>`:''}</div>`:'';
const sectionNav=labels=>`<nav class="analysis-section-nav" aria-label="Analysebereiche"><button data-analysis-section="all" class="selected" title="${analysisTip('priorityA')}">Gesamtübersicht</button>${labels.map(([key,label,view=key])=>`<button data-analysis-section="${key}" title="${analysisTip(view)}">${label}</button>`).join('')}</nav>`;
export function renderPriorityA(r,{escapeHtml=x=>String(x??'')}={}){const o=r.overview,p=r.phases;return `<section class="analysis-cluster"><h3>Spiel &amp; Phasen</h3>${sectionNav([['game','Spielverlauf','overview'],['rotation','Rotation','rotations'],['sideout','K1 / Sideout','k1k2'],['firstball','First-Ball-Sideout','k1k2'],['breakpoint','K2 / Breakpoint','k1k2']])}<section class="analysis-detail-section" data-analysis-detail="game"><h4>Spielverlauf</h4><div class="analysis-kpis"><div><strong>${o.matches}</strong><span>Spiele</span></div><div><strong>${o.rallies}</strong><span>Rallys</span></div><div><strong>${o.rallyRate}</strong><span title="${metricTip('rallyRate')}">Rallyquote Wir</span></div></div><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Satz</th><th>Rallys</th><th>Rallyquote</th><th>K1 Sideout</th><th>First Ball</th><th>K2 Break</th></tr></thead><tbody>${r.bySet.map(x=>`<tr><td>${x.set}</td><td>${x.rallies}</td><td>${x.rallyRate}</td><td>${x.sideout}</td><td>${x.firstBall}</td><td>${x.breakpoint}</td></tr>`).join('')||'<tr><td colspan="6">Keine abgeschlossenen Rallys</td></tr>'}</tbody></table></div></section><section class="analysis-detail-section" data-analysis-detail="rotation"><h4>Rotation</h4>${renderRotations(r.rotations)}</section><section class="analysis-detail-section" data-analysis-detail="sideout"><h4>K1 / Sideout</h4><div class="analysis-kpis"><div><strong>${p.k1Sideout}</strong><span title="${metricTip('k1Sideout')}">Sideout</span></div><div><strong>${p.k1Count}</strong><span>K1-Rallys</span></div></div></section><section class="analysis-detail-section" data-analysis-detail="firstball"><h4>First-Ball-Sideout</h4><div class="analysis-kpis"><div><strong>${p.firstBall}</strong><span title="${metricTip('firstBall')}">First Ball</span></div><div><strong>${p.k1Count}</strong><span>K1-Rallys</span></div></div></section><section class="analysis-detail-section" data-analysis-detail="breakpoint"><h4>K2 / Breakpoint</h4><div class="analysis-kpis"><div><strong>${p.k2Break}</strong><span title="${metricTip('k2Break')}">Breakpoint</span></div><div><strong>${p.k2Count}</strong><span>K2-Rallys</span></div></div></section></section>`;}
export function renderPriorityB(r,{escapeHtml=x=>String(x??'')}={}){return `<section class="analysis-cluster"><h3>Technik &amp; Wirkung</h3>${sectionNav([['serve','Aufschlag','serve'],['reception','Annahme','reception'],['set','Zuspiel','sets'],['attack','Angriff','attacks'],['players','Spielerinnenwirkung','players']])}<section class="analysis-detail-section" data-analysis-detail="serve"><h4>Aufschlagwirkung</h4>${renderServe(r.serve,{escapeHtml})}</section><section class="analysis-detail-section" data-analysis-detail="reception"><h4>Annahme &amp; Sideout</h4>${renderReception(r.reception,{escapeHtml})}</section><section class="analysis-detail-section" data-analysis-detail="set"><h4>Zuspielverteilung</h4>${renderSet(r.sets,{escapeHtml})}</section><section class="analysis-detail-section" data-analysis-detail="attack"><h4>Angriffseffizienz</h4>${renderAttack(r.attacks,{escapeHtml})}</section><section class="analysis-detail-section" data-analysis-detail="players"><h4>Spielerinnenwirkung</h4>${renderPlayers(r.players,{escapeHtml})}</section></section>`;}
export function renderQuality(result,{escapeHtml=x=>String(x??''),qualityChip=q=>escapeHtml(q)}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Qualität</th><th>Anzahl</th><th>Anteil</th></tr></thead><tbody>${result.rows.map(r=>`<tr><td>${qualityChip(r.quality)}</td><td>${r.count}</td><td>${r.share}</td></tr>`).join('')||'<tr><td colspan="3">Keine Aktionen</td></tr>'}</tbody></table></div>`;}
export function renderRotations(rows){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Rotation</th><th>Rallys</th><th>Rallybilanz</th><th>K1</th><th>First Ball</th><th>K2</th><th>K3</th><th>Annahme +/#</th><th>1. Angriff #</th><th>Angriff #</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.rotation}</td><td>${r.rallies}</td><td>${r.points>=0?'+':''}${r.points}</td><td>${r.k1Sideout}</td><td>${r.firstBall}</td><td>${r.k2Break}</td><td>${r.k3WinRate||'–'}</td><td>${r.receptionPositive}</td><td>${r.firstAttackKill||'–'}</td><td>${r.attackKill}</td></tr>`).join('')||'<tr><td colspan="10">Keine Rotationsdaten</td></tr>'}</tbody></table></div><p class="small">Rallybilanz = gewonnene minus verlorene Rallys während dieser Rotation. K3 = Transition nach gegnerischem Angriff über Block/Abwehr.</p>`;}
export function renderPlayers(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Spielerin</th><th>Aktionen</th><th>#</th><th>+</th><th>0/!</th><th>−</th><th>=</th><th>Rally +*</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.player.abbreviation)} · ${escapeHtml(r.player.firstName)} ${escapeHtml(r.player.lastName)}</td><td>${r.actions}</td><td>${r.hash}</td><td>${r.plus}</td><td>${r.neutral}</td><td>${r.minus}</td><td>${r.error}</td><td>${r.rallyWon}</td></tr>`).join('')||'<tr><td colspan="8">Keine Spielerinnenaktionen</td></tr>'}</tbody></table></div><p class="small">* Gewonnene Rallys mit mindestens einer Aktion dieser Spielerin; keine Kausalitätsaussage.</p>`;}
export function renderPlayersOverview(rows,{actions=[],escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact players-overview"><thead><tr><th>Spielerin</th><th>Aktionen</th>${actions.map(t=>`<th title="${escapeHtml(t)}">${escapeHtml(t)}</th>`).join('')}<th>Rallys +</th><th>Rallys −</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.player.abbreviation)} · ${escapeHtml(r.player.firstName)} ${escapeHtml(r.player.lastName)}</td><td>${r.actions}</td>${actions.map(t=>`<td>${r.by[t]||0}</td>`).join('')}<td>${r.won}</td><td>${r.lost}</td></tr>`).join('')||`<tr><td colspan="${actions.length+4}">Keine Spielerinnenaktionen</td></tr>`}</tbody></table></div><p class="small">Rallys +/− zeigen Mannschaftserfolg während der Beteiligung; Einzelaktionen bleiben getrennt auswertbar.</p>`;}
export function renderK1K2(result,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-kpis"><div><strong>${result.k1Sideout}</strong><span title="${metricTip('k1Sideout')}">K1 Sideout</span></div><div><strong>${result.firstBall}</strong><span>First-Ball-Sideout</span></div><div><strong>${result.k2Break}</strong><span title="${metricTip('k2Break')}">K2 Breakpoint</span></div><div><strong>${result.k1Count}</strong><span>K1 Rallys</span></div><div><strong>${result.k2Count}</strong><span>K2 Rallys</span></div></div>${renderRotations(result.rotations)}<h4>Sideout nach Annahmequalität</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Annahme</th><th>Rallys</th><th>Sideout</th><th>First Ball</th></tr></thead><tbody>${result.receptionQuality.map(r=>`<tr><td>${escapeHtml(r.quality)}</td><td>${r.rallies}</td><td>${r.sideout}</td><td>${r.firstBall}</td></tr>`).join('')||'<tr><td colspan="4">Keine K1-Daten</td></tr>'}</tbody></table></div>`;}

export function renderFirstBallDeep(result,{escapeHtml=x=>String(x??'')}={}){
 const t=result.total||{};
 return `<div class="analysis-kpis"><div><strong>${t.rallies||0}</strong><span>K1-Rallys</span></div><div><strong>${t.sideout||'–'}</strong><span>Sideout</span></div><div><strong>${t.firstBall||'–'}</strong><span>First Ball</span></div><div><strong>${t.recPositive||'–'}</strong><span>Annahme +/#</span></div><div><strong>${t.attackKill||'–'}</strong><span>1. Angriff #</span></div></div><h4>Nach Rotation</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Rotation</th><th>K1</th><th>Sideout</th><th>First Ball</th><th>Annahme +/#</th><th>Annahme #</th><th>1. Angriff #</th></tr></thead><tbody>${(result.byRotation||[]).filter(r=>r.rallies).map(r=>`<tr><td>${r.rotation}</td><td>${r.rallies}</td><td>${r.sideout}</td><td>${r.firstBall}</td><td>${r.recPositive}</td><td>${r.recPerfect}</td><td>${r.attackKill}</td></tr>`).join('')||'<tr><td colspan="7">Keine K1-Daten</td></tr>'}</tbody></table></div><h4>Nach Annahmequalität</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Qualität</th><th>Rallys</th><th>Sideout</th><th>First Ball</th><th>1. Angriff #</th></tr></thead><tbody>${(result.byReception||[]).map(r=>`<tr><td>${escapeHtml(r.quality)}</td><td>${r.rallies}</td><td>${r.sideout}</td><td>${r.firstBall}</td><td>${r.attackKill}</td></tr>`).join('')||'<tr><td colspan="5">Keine Annahmegruppen</td></tr>'}</tbody></table></div>`;
}
export function renderK3(result){
 const t=result.total||{};
 return `<div class="analysis-kpis"><div><strong>${t.n||0}</strong><span>Transitionen</span></div><div><strong>${t.winRate||'–'}</strong><span>K3-Rallyerfolg</span></div><div><strong>${t.killRate||'–'}</strong><span>Transition-Angriff #</span></div><div><strong>${t.attackErrors||0}</strong><span>Angriffsfehler</span></div></div><h4>Nach Rotation</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Rotation</th><th>K3</th><th>gewonnen</th><th>K3-Erfolg</th><th>Angriff #</th></tr></thead><tbody>${(result.byRotation||[]).filter(r=>r.n).map(r=>`<tr><td>${r.rotation}</td><td>${r.n}</td><td>${r.won}</td><td>${r.winRate}</td><td>${r.killRate}</td></tr>`).join('')||'<tr><td colspan="5">Noch keine vollständigen Transition-Ketten</td></tr>'}</tbody></table></div><h4>Auslöser</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Block/Abwehr</th><th>K3</th><th>K3-Erfolg</th><th>Angriff #</th></tr></thead><tbody>${(result.byTrigger||[]).filter(r=>r.n).map(r=>`<tr><td>${r.trigger}</td><td>${r.n}</td><td>${r.winRate}</td><td>${r.killRate}</td></tr>`).join('')||'<tr><td colspan="4">Keine Transitionen</td></tr>'}</tbody></table></div>`;
}
export function renderBlockDefense(rows,{escapeHtml=x=>String(x??'')}={}){
 return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Technik</th><th>Spielerin</th><th>Aktionen</th><th>direkter Punkt</th><th>weitergespielt</th><th>Transition-Angriffe</th><th>Transition gewonnen</th></tr></thead><tbody>${(rows||[]).map(r=>`<tr><td>${r.technique}</td><td>${escapeHtml(r.p)}</td><td>${r.n}</td><td>${r.directRate}</td><td>${r.continuedRate}</td><td>${r.transitionAttack}</td><td>${r.transitionWinRate}</td></tr>`).join('')||'<tr><td colspan="7">Keine Block-/Abwehraktionen</td></tr>'}</tbody></table></div>`;
}
export function renderTargets(rows){
 return `<div class="analysis-target-grid">${['Aufschlag','Angriff'].map(tech=>{const r=(rows||[]).filter(x=>x.technique===tech);return `<section><h4>${tech} – WO → WOHIN</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Von</th><th>Nach</th><th>Anzahl</th><th>Erfolg</th><th>Fehler</th></tr></thead><tbody>${r.map(x=>`<tr><td>${x.from}</td><td>${x.to}</td><td>${x.n}</td><td>${x.successRate}</td><td>${x.errorRate}</td></tr>`).join('')||'<tr><td colspan="5">Keine Daten</td></tr>'}</tbody></table></div></section>`}).join('')}</div>`;
}
export function renderPlayerContext(rows,{escapeHtml=x=>String(x??'')}={}){
 return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Spielerin</th><th>Aktionen</th><th>K1 Wirkung</th><th>K2 Wirkung</th><th>K3 Wirkung</th><th>häufigste Technik</th><th>auffällige Rotation</th></tr></thead><tbody>${(rows||[]).map(r=>{const rot=[...(r.rotations||[])].sort((a,b)=>b.n-a.n)[0];return `<tr><td>${escapeHtml(r.player?.abbreviation||'–')}</td><td>${r.actions}</td><td>${r.phases?.K1?.winRate||'–'}</td><td>${r.phases?.K2?.winRate||'–'}</td><td>${r.phases?.K3?.winRate||'–'}</td><td>${escapeHtml(r.techniques?.[0]?.[0]||'–')}</td><td>${rot?`${rot.rotation} (${rot.winRate})`:'–'}</td></tr>`}).join('')||'<tr><td colspan="7">Keine Spielerinnenkontexte</td></tr>'}</tbody></table></div><p class="small">Wirkung bezeichnet Mannschaftserfolg in Rallys mit Beteiligung der Spielerin; keine Kausalitätsaussage.</p>`;
}
export function renderChainPatterns(rows,{escapeHtml=x=>String(x??'')}={}){
 return `<p class="small">Gewinn-/Verlustketten vergleichen wiederkehrende Aktionsfolgen im Rallykontext.</p><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Phase</th><th>Rotation</th><th>Kette</th><th>Anzahl</th><th>gewonnen</th><th>verloren</th><th>Erfolg</th></tr></thead><tbody>${(rows||[]).map(r=>`<tr><td>${r.phase}</td><td>${r.rotation||'–'}</td><td>${escapeHtml(r.label)}</td><td>${r.n}</td><td>${r.won}</td><td>${r.lost}</td><td>${r.winRate}</td></tr>`).join('')||'<tr><td colspan="7">Keine Kettenmuster</td></tr>'}</tbody></table></div>`;
}
export function renderServe(rows,{escapeHtml=x=>String(x??'')}={}){return `<p class="small"><strong>Direktes Aufschlagergebnis:</strong> Fehler + Ass + im Spiel = 100 %. <strong>Breakquote</strong> ist separat die gewonnene Rally nach eigenem Aufschlag und darf nicht zu diesen drei Anteilen addiert werden.</p><div class="analysis-table-wrap"><table class="data-table compact serve-semantic-table"><thead><tr><th rowspan="2">Spielerin</th><th rowspan="2">Technik</th><th rowspan="2">Ziel</th><th rowspan="2">Aufschläge</th><th colspan="3">Direktes Aufschlagergebnis = 100 %</th><th colspan="2">Folgewirkung</th></tr><tr><th>Fehler</th><th>Ass</th><th>Im Spiel</th><th>Breakquote</th><th>Gegner +/#</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.p)}</td><td>${escapeHtml(g.tech)}</td><td>${g.z}</td><td>${g.n}</td><td>${g.errorRate}</td><td>${g.aceRate}</td><td>${g.inPlayRate}</td><td>${g.breakRate}</td><td>${g.oppPositiveRate}</td></tr>`).join('')||'<tr><td colspan="9">Keine Aufschläge</td></tr>'}</tbody></table></div>`;}
export function renderReception(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Spielerin</th><th>Rotation</th><th>Annahmen</th><th>+/#</th><th># perfekt</th><th>= Fehler</th><th>Sideout danach</th><th>First Ball</th><th>Folgeangriff #</th><th>häufigstes Zuspielziel</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.p)}</td><td>${g.rotation||'–'}</td><td>${g.n}</td><td>${g.posRate}</td><td>${g.perfectRate}</td><td>${g.errorRate}</td><td>${g.sideoutRate}</td><td>${g.firstBallRate}</td><td>${g.followKillRate||'–'}</td><td>${g.setTargets?.[0]?.[0]||'–'}</td></tr>`).join('')||'<tr><td colspan="10">Keine Annahmen</td></tr>'}</tbody></table></div>`;}
export function renderSet(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Zuspielerin</th><th>Rotation</th><th>Phase</th><th>von</th><th>Ziel</th><th>Tempo</th><th>Distanz</th><th>Annahme davor</th><th>Anzahl</th><th>Folgeangriff #</th><th>Rally gewonnen</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.p||'–')}</td><td>${g.rotation||'–'}</td><td>${g.phase||'–'}</td><td>${g.from}</td><td>${g.to}</td><td>${escapeHtml(g.tempo)}</td><td>${escapeHtml(g.dist)}</td><td>${escapeHtml(g.recQ||'–')}</td><td>${g.n}</td><td>${g.followKillRate}</td><td>${g.rallyWinRate||'–'}</td></tr>`).join('')||'<tr><td colspan="11">Keine Zuspiele</td></tr>'}</tbody></table></div>`;}
export function renderAttack(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Angreiferin</th><th>Rotation</th><th>Phase</th><th>Von</th><th>Nach</th><th>Annahme davor</th><th>Tempo</th><th>Angriffe</th><th>Punktquote</th><th>Fehler</th><th>Geblockt</th><th>Effizienz</th><th>Rally gewonnen</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.p)}</td><td>${g.rotation||'–'}</td><td>${g.phase||'–'}</td><td>${g.from}</td><td>${g.to}</td><td>${escapeHtml(g.recQ||'–')}</td><td>${escapeHtml(g.tempo||'–')}</td><td>${g.n}</td><td>${g.killRate}</td><td>${g.errorRate}</td><td>${g.blockedRate}</td><td>${g.efficiency}</td><td>${g.rallyWinRate||'–'}</td></tr>`).join('')||'<tr><td colspan="13">Keine Angriffe</td></tr>'}</tbody></table></div>`;}
export function renderChains(rows,{escapeHtml=x=>String(x??'')}={}){return `<p class="small">Kontextketten werden nur gebildet, wenn Annahme → Zuspiel → Angriff innerhalb derselben Rally vollständig erfasst wurde.</p><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Annahme</th><th>Qual.</th><th>Zuspiel von→nach</th><th>Angriff</th><th>von→nach</th><th>Anzahl</th><th>Angriff #</th><th>Rally +</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.rec)}</td><td>${escapeHtml(g.rq)}</td><td>P${g.sz} → P${g.st}</td><td>${escapeHtml(g.att)}</td><td>P${g.az} → P${g.at}</td><td>${g.n}</td><td>${g.killRate}</td><td>${g.winRate}</td></tr>`).join('')||'<tr><td colspan="8">Noch keine vollständigen Kontextketten</td></tr>'}</tbody></table></div>`;}
export function renderOpponent(result,{escapeHtml=x=>String(x??'')}={}){
 const attackRows=result.attacks.map(g=>`<tr><td>${escapeHtml(g.player)}</td><td>${g.from}</td><td>${g.to}</td><td>${g.n}</td><td>${g.share}</td></tr>`).join('');
 const serveRows=result.serves.map(g=>`<tr><td>${g.target}</td><td>${escapeHtml(g.technique)}</td><td>${g.n}</td><td>${g.share}</td></tr>`).join('');
 const setRows=result.sets.map(g=>`<tr><td>${g.from}</td><td>${g.to}</td><td>${g.n}</td><td>${g.share}</td></tr>`).join('');
 const contextRows=(result.contextRows||[]).slice(0,30).map(g=>`<tr><td>${escapeHtml(g.technique)}</td><td>${escapeHtml(g.rotation||'–')}</td><td>${g.from}</td><td>${g.to}</td><td>${g.n}</td><td>${g.oppWinRate}</td></tr>`).join('');
 return `<div class="analysis-split"><section><h4>Angriffstendenzen</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Spielerin</th><th>Von</th><th>Nach</th><th>Anzahl</th><th>Anteil</th></tr></thead><tbody>${attackRows||'<tr><td colspan="5">Keine Gegnerangriffe</td></tr>'}</tbody></table></div></section><section><h4>Aufschlagziele</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Ziel</th><th>Technik</th><th>Anzahl</th><th>Anteil</th></tr></thead><tbody>${serveRows||'<tr><td colspan="4">Keine Gegneraufschläge</td></tr>'}</tbody></table></div></section><section><h4>Zuspielwege</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Von</th><th>Nach</th><th>Anzahl</th><th>Anteil</th></tr></thead><tbody>${setRows||'<tr><td colspan="4">Keine Gegnerzuspiele</td></tr>'}</tbody></table></div></section></div><h4>Gegner im Rallykontext</h4><div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Technik</th><th>eigene Rotation</th><th>Von</th><th>Nach</th><th>Anzahl</th><th>Gegner gewinnt Rally</th></tr></thead><tbody>${contextRows||'<tr><td colspan="6">Keine ausreichenden Gegnerkontexte</td></tr>'}</tbody></table></div>`;
}
export function renderOverview(result,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-kpis"><div><strong>${result.matches}</strong><span>Spiele</span></div><div><strong>${result.rallies}</strong><span>Rallys</span></div><div><strong>${result.rallyRate}</strong><span title="${metricTip('rallyRate')}">Rallyquote Wir</span></div><div><strong>${result.k1Sideout}</strong><span title="${metricTip('k1Sideout')}">K1 Sideout</span></div><div><strong>${result.k2Break}</strong><span title="${metricTip('k2Break')}">K2 Break</span></div><div><strong>${result.firstBall}</strong><span title="${metricTip('firstBall')}">First Ball</span></div></div><div class="analysis-split"><section><h4>Eigene direkte Punktaktionen</h4><div class="analysis-mini-bars">${Object.entries(result.bySource).map(([k,n])=>`<div><span>${k}</span><strong>${n}</strong></div>`).join('')}<div><span>Gegnerfehler</span><strong>${result.opponentErrors}</strong></div></div></section><section><h4>Auffälligkeiten</h4><ul class="analysis-insights">${result.insights.map(x=>`<li>${escapeHtml(x)}</li>`).join('')||'<li>Noch zu wenig Daten für belastbare Tendenzen.</li>'}</ul></section></div><h4>Rotationen</h4>${renderRotations(result.rotations)}`;}
export function renderRallies(rows,{escapeHtml=x=>String(x??'')}={}){return `<div class="analysis-table-wrap"><table class="data-table compact"><thead><tr><th>Rally</th><th>Satz</th><th>Rotation</th><th>Aktionen</th><th>Gewinner</th><th>Stand</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.rally)}</td><td>${escapeHtml(r.set)}</td><td>${escapeHtml(r.rotation)}</td><td>${r.actions}</td><td>${r.winner==='us'?'Wir':'Gegner'}</td><td>${escapeHtml(r.scoreUs)}:${escapeHtml(r.scoreThem)}</td></tr>`).join('')||'<tr><td colspan="6">Keine abgeschlossenen Rallys</td></tr>'}</tbody></table></div>`;}
export function renderCompareStats(stats){return `<div class="analysis-kpis"><div><strong>${stats.matches}</strong><span>Spiele</span></div><div><strong>${stats.actions}</strong><span>Aktionen</span></div><div><strong>${stats.rallies}</strong><span>Rallys</span></div><div><strong>${stats.own}:${stats.opp}</strong><span>Rallys Wir:Gegner</span></div><div><strong>${stats.win}</strong><span title="${metricTip('rallyRate')}">Rallyquote Wir</span></div></div>`;}
export function createAnalysisController({query,getMatches,getPinnedMatchId,clearPinnedMatch,filterMatches,filterEvents,stats,actions,rotations,qualityLevel,getPlayers,getSeasons,getTeams,getMatchTypes,getSelectedTeamId,escapeHtml,qualityChip,version,matchNames,matchScoreText,analyzeView,renderView,onSaveResult}){
  const resultWindow=createResultWindow();
  const value=(prefix,id)=>query('#'+prefix+id)?.value||'';
  const filteredMatches=(prefix='a')=>filterMatches(getMatches(),{from:value(prefix,'From'),to:value(prefix,'To'),seasonId:value(prefix,'Season'),teamId:value(prefix,'Team'),oppId:value(prefix,'Opponent'),typeId:value(prefix,'Type')},getPinnedMatchId());
  const filteredEvents=(matches,prefix='a')=>filterEvents(matches,{playerId:value(prefix,'Player'),technique:value(prefix,'Technique'),rotation:value(prefix,'Rotation'),setNo:value(prefix,'Set')},actions);
  const filterBlock=(prefix,title,compare=false)=>{const dates=getMatches().map(m=>String(m?.matchDate||m?.events?.find(e=>e.createdAt)?.createdAt||'').slice(0,10)).filter(Boolean).sort();return filterBlockHtml({prefix,title,compare,minDate:dates[0]||'',maxDate:dates.at(-1)||'',seasons:getSeasons(),teams:getTeams(),matchTypes:getMatchTypes(),players:getPlayers(),actions,rotations,selectedTeamId:getSelectedTeamId(),escapeHtml});};
  const filterValues=prefix=>Object.fromEntries(['From','To','Season','Team','Opponent','Type','Player','Technique','Rotation','Set'].map(id=>[id,value(prefix,id)]));
  const titleFor=view=>query('#analysisView')?.selectedOptions?.[0]?.textContent?.trim()||view;
  const compute=(view,events,matches)=>{const context={actions,rotations,qualityLevel,players:getPlayers()};return view==='priorityA'||view==='priorityB'?analyzePriorityView(view,events,matches,context):analyzeView(view,events,matches,context)};
  const showResult=({view,content,compareContent='',compare=false,record=null,teamReport=null,trainerReport=null})=>{const full=record?record.content:resultShellHtml({content,compareContent,compare}),title=record?.title||titleFor(view),subtitle=record?`Gespeichert am ${new Date(record.savedAt).toLocaleString('de-DE')}`:`Erstellt am ${new Date().toLocaleString('de-DE')}`,report=record?.teamReport||teamReport||null,coach=record?.trainerReport||trainerReport||null;resultWindow.open({title:`Analyse · ${title}`,subtitle,content:full,teamReport:report,trainerReport:coach,accept:record?()=>{}:async()=>{const filters={a:filterValues('a'),b:compare?filterValues('b'):null,compare};const saved={id:analysisResultId(view,filters),schema:3,view,title,filters,content:full,teamReport:report,trainerReport:coach,savedAt:new Date().toISOString(),version};saveAnalysisResult(saved);await onSaveResult?.(saved);},print:{title:`VolleyTakt · ${title}`,subtitle,content:full}})};
  const renderResult=()=>{
    const selectedView=query('#analysisView')?.value||'priorityA';
    const ma=filteredMatches('a'),ea=filteredEvents(ma,'a'),compare=query('#analysisCompare')?.checked,mb=compare?filteredMatches('b'):[],eb=compare?filteredEvents(mb,'b'):[];
    const buildDash=(events,matches)=>({overview:compute('overview',events,matches),k1k2:compute('k1k2',events,matches),firstball:compute('firstball',events,matches),k3:compute('k3',events,matches),rotations:compute('rotations',events,matches),serve:compute('serve',events,matches),reception:compute('reception',events,matches),sets:compute('sets',events,matches),attacks:compute('attacks',events,matches),blockdef:compute('blockdef',events,matches),targets:compute('targets',events,matches),players:compute('players',events,matches),playerContext:compute('playerContext',events,matches),playersOverview:compute('playersOverview',events,matches),opponent:compute('opponent',events,matches),chains:compute('chains',events,matches),quality:compute('techniques',events,matches),rallies:compute('rallies',events,matches)});
    const host=query('#analysisResult');
    if(!ma.length){host.innerHTML='<div class="card analysis-empty"><strong>Keine Spiele im gewählten Zeitraum.</strong><p class="small">Bitte Zeitraum oder weitere Filter anpassen. Das aktuell geladene Spiel wird nicht als Ersatz verwendet.</p></div>';return;}
    const dash=buildDash(ea,ma), dashB=compare?buildDash(eb,mb):null;
    const compareSummary=compare?{a:dash.overview,b:dashB.overview}:null;
    const num=v=>{const n=Number.parseFloat(String(v??'').replace(',','.'));return Number.isFinite(n)?n:null};
    const compareDeep=compare?(()=>{
      const a=compute('compareDeep',ea,ma),b=compute('compareDeep',eb,mb);
      const labels={rallyRate:'Rallyquote',k1Sideout:'K1',firstBall:'First Ball',k2Break:'K2',k3WinRate:'K3',receptionPositive:'Annahme +/#',attackEfficiency:'Angriffseffizienz'};
      return Object.keys(labels).map(key=>{const av=num(a[key]),bv=num(b[key]),delta=av==null||bv==null?null:bv-av;return {key,label:labels[key],delta,direction:delta==null?'na':delta>0?'up':delta<0?'down':'same',deltaLabel:delta==null?'–':`${delta>0?'+':''}${delta.toFixed(1).replace('.',',')} PP`}});
    })():null;
    host.innerHTML=analysisDashboardHtml(dash,{activeView:selectedView,compareSummary,compareDeep});
    const filtersA=filterValues('a');
    const teamReport=buildTeamReport({matches:ma,dash,filters:filtersA,matchNames,matchScoreText});
    const trainerReport=buildTrainerReport({matches:ma,dash,filters:filtersA,matchNames,matchScoreText});
    trainerReport.exportBase=reportExportBase({matches:ma,filters:filtersA,matchNames,target:'Trainer'});
    const teamBtn=host.querySelector('[data-analysis-team-report]');
    if(teamBtn)teamBtn.onclick=()=>resultWindow.openDashboardReports({report:teamReport,trainer:trainerReport});
    host.querySelectorAll('[data-analysis-detail-view]').forEach(button=>button.onclick=()=>{
      const view=button.dataset.analysisDetailView,ra=compute(view,ea,ma);
      const base=renderView(view,ra,{actions,escapeHtml,qualityChip});
      const content=`<div class="analysis-modern-detail">${detailVizHtml(view,ra)}${insightsHtml(view,ra,{events:ea,actions})}<section class="analysis-detail-table"><h4>Detaildaten</h4>${base}</section></div>`;
      let compareContent='';
      if(compare){
        const rb=compute(view,eb,mb),baseB=renderView(view,rb,{actions,escapeHtml,qualityChip});
        compareContent=`<div class="card analysis-compare-result"><h3>Vergleich B</h3><div class="analysis-modern-detail">${detailVizHtml(view,rb)}${insightsHtml(view,rb,{events:eb,actions})}<section class="analysis-detail-table">${baseB}</section></div></div>`;
      }
      showResult({view,content,compareContent,compare,teamReport,trainerReport});
    });
    const closePopovers=except=>host.querySelectorAll('.analysis-card-popover').forEach(p=>{if(p!==except)p.hidden=true});
    host.querySelectorAll('.analysis-card-help').forEach(button=>button.onclick=e=>{
      e.stopPropagation();const pop=button.closest('.analysis-dashboard-card')?.querySelector('.analysis-card-popover');if(!pop)return;const next=pop.hidden;closePopovers(pop);pop.hidden=!next;button.classList.toggle('active',next);
    });
    host.onclick=e=>{if(!e.target.closest('.analysis-card-help')&&!e.target.closest('.analysis-card-popover'))closePopovers(null)};
  };
  const draw=()=>{const matches=getMatches(),pinned=getPinnedMatchId()?matches.find(m=>m.matchId===getPinnedMatchId()):null,pinnedHtml=pinned?`<div class="card analysis-pinned"><strong>Spielanalyse: ${escapeHtml(matchNames(pinned))}</strong><span>${escapeHtml(pinned.matchDate||'')} · ${escapeHtml(matchScoreText(pinned))}</span><button id="analysisAllMatches">Alle Spiele analysieren</button></div>`:'';query('#drawerBody').innerHTML=analysisDrawerHtml({pinnedHtml,version,filterAHtml:filterBlock('a','Zeitraum / Filter A'),filterBHtml:filterBlock('b','Zeitraum / Filter B',true)});if(query('#analysisAllMatches'))query('#analysisAllMatches').onclick=()=>{clearPinnedMatch();draw();};query('#analysisCompare').onchange=()=>{query('#analysisB').hidden=!query('#analysisCompare').checked;};const updateSaved=()=>{const view=query('#analysisView')?.value||'priorityA',saved=latestAnalysisResult(view),button=query('#openSavedAnalysis');button.hidden=!saved;button.onclick=saved?()=>showResult({view,content:saved.content,record:saved}):null};query('#runAnalysis').onclick=renderResult;const viewSelect=query('#analysisView'),helpBtn=query('#analysisViewHelp'),helpText=query('#analysisViewHelpText');const updateHelp=()=>{const view=viewSelect?.value||'priorityA',tip=analysisTip(view);if(helpBtn)helpBtn.title=tip;if(helpText)helpText.textContent=tip};if(viewSelect)viewSelect.onchange=()=>{updateSaved();updateHelp()};if(helpBtn)helpBtn.onclick=()=>{if(helpText)helpText.hidden=!helpText.hidden};updateSaved();updateHelp();};
  return {draw,renderResult,filteredMatches,filteredEvents};
}
export function renderView(view,result,context={}){
  if(view==='priorityA')return renderPriorityA(result,context);
  if(view==='priorityB')return renderPriorityB(result,context);
  if(view==='k1k2')return renderK1K2(result,context);
  if(view==='firstball')return renderFirstBallDeep(result,context);
  if(view==='k3')return renderK3(result);
  if(view==='rotations')return renderRotations(result);
  if(view==='serve')return renderServe(result,context);
  if(view==='reception')return renderReception(result,context);
  if(view==='sets')return renderSet(result,context);
  if(view==='attacks')return renderAttack(result,context);
  if(view==='blockdef')return renderBlockDefense(result,context);
  if(view==='targets')return renderTargets(result);
  if(view==='chains')return renderChains(result,context);
  if(view==='chainPatterns')return renderChainPatterns(result,context);
  if(view==='opponent')return renderOpponent(result,context);
  if(view==='playersOverview')return renderPlayersOverview(result,context);
  if(view==='players')return renderPlayers(result,context);
  if(view==='playerContext')return renderPlayerContext(result,context);
  if(view==='techniques')return renderQuality(result,context);
  if(view==='rallies')return renderRallies(result,context);
  return renderOverview(result,context);
}
import {analyzePriorityView} from './priorities.js';
import {analysisResultId,latestAnalysisResult,saveAnalysisResult} from './cache.js';
import {createResultWindow} from './result-window.js';
import {buildTeamReport} from './team-report.js';
import {buildTrainerReport} from './trainer-report.js';
import {reportExportBase} from './report-export.js';
